// -----------------------------------------------------------------------------
// SpMS API and its PostgreSQL on Azure: Container Apps + PostgreSQL Flexible
// Server 16 + Key Vault + Log Analytics / Application Insights.
//
//   az deployment group create -g rg-spms-dev -f infra/api.bicep \
//     -p apiImage=<registry>/spms-api:<tag> pgAdminPassword=<secret> \
//        entraAuthority=https://login.microsoftonline.com/<tenant>/v2.0 entraAudience=api://spms \
//        webOrigin=https://<front-end-host> openfgaPresharedKey=<secret>
//
// then deploy OpenFGA into the SAME environment (its ingress is internal):
//
//   az deployment group create -g rg-spms-dev -f infra/openfga.bicep \
//     -p keyVaultName=<output keyVaultName> managedEnvironmentName=<output environmentName>
//
// and, per release: start the migrate job, then roll the API revision.
//
// Decisions encoded here:
//   * One image, three entry points: the API, `--migrate` (a manual job the
//     pipeline starts before a revision rolls) and `--maintain` (a nightly
//     scheduled job: partitions ahead, published outbox months dropped). An
//     app instance never migrates: two instances starting together would race.
//   * Every secret is a Key Vault secret read through a user-assigned identity.
//     The template writes the ones it is given (connection strings, keys) and
//     never echoes them; rotating one is a new secret version, not a redeploy.
//   * The database has three logins: an admin (bootstrap only, creates the
//     roles), the owner (migrations and maintenance) and the runtime login
//     (spms_app, row-level security applies). The API holds the runtime and
//     owner strings; only the jobs hold the admin one.
//   * PostgreSQL is public-endpoint with "allow Azure services" for R1, TLS
//     required. Private networking (VNet-integrated environment + private
//     endpoint) is the R2 hardening step and changes no application setting.
// -----------------------------------------------------------------------------
targetScope = 'resourceGroup'

@description('Prefix for resource names.')
@minLength(3)
@maxLength(11)
param namePrefix string = 'spms'

@allowed(['dev', 'test', 'prod'])
param environmentName string = 'dev'

param location string = resourceGroup().location

@description('API image, e.g. myregistry.azurecr.io/spms-api:1.2.3 (built from backend/Dockerfile).')
param apiImage string

@secure()
@description('Preshared key the API presents to OpenFGA (the same value openfga.bicep reads as openfga-preshared-key).')
param openfgaPresharedKey string

@description('Registry server the image is pulled from; empty for a public registry.')
param registryServer string = ''

@description('PostgreSQL administrator login (bootstrap only).')
param pgAdminLogin string = 'spmsadmin'

@secure()
@description('PostgreSQL administrator password.')
param pgAdminPassword string

@secure()
@description('Password for the spms_owner login (migrations). Generated by the pipeline and kept in Key Vault.')
param pgOwnerPassword string

@secure()
@description('Password for the runtime login (spms_app).')
param pgAppPassword string

@allowed(['Burstable', 'GeneralPurpose', 'MemoryOptimized'])
param pgTier string = 'Burstable'
param pgSku string = 'Standard_B1ms'
@minValue(32)
param pgStorageGb int = 32
@minValue(7)
@maxValue(35)
param pgBackupDays int = 14
@description('Zone-redundant high availability; recommended for prod.')
param pgHighAvailability bool = false

@description('Entra ID authority, https://login.microsoftonline.com/{tenant}/v2.0')
param entraAuthority string
@description('The API app registration\'s application id URI.')
param entraAudience string

@description('The web front end\'s origin (Front Door host), for CORS and guest links.')
param webOrigin string

@description('OpenFGA URL inside the environment (openfga.bicep output); empty until OpenFGA is deployed.')
param openfgaUrl string = ''

@secure()
@description('Field-protection key, base64 of 32 random bytes (Protection:Keys:k1).')
param protectionKey string
@secure()
@description('Lookup-hash key, base64 of 32 random bytes (Protection:LookupKey).')
param lookupKey string
@secure()
@description('Guest session signing key, base64 of 32+ random bytes.')
param guestSigningKey string
@secure()
@description('Key the metrics scraper presents as X-Metrics-Key.')
param metricsKey string

@minValue(1)
param minReplicas int = 1
@description('Keep at 1: the live board fans out in-process, so a second replica would not hear changes made on the first.')
@minValue(1)
@maxValue(1)
param maxReplicas int = 1

var baseName = '${namePrefix}-${environmentName}'
var pgServerName = '${baseName}-pg-${substring(uniqueString(resourceGroup().id), 0, 6)}'
var keyVaultName = take('${namePrefix}${environmentName}kv${uniqueString(resourceGroup().id)}', 24)
var pgHost = '${pgServerName}.postgres.database.azure.com'

// ------------------------------------------------------------------ logs ----

resource logs 'Microsoft.OperationalInsights/workspaces@2023-09-01' = {
  name: '${baseName}-logs'
  location: location
  properties: {
    sku: { name: 'PerGB2018' }
    retentionInDays: environmentName == 'prod' ? 90 : 30
  }
}

resource insights 'Microsoft.Insights/components@2020-02-02' = {
  name: '${baseName}-ai'
  location: location
  kind: 'web'
  properties: {
    Application_Type: 'web'
    WorkspaceResourceId: logs.id
    IngestionMode: 'LogAnalytics'
  }
}

// ------------------------------------------------------------- identity ----

resource identity 'Microsoft.ManagedIdentity/userAssignedIdentities@2023-01-31' = {
  name: '${baseName}-api-id'
  location: location
}

// ----------------------------------------------------------- key vault ----

resource vault 'Microsoft.KeyVault/vaults@2023-07-01' = {
  name: keyVaultName
  location: location
  properties: {
    tenantId: subscription().tenantId
    sku: { family: 'A', name: 'standard' }
    enableRbacAuthorization: true
    enableSoftDelete: true
    softDeleteRetentionInDays: 90
    enablePurgeProtection: true
    publicNetworkAccess: 'Enabled'
  }
}

var secretsUser = subscriptionResourceId('Microsoft.Authorization/roleDefinitions', '4633458b-17de-408a-b874-0445c86b69e6')

resource secretsAccess 'Microsoft.Authorization/roleAssignments@2022-04-01' = {
  name: guid(vault.id, identity.id, secretsUser)
  scope: vault
  properties: {
    principalId: identity.properties.principalId
    principalType: 'ServicePrincipal'
    roleDefinitionId: secretsUser
  }
}

var connection = 'Host=${pgHost};Port=5432;Database=spms;SSL Mode=Require;Trust Server Certificate=false'

var secretValues = [
  { name: 'pg-admin-connection', value: '${connection};Username=${pgAdminLogin};Password=${pgAdminPassword}' }
  { name: 'pg-owner-connection', value: '${connection};Username=spms_owner_login;Password=${pgOwnerPassword}' }
  { name: 'pg-app-connection', value: '${connection};Username=spms_app_login;Password=${pgAppPassword};Maximum Pool Size=50' }
  { name: 'protection-key-k1', value: protectionKey }
  { name: 'protection-lookup-key', value: lookupKey }
  { name: 'guest-signing-key', value: guestSigningKey }
  { name: 'metrics-key', value: metricsKey }
  { name: 'pg-owner-password', value: pgOwnerPassword }
  { name: 'pg-app-password', value: pgAppPassword }
  { name: 'openfga-preshared-key', value: openfgaPresharedKey }
  { name: 'openfga-datastore-uri', value: 'postgres://${pgAdminLogin}:${uriComponent(pgAdminPassword)}@${pgHost}:5432/openfga?sslmode=require' }
]

resource secrets 'Microsoft.KeyVault/vaults/secrets@2023-07-01' = [for s in secretValues: {
  parent: vault
  name: s.name
  properties: { value: s.value }
}]

// ------------------------------------------------------------ postgres ----

resource pg 'Microsoft.DBforPostgreSQL/flexibleServers@2023-12-01-preview' = {
  name: pgServerName
  location: location
  sku: { name: pgSku, tier: pgTier }
  properties: {
    version: '16'
    administratorLogin: pgAdminLogin
    administratorLoginPassword: pgAdminPassword
    storage: { storageSizeGB: pgStorageGb, autoGrow: 'Enabled' }
    backup: { backupRetentionDays: pgBackupDays, geoRedundantBackup: environmentName == 'prod' ? 'Enabled' : 'Disabled' }
    highAvailability: { mode: pgHighAvailability ? 'ZoneRedundant' : 'Disabled' }
    authConfig: { activeDirectoryAuth: 'Disabled', passwordAuth: 'Enabled' }
  }
}

resource pgAzure 'Microsoft.DBforPostgreSQL/flexibleServers/firewallRules@2023-12-01-preview' = {
  parent: pg
  name: 'AllowAzureServices'
  properties: { startIpAddress: '0.0.0.0', endIpAddress: '0.0.0.0' }
}

// Row-level security and the schema's functions need nothing beyond core
// Postgres; btree_gist backs the exclusion constraints (no double booking) and
// pg_trgm the name search.
resource pgExtensions 'Microsoft.DBforPostgreSQL/flexibleServers/configurations@2023-12-01-preview' = {
  parent: pg
  name: 'azure.extensions'
  properties: { value: 'BTREE_GIST,PG_TRGM', source: 'user-override' }
}

resource pgTls 'Microsoft.DBforPostgreSQL/flexibleServers/configurations@2023-12-01-preview' = {
  parent: pg
  name: 'require_secure_transport'
  properties: { value: 'on', source: 'user-override' }
}

resource spmsDb 'Microsoft.DBforPostgreSQL/flexibleServers/databases@2023-12-01-preview' = {
  parent: pg
  name: 'spms'
  properties: { charset: 'UTF8', collation: 'en_US.utf8' }
}

resource openfgaDb 'Microsoft.DBforPostgreSQL/flexibleServers/databases@2023-12-01-preview' = {
  parent: pg
  name: 'openfga'
  properties: { charset: 'UTF8', collation: 'en_US.utf8' }
}

// --------------------------------------------------------- environment ----

resource environment 'Microsoft.App/managedEnvironments@2024-03-01' = {
  name: '${baseName}-env'
  location: location
  properties: {
    appLogsConfiguration: {
      destination: 'log-analytics'
      logAnalyticsConfiguration: {
        customerId: logs.properties.customerId
        sharedKey: logs.listKeys().primarySharedKey
      }
    }
  }
}

var kv = vault.properties.vaultUri
var appSecrets = [
  { name: 'pg-app', keyVaultUrl: '${kv}secrets/pg-app-connection', identity: identity.id }
  { name: 'pg-owner', keyVaultUrl: '${kv}secrets/pg-owner-connection', identity: identity.id }
  { name: 'protection-k1', keyVaultUrl: '${kv}secrets/protection-key-k1', identity: identity.id }
  { name: 'lookup-key', keyVaultUrl: '${kv}secrets/protection-lookup-key', identity: identity.id }
  { name: 'guest-signing', keyVaultUrl: '${kv}secrets/guest-signing-key', identity: identity.id }
  { name: 'metrics-key', keyVaultUrl: '${kv}secrets/metrics-key', identity: identity.id }
  { name: 'openfga-key', keyVaultUrl: '${kv}secrets/openfga-preshared-key', identity: identity.id }
]
var jobSecrets = concat(appSecrets, [
  { name: 'pg-admin', keyVaultUrl: '${kv}secrets/pg-admin-connection', identity: identity.id }
  { name: 'pg-owner-password', keyVaultUrl: '${kv}secrets/pg-owner-password', identity: identity.id }
  { name: 'pg-app-password', keyVaultUrl: '${kv}secrets/pg-app-password', identity: identity.id }
])

var commonEnv = [
  { name: 'ASPNETCORE_ENVIRONMENT', value: environmentName == 'prod' ? 'Production' : 'Staging' }
  { name: 'ConnectionStrings__Spms', secretRef: 'pg-app' }
  { name: 'ConnectionStrings__SpmsOwner', secretRef: 'pg-owner' }
  { name: 'Database__RuntimeRole', value: 'spms_app' }
  { name: 'Database__MigrationRole', value: 'spms_owner' }
  { name: 'Protection__ActiveKey', value: 'k1' }
  { name: 'Protection__Keys__k1', secretRef: 'protection-k1' }
  { name: 'Protection__LookupKey', secretRef: 'lookup-key' }
  { name: 'Observability__LogFormat', value: 'json' }
  { name: 'APPLICATIONINSIGHTS_CONNECTION_STRING', value: insights.properties.ConnectionString }
]

var registries = empty(registryServer) ? [] : [ { server: registryServer, identity: identity.id } ]

resource migrate 'Microsoft.App/jobs@2024-03-01' = {
  name: '${baseName}-migrate'
  location: location
  identity: { type: 'UserAssigned', userAssignedIdentities: { '${identity.id}': {} } }
  dependsOn: [secretsAccess, secrets, spmsDb]
  properties: {
    environmentId: environment.id
    configuration: {
      triggerType: 'Manual'
      replicaTimeout: 1800
      replicaRetryLimit: 0
      manualTriggerConfig: { parallelism: 1, replicaCompletionCount: 1 }
      secrets: jobSecrets
      registries: registries
    }
    template: {
      containers: [
        {
          name: 'migrate'
          image: apiImage
          args: ['--migrate']
          // The admin string is here only: it creates the roles and the two logins, then the owner migrates.
          env: concat(commonEnv, [
            { name: 'ConnectionStrings__SpmsAdmin', secretRef: 'pg-admin' }
            { name: 'Database__Logins__Owner__Name', value: 'spms_owner_login' }
            { name: 'Database__Logins__Owner__Password', secretRef: 'pg-owner-password' }
            { name: 'Database__Logins__App__Name', value: 'spms_app_login' }
            { name: 'Database__Logins__App__Password', secretRef: 'pg-app-password' }
          ])
          resources: { cpu: json('0.5'), memory: '1Gi' }
        }
      ]
    }
  }
}

resource maintain 'Microsoft.App/jobs@2024-03-01' = {
  name: '${baseName}-maintain'
  location: location
  identity: { type: 'UserAssigned', userAssignedIdentities: { '${identity.id}': {} } }
  dependsOn: [secretsAccess, secrets]
  properties: {
    environmentId: environment.id
    configuration: {
      triggerType: 'Schedule'
      replicaTimeout: 1800
      replicaRetryLimit: 1
      scheduleTriggerConfig: { cronExpression: '17 3 * * *', parallelism: 1, replicaCompletionCount: 1 }
      secrets: appSecrets
      registries: registries
    }
    template: {
      containers: [
        {
          name: 'maintain'
          image: apiImage
          args: ['--maintain']
          env: commonEnv
          resources: { cpu: json('0.25'), memory: '0.5Gi' }
        }
      ]
    }
  }
}

resource api 'Microsoft.App/containerApps@2024-03-01' = {
  name: '${baseName}-api'
  location: location
  identity: { type: 'UserAssigned', userAssignedIdentities: { '${identity.id}': {} } }
  dependsOn: [secretsAccess, secrets]
  properties: {
    managedEnvironmentId: environment.id
    configuration: {
      activeRevisionsMode: 'Single'
      secrets: appSecrets
      registries: registries
      ingress: {
        external: true
        targetPort: 8080
        transport: 'http'
        allowInsecure: false
      }
    }
    template: {
      containers: [
        {
          name: 'api'
          image: apiImage
          env: concat(commonEnv, [
            { name: 'Auth__Authority', value: entraAuthority }
            { name: 'Auth__Audience', value: entraAudience }
            { name: 'Auth__GuestSigningKey', secretRef: 'guest-signing' }
            { name: 'Authorization__OpenFga__ApiUrl', value: openfgaUrl }
            { name: 'Authorization__OpenFga__ApiToken', secretRef: 'openfga-key' }
            { name: 'Cors__AllowedOrigins__0', value: webOrigin }
            { name: 'Guest__Links__BaseUrl', value: webOrigin }
            { name: 'Observability__MetricsKey', secretRef: 'metrics-key' }
            { name: 'Jobs__Enabled', value: 'true' }
          ])
          resources: { cpu: json('1.0'), memory: '2Gi' }
          probes: [
            { type: 'Liveness', httpGet: { path: '/health/live', port: 8080 }, periodSeconds: 10 }
            { type: 'Readiness', httpGet: { path: '/health/ready', port: 8080 }, periodSeconds: 5 }
            { type: 'Startup', httpGet: { path: '/health/live', port: 8080 }, periodSeconds: 5, failureThreshold: 30 }
          ]
        }
      ]
      scale: {
        // One replica until the live board's fan-out moves to a shared bus: a board
        // connected to one instance does not hear changes made on another.
        minReplicas: minReplicas
        maxReplicas: maxReplicas
        rules: [ { name: 'http', http: { metadata: { concurrentRequests: '50' } } } ]
      }
    }
  }
}

output apiUrl string = 'https://${api.properties.configuration.ingress.fqdn}'
output keyVaultName string = vault.name
output environmentName string = environment.name
output postgresHost string = pgHost
@description('Start this before rolling a revision: az containerapp job start -g <rg> -n <name>.')
output migrateJobName string = migrate.name
