-- 01 core: generated by database/tools/generate.py from database/model/. Do not edit.
-- may reference: (nothing)

CREATE SCHEMA IF NOT EXISTS core AUTHORIZATION spms_owner;

-- ---------------------------------------------------------------------------
-- Foundation functions shared by every module.
-- ---------------------------------------------------------------------------

-- UUIDv7 (RFC 9562): 48-bit Unix ms timestamp, version 7, variant 10.
-- The application generates ids itself (a command knows its id before commit);
-- this default exists for SQL-side inserts, seeds and repairs.
CREATE FUNCTION core.uuid_v7() RETURNS uuid
LANGUAGE plpgsql VOLATILE PARALLEL SAFE AS $$
DECLARE
    ms bigint := floor(extract(epoch FROM clock_timestamp()) * 1000);
    b  bytea  := uuid_send(gen_random_uuid());
BEGIN
    b := set_byte(b, 0, ((ms >> 40) & 255)::int);
    b := set_byte(b, 1, ((ms >> 32) & 255)::int);
    b := set_byte(b, 2, ((ms >> 24) & 255)::int);
    b := set_byte(b, 3, ((ms >> 16) & 255)::int);
    b := set_byte(b, 4, ((ms >> 8)  & 255)::int);
    b := set_byte(b, 5, (ms & 255)::int);
    b := set_byte(b, 6, (get_byte(b, 6) & 15) | 112);   -- version 7
    b := set_byte(b, 8, (get_byte(b, 8) & 63) | 128);   -- variant 10
    RETURN encode(b, 'hex')::uuid;
END $$;

-- Request scope. Set with SET LOCAL semantics (is_local = true) inside the
-- request's transaction, so a pooled connection can never carry one request's
-- tenant into the next. Unset means NULL / empty, and every policy fails closed.
CREATE FUNCTION core.current_tenant_id() RETURNS uuid
LANGUAGE sql STABLE PARALLEL SAFE AS $$
    SELECT nullif(current_setting('app.tenant_id', true), '')::uuid
$$;

CREATE FUNCTION core.current_property_ids() RETURNS uuid[]
LANGUAGE sql STABLE PARALLEL SAFE AS $$
    SELECT coalesce(nullif(current_setting('app.property_ids', true), '')::uuid[], '{}'::uuid[])
$$;

CREATE FUNCTION core.current_principal_id() RETURNS uuid
LANGUAGE sql STABLE PARALLEL SAFE AS $$
    SELECT nullif(current_setting('app.principal_id', true), '')::uuid
$$;

-- The one call the API makes after BEGIN. Refuses outside a transaction block,
-- because set_config(..., true) there would silently last only one statement.
CREATE FUNCTION core.begin_scope(p_tenant uuid, p_properties uuid[], p_principal uuid,
                                 p_correlation text DEFAULT NULL) RETURNS void
LANGUAGE plpgsql AS $$
BEGIN
    IF p_tenant IS NULL THEN
        RAISE EXCEPTION 'begin_scope: tenant is required' USING ERRCODE = '22023';
    END IF;
    -- In an implicit single-statement transaction the two timestamps coincide.
    IF transaction_timestamp() = statement_timestamp() THEN
        RAISE EXCEPTION 'begin_scope must run inside an explicit transaction' USING ERRCODE = '25P01';
    END IF;
    PERFORM set_config('app.tenant_id', p_tenant::text, true);
    PERFORM set_config('app.property_ids', coalesce(p_properties, '{}')::text, true);
    PERFORM set_config('app.principal_id', coalesce(p_principal::text, ''), true);
    PERFORM set_config('app.correlation_id', coalesce(p_correlation, ''), true);
END $$;

-- updated_at on every mutable row.
CREATE FUNCTION core.touch() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
    NEW.updated_at := now();
    NEW.created_at := OLD.created_at;
    NEW.created_by := OLD.created_by;
    RETURN NEW;
END $$;

-- Versioned rows: optimistic concurrency is enforced by the database, not only
-- by the ORM. Every update must advance version by exactly one, so a writer that
-- forgot the concurrency check (or a hand-written UPDATE) cannot overwrite a
-- newer row silently (DEC-005).
CREATE FUNCTION core.touch_versioned() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
    IF NEW.version IS DISTINCT FROM OLD.version + 1 THEN
        RAISE EXCEPTION '%.%: version must advance from % to %, got %',
            TG_TABLE_SCHEMA, TG_TABLE_NAME, OLD.version, OLD.version + 1, NEW.version
            USING ERRCODE = '40001';
    END IF;
    NEW.updated_at := now();
    NEW.created_at := OLD.created_at;
    NEW.created_by := OLD.created_by;
    RETURN NEW;
END $$;

-- Append-only. Raises rather than ignoring, so a bug fails its test. The only
-- permitted change is a redaction performed by core.redact_* functions, which
-- set spms.redacting for the duration of one statement.
CREATE FUNCTION core.forbid_mutation() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
    IF TG_OP = 'UPDATE' AND current_setting('spms.redacting', true) = 'on' THEN
        RETURN NEW;
    END IF;
    RAISE EXCEPTION '%.% is append-only (% refused)', TG_TABLE_SCHEMA, TG_TABLE_NAME, TG_OP
        USING ERRCODE = '42501';
END $$;

-- Monthly range partitions in UTC. Run ahead by a maintenance job; the DEFAULT
-- partition is a safety net that must stay empty (tests assert it).
CREATE FUNCTION core.ensure_monthly_partitions(p_parent regclass, p_from date, p_months int)
RETURNS void LANGUAGE plpgsql AS $$
DECLARE
    m date;
    sch text;
    rel text;
BEGIN
    SELECT n.nspname, c.relname INTO sch, rel
      FROM pg_class c JOIN pg_namespace n ON n.oid = c.relnamespace WHERE c.oid = p_parent;
    FOR i IN 0 .. p_months - 1 LOOP
        m := (date_trunc('month', p_from) + make_interval(months => i))::date;
        EXECUTE format(
            'CREATE TABLE IF NOT EXISTS %I.%I PARTITION OF %s FOR VALUES FROM (%L) TO (%L)',
            sch, rel || '_' || to_char(m, 'YYYYMM'), p_parent,
            (m::timestamp AT TIME ZONE 'UTC'),
            ((m + interval '1 month')::timestamp AT TIME ZONE 'UTC'));
    END LOOP;
END $$;

CREATE TABLE core.tenant (
    tenant_id                      uuid NOT NULL DEFAULT core.uuid_v7(),
    code                           text NOT NULL,
    name                           text NOT NULL,
    default_locale                 text NOT NULL DEFAULT 'en-US',
    default_currency_code          char(3) NOT NULL DEFAULT 'USD',
    data_region                    text NOT NULL,
    status                         text NOT NULL DEFAULT 'Active',
    version                        integer NOT NULL DEFAULT 1,
    created_at                     timestamptz NOT NULL DEFAULT now(),
    created_by                     uuid,
    updated_at                     timestamptz NOT NULL DEFAULT now(),
    updated_by                     uuid,
    correlation_id                 text,
    CONSTRAINT tenant_pkey PRIMARY KEY (tenant_id),
    CONSTRAINT tenant_code_ck CHECK (code ~ '^[a-z0-9][a-z0-9-]{1,62}$'),
    CONSTRAINT tenant_default_currency_code_ck CHECK (default_currency_code ~ '^[A-Z]{3}$'),
    CONSTRAINT tenant_version_ck CHECK (version >= 1),
    CONSTRAINT tenant_status_known CHECK (status IN ('Active', 'Suspended', 'Closed')),
    CONSTRAINT tenant_code_uq UNIQUE (code)
);
COMMENT ON TABLE core.tenant IS 'Tenant directory. RLS restricts it to the current tenant like every other table. [R0; §24 Tenancy; spec ''tenant directory itself now has RLS'']';
COMMENT ON COLUMN core.tenant.data_region IS 'data residency region';

CREATE TABLE core.property (
    property_id                    uuid NOT NULL DEFAULT core.uuid_v7(),
    tenant_id                      uuid NOT NULL,
    code                           text NOT NULL,
    name                           text NOT NULL,
    timezone                       text NOT NULL,
    currency_code                  char(3) NOT NULL,
    locale                         text NOT NULL DEFAULT 'en-US',
    operating_mode                 text NOT NULL DEFAULT 'Standalone',
    opening_hours                  jsonb NOT NULL DEFAULT '[]',
    room_turnover_minutes          integer NOT NULL DEFAULT 15,
    provider_transition_minutes    integer NOT NULL DEFAULT 10,
    status                         text NOT NULL DEFAULT 'Active',
    source_system                  text NOT NULL DEFAULT 'Spa',
    source_key                     text,
    version                        integer NOT NULL DEFAULT 1,
    created_at                     timestamptz NOT NULL DEFAULT now(),
    created_by                     uuid,
    updated_at                     timestamptz NOT NULL DEFAULT now(),
    updated_by                     uuid,
    correlation_id                 text,
    CONSTRAINT property_pkey PRIMARY KEY (property_id),
    CONSTRAINT property_currency_code_ck CHECK (currency_code ~ '^[A-Z]{3}$'),
    CONSTRAINT property_operating_mode_ck CHECK (operating_mode IN ('Standalone', 'MarqueeIntegrated')),
    CONSTRAINT property_opening_hours_ck CHECK (jsonb_typeof(opening_hours) = 'array'),
    CONSTRAINT property_room_turnover_minutes_ck CHECK (room_turnover_minutes >= 0),
    CONSTRAINT property_provider_transition_minutes_ck CHECK (provider_transition_minutes >= 0),
    CONSTRAINT property_version_ck CHECK (version >= 1),
    CONSTRAINT property_tenant_identity_uq UNIQUE (tenant_id, property_id),
    CONSTRAINT property_status_known CHECK (status IN ('Active', 'Inactive', 'Closed')),
    CONSTRAINT property_code_uq UNIQUE (tenant_id, code)
);
COMMENT ON TABLE core.property IS 'A spa property. operating_mode is the default; capability_ownership decides per capability and time. [§53.2 Operating modes; DEC-001; DEC-011]';
COMMENT ON COLUMN core.property.timezone IS 'IANA zone; the board and business day are always read in it';
COMMENT ON COLUMN core.property.opening_hours IS 'weekly hours: [{"day": 1, "opens": "09:00", "closes": "21:00"}], ISO day 1 = Monday';

CREATE TABLE core.principal (
    principal_id                   uuid NOT NULL DEFAULT core.uuid_v7(),
    tenant_id                      uuid NOT NULL,
    principal_type                 text NOT NULL,
    display_name                   text NOT NULL,
    last_authenticated_at          timestamptz,
    status                         text NOT NULL DEFAULT 'Active',
    version                        integer NOT NULL DEFAULT 1,
    created_at                     timestamptz NOT NULL DEFAULT now(),
    created_by                     uuid,
    updated_at                     timestamptz NOT NULL DEFAULT now(),
    updated_by                     uuid,
    correlation_id                 text,
    CONSTRAINT principal_pkey PRIMARY KEY (principal_id),
    CONSTRAINT principal_principal_type_ck CHECK (principal_type IN ('Staff', 'Guest', 'Service', 'Device')),
    CONSTRAINT principal_version_ck CHECK (version >= 1),
    CONSTRAINT principal_tenant_identity_uq UNIQUE (tenant_id, principal_id),
    CONSTRAINT principal_status_known CHECK (status IN ('Active', 'Disabled', 'Revoked'))
);
COMMENT ON TABLE core.principal IS 'Anyone or anything that acts: staff, guest, service or device. principal_id is the OpenFGA user id (user:<principal_id>), so replacing the identity provider never rewrites authorization tuples. [§24 Authentication; OpenFGA user identity]';

CREATE TABLE core.principal_login (
    principal_login_id             uuid NOT NULL DEFAULT core.uuid_v7(),
    tenant_id                      uuid NOT NULL,
    principal_id                   uuid NOT NULL,
    login_type                     text NOT NULL,
    idp_issuer                     text NOT NULL,
    idp_subject                    text NOT NULL,
    username                       text,
    mfa_required                   boolean NOT NULL DEFAULT true,
    credential_rotated_at          timestamptz,
    last_authenticated_at          timestamptz,
    status                         text NOT NULL DEFAULT 'Active',
    version                        integer NOT NULL DEFAULT 1,
    created_at                     timestamptz NOT NULL DEFAULT now(),
    created_by                     uuid,
    updated_at                     timestamptz NOT NULL DEFAULT now(),
    updated_by                     uuid,
    correlation_id                 text,
    CONSTRAINT principal_login_pkey PRIMARY KEY (principal_login_id),
    CONSTRAINT principal_login_login_type_ck CHECK (login_type IN ('EntraUser', 'EntraApplication')),
    CONSTRAINT principal_login_version_ck CHECK (version >= 1),
    CONSTRAINT principal_login_tenant_identity_uq UNIQUE (tenant_id, principal_login_id),
    CONSTRAINT principal_login_status_known CHECK (status IN ('Active', 'Disabled', 'Locked')),
    CONSTRAINT principal_login_subject_uq UNIQUE (idp_issuer, idp_subject)
);
COMMENT ON TABLE core.principal_login IS 'An external identity that signs in as a principal: Entra user (oid) or client-credentials app. [§24 OIDC/SSO, MFA, service accounts; §Security and audit (no password rows)]';
COMMENT ON COLUMN core.principal_login.idp_subject IS 'Entra object id (oid) or application object id';

CREATE TABLE core.device_registration (
    device_registration_id         uuid NOT NULL DEFAULT core.uuid_v7(),
    tenant_id                      uuid NOT NULL,
    property_id                    uuid NOT NULL,
    principal_id                   uuid NOT NULL,
    device_kind                    text NOT NULL,
    device_name                    text NOT NULL,
    public_key_spki                bytea NOT NULL,
    last_seen_at                   timestamptz,
    revoked_at                     timestamptz,
    revoked_by                     uuid,
    status                         text NOT NULL DEFAULT 'Pending',
    version                        integer NOT NULL DEFAULT 1,
    created_at                     timestamptz NOT NULL DEFAULT now(),
    created_by                     uuid,
    updated_at                     timestamptz NOT NULL DEFAULT now(),
    updated_by                     uuid,
    correlation_id                 text,
    CONSTRAINT device_registration_pkey PRIMARY KEY (device_registration_id),
    CONSTRAINT device_registration_device_kind_ck CHECK (device_kind IN ('ProviderTablet', 'Kiosk', 'FrontDesk')),
    CONSTRAINT device_registration_version_ck CHECK (version >= 1),
    CONSTRAINT device_registration_tenant_identity_uq UNIQUE (tenant_id, device_registration_id),
    CONSTRAINT device_registration_status_known CHECK (status IN ('Pending', 'Active', 'Revoked')),
    CONSTRAINT device_registration_revocation_complete CHECK ((status = 'Revoked') = (revoked_at IS NOT NULL)),
    CONSTRAINT device_registration_principal_uq UNIQUE (principal_id)
);
COMMENT ON COLUMN core.device_registration.public_key_spki IS 'device key for the encrypted offline queue';

CREATE TABLE core.capability_ownership (
    ownership_id                   uuid NOT NULL DEFAULT core.uuid_v7(),
    tenant_id                      uuid NOT NULL,
    property_id                    uuid NOT NULL,
    capability_code                text NOT NULL,
    owner_system                   text NOT NULL,
    effective_range                tstzrange NOT NULL,
    approved_by                    uuid,
    approved_at                    timestamptz,
    status                         text NOT NULL DEFAULT 'Proposed',
    version                        integer NOT NULL DEFAULT 1,
    created_at                     timestamptz NOT NULL DEFAULT now(),
    created_by                     uuid,
    updated_at                     timestamptz NOT NULL DEFAULT now(),
    updated_by                     uuid,
    correlation_id                 text,
    CONSTRAINT capability_ownership_pkey PRIMARY KEY (ownership_id),
    CONSTRAINT capability_ownership_capability_code_ck CHECK (capability_code ~ '^[A-Z][A-Za-z]+$'),
    CONSTRAINT capability_ownership_owner_system_ck CHECK (owner_system IN ('Spa', 'Marquee', 'Pms', 'Pos', 'External')),
    CONSTRAINT capability_ownership_version_ck CHECK (version >= 1),
    CONSTRAINT capability_ownership_tenant_identity_uq UNIQUE (tenant_id, ownership_id),
    CONSTRAINT capability_ownership_status_known CHECK (status IN ('Proposed', 'Approved', 'Active', 'Superseded', 'Rejected')),
    CONSTRAINT capability_ownership_approval_complete CHECK ((approved_by IS NULL) = (approved_at IS NULL)),
    CONSTRAINT capability_ownership_active_is_approved CHECK (status NOT IN ('Approved', 'Active') OR approved_by IS NOT NULL),
    CONSTRAINT capability_ownership_proposer_not_approver CHECK (approved_by IS NULL OR approved_by IS DISTINCT FROM created_by)
);
COMMENT ON TABLE core.capability_ownership IS 'Exactly one authority per capability, property and instant. Kept typed (not a setting) because the database must enforce it. [DEC-001 (APPROVED critical hybrid rule); MCI-001]';
COMMENT ON COLUMN core.capability_ownership.capability_code IS 'e.g. Catalog, Pricing, Payment, Inventory, Entitlement, GuestProfile';

CREATE TABLE core.setting (
    setting_id                     uuid NOT NULL DEFAULT core.uuid_v7(),
    tenant_id                      uuid NOT NULL,
    property_id                    uuid,
    setting_key                    text NOT NULL,
    value_json                     jsonb NOT NULL,
    deployment_scope               text NOT NULL DEFAULT 'Production',
    reason                         text,
    approved_by                    uuid,
    approved_at                    timestamptz,
    status                         text NOT NULL DEFAULT 'Proposed',
    effective_from                 timestamptz NOT NULL DEFAULT now(),
    effective_to                   timestamptz,
    version                        integer NOT NULL DEFAULT 1,
    created_at                     timestamptz NOT NULL DEFAULT now(),
    created_by                     uuid,
    updated_at                     timestamptz NOT NULL DEFAULT now(),
    updated_by                     uuid,
    correlation_id                 text,
    CONSTRAINT setting_pkey PRIMARY KEY (setting_id),
    CONSTRAINT setting_setting_key_ck CHECK (setting_key ~ '^[a-z][a-z0-9_]*(\.[a-z0-9_]+)+$'),
    CONSTRAINT setting_deployment_scope_ck CHECK (deployment_scope IN ('Training', 'Pilot', 'Production')),
    CONSTRAINT setting_version_ck CHECK (version >= 1),
    CONSTRAINT setting_tenant_identity_uq UNIQUE (tenant_id, setting_id),
    CONSTRAINT setting_status_known CHECK (status IN ('Proposed', 'Approved', 'Active', 'Superseded', 'Rejected')),
    CONSTRAINT setting_effective_range_ck CHECK (effective_to IS NULL OR effective_to > effective_from),
    CONSTRAINT setting_active_is_approved CHECK (status NOT IN ('Approved', 'Active') OR approved_by IS NOT NULL),
    CONSTRAINT setting_approver_not_author CHECK (approved_by IS NULL OR approved_by IS DISTINCT FROM created_by)
);
COMMENT ON TABLE core.setting IS 'Governed, effective-dated configuration. One active value per key, scope and instant. A change is a new row that someone other than its author approves; the old row becomes Superseded. Keys are namespaced: feature.*, policy.cancellation, policy.deposit, retention.<data_class>, messaging.quiet_hours ... [§Configurable policies and accountability; SEC-005 retention; SEC-014 segregation of duties]';

CREATE TABLE core.code_list (
    code_list_id                   uuid NOT NULL DEFAULT core.uuid_v7(),
    tenant_id                      uuid NOT NULL,
    property_id                    uuid,
    list_code                      text NOT NULL,
    code                           text NOT NULL,
    label                          text NOT NULL,
    sort_order                     integer NOT NULL DEFAULT 0,
    attributes                     jsonb NOT NULL DEFAULT '{}',
    status                         text NOT NULL DEFAULT 'Active',
    version                        integer NOT NULL DEFAULT 1,
    created_at                     timestamptz NOT NULL DEFAULT now(),
    created_by                     uuid,
    updated_at                     timestamptz NOT NULL DEFAULT now(),
    updated_by                     uuid,
    correlation_id                 text,
    CONSTRAINT code_list_pkey PRIMARY KEY (code_list_id),
    CONSTRAINT code_list_list_code_ck CHECK (list_code IN ('ReasonCode', 'Department', 'Tender', 'LicenseType', 'RevenueCenter', 'ServiceCategory', 'ItemCategory')),
    CONSTRAINT code_list_version_ck CHECK (version >= 1),
    CONSTRAINT code_list_tenant_identity_uq UNIQUE (tenant_id, code_list_id),
    CONSTRAINT code_list_status_known CHECK (status IN ('Active', 'Retired')),
    CONSTRAINT code_list_code_uq UNIQUE NULLS NOT DISTINCT (tenant_id, property_id, list_code, code)
);
COMMENT ON TABLE core.code_list IS 'Simple enumerations: (list_code, code) -> label + attributes. Referencing columns hold the code; commands validate it. Anything with money or enforcement semantics stays a typed table. [CON override reasons; tenders; §Provider license catalog (37 types); §Income accounts]';
COMMENT ON COLUMN core.code_list.attributes IS 'list-specific: ReasonCode {domain, requires_note}; Tender {tender_type}; LicenseType {issuer, jurisdiction_dependent}';

CREATE TABLE core.audit_event (
    audit_id                       uuid NOT NULL DEFAULT core.uuid_v7(),
    tenant_id                      uuid NOT NULL,
    property_id                    uuid,
    actor_type                     text NOT NULL,
    actor_principal_id             uuid,
    on_behalf_of_principal_id      uuid,
    purpose                        text,
    action                         text NOT NULL,
    entity_type                    text NOT NULL,
    entity_id                      uuid NOT NULL,
    entity_version                 integer,
    from_status                    text,
    to_status                      text,
    before_hash                    char(64),
    after_hash                     char(64),
    before_data                    jsonb,
    after_data                     jsonb,
    changed_fields                 text[],
    conflict_codes                 text[] NOT NULL DEFAULT '{}',
    reason_code                    text,
    reason_text                    text,
    authorization_decision         jsonb,
    db_role                        text NOT NULL DEFAULT current_user,
    occurred_at                    timestamptz NOT NULL DEFAULT now(),
    correlation_id                 text,
    CONSTRAINT audit_event_pkey PRIMARY KEY (audit_id, occurred_at),
    CONSTRAINT audit_event_actor_type_ck CHECK (actor_type IN ('Staff', 'Guest', 'Service', 'Device', 'System'))
) PARTITION BY RANGE (occurred_at);
COMMENT ON TABLE core.audit_event IS 'Append-only business and security audit, and the history of every entity (status changes, visit events, service and policy changes). before/after_data never contain restricted columns. [SEC-004; SEC-007/008 sensitive-read audit; DEC-005]';
COMMENT ON COLUMN core.audit_event.on_behalf_of_principal_id IS 'delegated authority or AI acting for a principal';
COMMENT ON COLUMN core.audit_event.authorization_decision IS 'OpenFGA check: {relation, object, model_id, allowed}';

CREATE TABLE core.audit_seal (
    audit_seal_id                  uuid NOT NULL DEFAULT core.uuid_v7(),
    tenant_id                      uuid NOT NULL,
    period_start                   timestamptz NOT NULL,
    period_end                     timestamptz NOT NULL,
    row_count                      bigint NOT NULL,
    digest                         char(64) NOT NULL,
    previous_digest                char(64),
    created_at                     timestamptz NOT NULL DEFAULT now(),
    created_by                     uuid,
    CONSTRAINT audit_seal_pkey PRIMARY KEY (audit_seal_id),
    CONSTRAINT audit_seal_row_count_ck CHECK (row_count >= 0),
    CONSTRAINT audit_seal_tenant_identity_uq UNIQUE (tenant_id, audit_seal_id),
    CONSTRAINT audit_seal_period_forward CHECK (period_end > period_start),
    CONSTRAINT audit_seal_period_uq UNIQUE (tenant_id, period_start)
);
COMMENT ON TABLE core.audit_seal IS 'Periodic digest over a tenant''s audit rows, chained to the previous seal. [§24 Audit: tamper-evident]';

CREATE TABLE core.event_outbox (
    event_id                       uuid NOT NULL DEFAULT core.uuid_v7(),
    tenant_id                      uuid NOT NULL,
    property_id                    uuid,
    occurred_at                    timestamptz NOT NULL DEFAULT now(),
    event_type                     text NOT NULL,
    schema_version                 integer NOT NULL DEFAULT 1,
    aggregate_type                 text NOT NULL,
    aggregate_id                   uuid NOT NULL,
    aggregate_version              integer,
    payload                        jsonb NOT NULL,
    causation_id                   text,
    published_at                   timestamptz,
    attempt_count                  integer NOT NULL DEFAULT 0,
    next_attempt_at                timestamptz NOT NULL DEFAULT now(),
    last_error                     text,
    updated_at                     timestamptz NOT NULL DEFAULT now(),
    correlation_id                 text,
    CONSTRAINT event_outbox_pkey PRIMARY KEY (event_id, occurred_at),
    CONSTRAINT event_outbox_attempt_count_ck CHECK (attempt_count >= 0)
) PARTITION BY RANGE (occurred_at);
COMMENT ON TABLE core.event_outbox IS 'Written in the same transaction as the change it announces. No secrets, card data or clinical content. [NFR-001; §26 Integration operations; FGA tuple sync]';

CREATE TABLE core.event_inbox (
    event_inbox_id                 uuid NOT NULL DEFAULT core.uuid_v7(),
    tenant_id                      uuid NOT NULL,
    consumer_name                  text NOT NULL,
    event_id                       uuid NOT NULL,
    outcome                        text NOT NULL,
    processed_at                   timestamptz NOT NULL DEFAULT now(),
    correlation_id                 text,
    CONSTRAINT event_inbox_pkey PRIMARY KEY (event_inbox_id),
    CONSTRAINT event_inbox_outcome_ck CHECK (outcome IN ('Processed', 'Skipped', 'Failed')),
    CONSTRAINT event_inbox_tenant_identity_uq UNIQUE (tenant_id, event_inbox_id),
    CONSTRAINT event_inbox_consumer_event_uq UNIQUE (tenant_id, consumer_name, event_id)
);

CREATE TABLE core.idempotency_record (
    idempotency_record_id          uuid NOT NULL DEFAULT core.uuid_v7(),
    tenant_id                      uuid NOT NULL,
    property_id                    uuid NOT NULL,
    operation                      text NOT NULL,
    route                          text NOT NULL,
    idempotency_key                text NOT NULL,
    request_hash                   char(64) NOT NULL,
    request_hash_format            text NOT NULL DEFAULT 'sha256-canonical-json-v1',
    completed                      boolean NOT NULL DEFAULT false,
    response_code                  integer,
    response_cipher                bytea,
    key_version                    text,
    expires_at                     timestamptz NOT NULL,
    created_at                     timestamptz NOT NULL DEFAULT now(),
    created_by                     uuid,
    updated_at                     timestamptz NOT NULL DEFAULT now(),
    updated_by                     uuid,
    correlation_id                 text,
    CONSTRAINT idempotency_record_pkey PRIMARY KEY (idempotency_record_id),
    CONSTRAINT idempotency_record_idempotency_key_ck CHECK (length(idempotency_key) BETWEEN 8 AND 200),
    CONSTRAINT idempotency_record_tenant_identity_uq UNIQUE (tenant_id, idempotency_record_id),
    CONSTRAINT idempotency_record_cipher_has_key CHECK ((response_cipher IS NULL) = (key_version IS NULL)),
    CONSTRAINT idempotency_record_key_uq UNIQUE (tenant_id, property_id, operation, route, idempotency_key)
);
COMMENT ON TABLE core.idempotency_record IS 'Claim-then-complete. Scoped by tenant, property, operation and route. [API-001]';

CREATE TABLE core.external_mapping (
    external_mapping_id            uuid NOT NULL DEFAULT core.uuid_v7(),
    tenant_id                      uuid NOT NULL,
    property_id                    uuid,
    entity_type                    text NOT NULL,
    local_id                       uuid NOT NULL,
    external_property_reference    text,
    source_version                 bigint,
    snapshot_cipher                bytea,
    encryption_key_version         text,
    status                         text NOT NULL DEFAULT 'Active',
    effective_from                 timestamptz NOT NULL DEFAULT now(),
    effective_to                   timestamptz,
    source_system                  text NOT NULL DEFAULT 'Spa',
    source_key                     text,
    version                        integer NOT NULL DEFAULT 1,
    created_at                     timestamptz NOT NULL DEFAULT now(),
    created_by                     uuid,
    updated_at                     timestamptz NOT NULL DEFAULT now(),
    updated_by                     uuid,
    correlation_id                 text,
    CONSTRAINT external_mapping_pkey PRIMARY KEY (external_mapping_id),
    CONSTRAINT external_mapping_version_ck CHECK (version >= 1),
    CONSTRAINT external_mapping_tenant_identity_uq UNIQUE (tenant_id, external_mapping_id),
    CONSTRAINT external_mapping_status_known CHECK (status IN ('Active', 'Retired', 'ReviewRequired')),
    CONSTRAINT external_mapping_effective_range_ck CHECK (effective_to IS NULL OR effective_to > effective_from),
    CONSTRAINT external_mapping_is_external CHECK (source_system <> 'Spa' AND source_key IS NOT NULL),
    CONSTRAINT external_mapping_cipher_has_key CHECK ((snapshot_cipher IS NULL) = (encryption_key_version IS NULL)),
    CONSTRAINT external_mapping_external_uq UNIQUE NULLS NOT DISTINCT (tenant_id, source_system, entity_type, external_property_reference, source_key)
);
COMMENT ON TABLE core.external_mapping IS 'Local entity <-> external system id. source_system/source_key are the external side. [MCI-004 identity and external mappings; PMS/POS ingestion (Marquee-Integrated mode)]';

CREATE TABLE core.legal_hold (
    legal_hold_id                  uuid NOT NULL DEFAULT core.uuid_v7(),
    tenant_id                      uuid NOT NULL,
    property_id                    uuid,
    entity_table                   text NOT NULL,
    entity_key                     text NOT NULL,
    hold_scope                     text NOT NULL,
    reason                         text NOT NULL,
    starts_at                      timestamptz NOT NULL DEFAULT now(),
    ends_at                        timestamptz,
    released_at                    timestamptz,
    released_by                    uuid,
    status                         text NOT NULL DEFAULT 'Active',
    source_system                  text NOT NULL DEFAULT 'Spa',
    source_key                     text,
    version                        integer NOT NULL DEFAULT 1,
    created_at                     timestamptz NOT NULL DEFAULT now(),
    created_by                     uuid,
    updated_at                     timestamptz NOT NULL DEFAULT now(),
    updated_by                     uuid,
    correlation_id                 text,
    CONSTRAINT legal_hold_pkey PRIMARY KEY (legal_hold_id),
    CONSTRAINT legal_hold_hold_scope_ck CHECK (hold_scope IN ('Entity', 'Guest', 'Matter')),
    CONSTRAINT legal_hold_version_ck CHECK (version >= 1),
    CONSTRAINT legal_hold_tenant_identity_uq UNIQUE (tenant_id, legal_hold_id),
    CONSTRAINT legal_hold_status_known CHECK (status IN ('Active', 'Released')),
    CONSTRAINT legal_hold_release_complete CHECK ((status = 'Released') = (released_at IS NOT NULL AND released_by IS NOT NULL))
);
COMMENT ON TABLE core.legal_hold IS 'Kept typed: retention and erasure jobs must be able to find active holds with one indexed query. [SEC-005 legal hold]';

ALTER TABLE core.property ADD CONSTRAINT property_tenant_fk FOREIGN KEY (tenant_id) REFERENCES core.tenant (tenant_id);
ALTER TABLE core.principal ADD CONSTRAINT principal_tenant_fk FOREIGN KEY (tenant_id) REFERENCES core.tenant (tenant_id);
ALTER TABLE core.principal_login ADD CONSTRAINT principal_login_principal_id_fk FOREIGN KEY (tenant_id, principal_id) REFERENCES core.principal (tenant_id, principal_id) ON DELETE RESTRICT;
CREATE INDEX principal_login_principal_id_ix ON core.principal_login (tenant_id, principal_id);
ALTER TABLE core.principal_login ADD CONSTRAINT principal_login_tenant_fk FOREIGN KEY (tenant_id) REFERENCES core.tenant (tenant_id);
ALTER TABLE core.device_registration ADD CONSTRAINT device_registration_principal_id_fk FOREIGN KEY (tenant_id, principal_id) REFERENCES core.principal (tenant_id, principal_id) ON DELETE RESTRICT;
CREATE INDEX device_registration_principal_id_ix ON core.device_registration (tenant_id, principal_id);
CREATE INDEX device_registration_scope_ix ON core.device_registration (tenant_id, property_id);
ALTER TABLE core.device_registration ADD CONSTRAINT device_registration_tenant_fk FOREIGN KEY (tenant_id) REFERENCES core.tenant (tenant_id);
ALTER TABLE core.device_registration ADD CONSTRAINT device_registration_property_fk FOREIGN KEY (tenant_id, property_id) REFERENCES core.property (tenant_id, property_id);
CREATE INDEX capability_ownership_scope_ix ON core.capability_ownership (tenant_id, property_id);
ALTER TABLE core.capability_ownership ADD CONSTRAINT capability_ownership_tenant_fk FOREIGN KEY (tenant_id) REFERENCES core.tenant (tenant_id);
ALTER TABLE core.capability_ownership ADD CONSTRAINT capability_ownership_property_fk FOREIGN KEY (tenant_id, property_id) REFERENCES core.property (tenant_id, property_id);
CREATE INDEX setting_scope_ix ON core.setting (tenant_id, property_id);
ALTER TABLE core.setting ADD CONSTRAINT setting_tenant_fk FOREIGN KEY (tenant_id) REFERENCES core.tenant (tenant_id);
ALTER TABLE core.setting ADD CONSTRAINT setting_property_fk FOREIGN KEY (tenant_id, property_id) REFERENCES core.property (tenant_id, property_id);
ALTER TABLE core.code_list ADD CONSTRAINT code_list_tenant_fk FOREIGN KEY (tenant_id) REFERENCES core.tenant (tenant_id);
ALTER TABLE core.code_list ADD CONSTRAINT code_list_property_fk FOREIGN KEY (tenant_id, property_id) REFERENCES core.property (tenant_id, property_id);
ALTER TABLE core.audit_event ADD CONSTRAINT audit_event_tenant_fk FOREIGN KEY (tenant_id) REFERENCES core.tenant (tenant_id);
ALTER TABLE core.audit_event ADD CONSTRAINT audit_event_property_fk FOREIGN KEY (tenant_id, property_id) REFERENCES core.property (tenant_id, property_id);
ALTER TABLE core.audit_seal ADD CONSTRAINT audit_seal_tenant_fk FOREIGN KEY (tenant_id) REFERENCES core.tenant (tenant_id);
CREATE INDEX event_outbox_tenant_ix ON core.event_outbox (tenant_id);
CREATE INDEX event_outbox_scope_ix ON core.event_outbox (tenant_id, property_id);
ALTER TABLE core.event_outbox ADD CONSTRAINT event_outbox_tenant_fk FOREIGN KEY (tenant_id) REFERENCES core.tenant (tenant_id);
ALTER TABLE core.event_outbox ADD CONSTRAINT event_outbox_property_fk FOREIGN KEY (tenant_id, property_id) REFERENCES core.property (tenant_id, property_id);
ALTER TABLE core.event_inbox ADD CONSTRAINT event_inbox_tenant_fk FOREIGN KEY (tenant_id) REFERENCES core.tenant (tenant_id);
ALTER TABLE core.idempotency_record ADD CONSTRAINT idempotency_record_tenant_fk FOREIGN KEY (tenant_id) REFERENCES core.tenant (tenant_id);
ALTER TABLE core.idempotency_record ADD CONSTRAINT idempotency_record_property_fk FOREIGN KEY (tenant_id, property_id) REFERENCES core.property (tenant_id, property_id);
CREATE INDEX external_mapping_scope_ix ON core.external_mapping (tenant_id, property_id);
ALTER TABLE core.external_mapping ADD CONSTRAINT external_mapping_tenant_fk FOREIGN KEY (tenant_id) REFERENCES core.tenant (tenant_id);
ALTER TABLE core.external_mapping ADD CONSTRAINT external_mapping_property_fk FOREIGN KEY (tenant_id, property_id) REFERENCES core.property (tenant_id, property_id);
CREATE INDEX legal_hold_scope_ix ON core.legal_hold (tenant_id, property_id);
ALTER TABLE core.legal_hold ADD CONSTRAINT legal_hold_tenant_fk FOREIGN KEY (tenant_id) REFERENCES core.tenant (tenant_id);
ALTER TABLE core.legal_hold ADD CONSTRAINT legal_hold_property_fk FOREIGN KEY (tenant_id, property_id) REFERENCES core.property (tenant_id, property_id);

CREATE TRIGGER tenant_touch BEFORE UPDATE ON core.tenant FOR EACH ROW EXECUTE FUNCTION core.touch_versioned();
CREATE TRIGGER property_touch BEFORE UPDATE ON core.property FOR EACH ROW EXECUTE FUNCTION core.touch_versioned();
CREATE TRIGGER principal_touch BEFORE UPDATE ON core.principal FOR EACH ROW EXECUTE FUNCTION core.touch_versioned();
CREATE TRIGGER principal_login_touch BEFORE UPDATE ON core.principal_login FOR EACH ROW EXECUTE FUNCTION core.touch_versioned();
CREATE TRIGGER device_registration_touch BEFORE UPDATE ON core.device_registration FOR EACH ROW EXECUTE FUNCTION core.touch_versioned();
CREATE TRIGGER capability_ownership_touch BEFORE UPDATE ON core.capability_ownership FOR EACH ROW EXECUTE FUNCTION core.touch_versioned();
CREATE TRIGGER setting_touch BEFORE UPDATE ON core.setting FOR EACH ROW EXECUTE FUNCTION core.touch_versioned();
CREATE TRIGGER code_list_touch BEFORE UPDATE ON core.code_list FOR EACH ROW EXECUTE FUNCTION core.touch_versioned();
CREATE TRIGGER audit_event_append_only BEFORE UPDATE OR DELETE ON core.audit_event FOR EACH ROW EXECUTE FUNCTION core.forbid_mutation();
DO $$ BEGIN PERFORM core.ensure_monthly_partitions('core.audit_event'::regclass, (date_trunc('month', now() AT TIME ZONE 'UTC') - interval '1 month')::date, 4); END $$;
CREATE TABLE core.audit_event_default PARTITION OF core.audit_event DEFAULT;
CREATE TRIGGER audit_seal_append_only BEFORE UPDATE OR DELETE ON core.audit_seal FOR EACH ROW EXECUTE FUNCTION core.forbid_mutation();
DO $$ BEGIN PERFORM core.ensure_monthly_partitions('core.event_outbox'::regclass, (date_trunc('month', now() AT TIME ZONE 'UTC') - interval '1 month')::date, 4); END $$;
CREATE TABLE core.event_outbox_default PARTITION OF core.event_outbox DEFAULT;
CREATE TRIGGER event_inbox_append_only BEFORE UPDATE OR DELETE ON core.event_inbox FOR EACH ROW EXECUTE FUNCTION core.forbid_mutation();
CREATE TRIGGER idempotency_record_touch BEFORE UPDATE ON core.idempotency_record FOR EACH ROW EXECUTE FUNCTION core.touch();
CREATE TRIGGER external_mapping_touch BEFORE UPDATE ON core.external_mapping FOR EACH ROW EXECUTE FUNCTION core.touch_versioned();
CREATE TRIGGER legal_hold_touch BEFORE UPDATE ON core.legal_hold FOR EACH ROW EXECUTE FUNCTION core.touch_versioned();

ALTER TABLE core.tenant ENABLE ROW LEVEL SECURITY;
ALTER TABLE core.tenant FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_scope ON core.tenant USING (tenant_id = (SELECT core.current_tenant_id()));

ALTER TABLE core.capability_ownership ADD CONSTRAINT capability_ownership_single_authority
    EXCLUDE USING gist (tenant_id WITH =, property_id WITH =, capability_code WITH =, effective_range WITH &&)
    WHERE (status IN ('Approved', 'Active'));

ALTER TABLE core.setting ADD CONSTRAINT setting_single_active
    EXCLUDE USING gist (tenant_id WITH =, (coalesce(property_id, '00000000-0000-0000-0000-000000000000'::uuid)) WITH =,
                        setting_key WITH =, deployment_scope WITH =,
                        tstzrange(effective_from, coalesce(effective_to, 'infinity'), '[)') WITH &&)
    WHERE (status IN ('Approved', 'Active'));
CREATE INDEX audit_event_entity_ix ON core.audit_event (tenant_id, entity_type, entity_id, occurred_at DESC);
CREATE INDEX audit_event_scope_ix ON core.audit_event (tenant_id, property_id, occurred_at DESC);
CREATE INDEX audit_event_actor_ix ON core.audit_event (tenant_id, actor_principal_id, occurred_at DESC);
CREATE INDEX audit_event_correlation_ix ON core.audit_event (correlation_id);
CREATE INDEX event_outbox_pending_ix ON core.event_outbox (next_attempt_at) WHERE published_at IS NULL;
CREATE INDEX idempotency_record_expiry_ix ON core.idempotency_record (expires_at);
CREATE INDEX external_mapping_local_ix ON core.external_mapping (tenant_id, entity_type, local_id);
CREATE INDEX legal_hold_entity_ix ON core.legal_hold (tenant_id, entity_table, entity_key) WHERE status = 'Active';
