-- 02 catalog: generated by database/tools/generate.py from database/model/. Do not edit.
-- may reference: core

CREATE SCHEMA IF NOT EXISTS catalog AUTHORIZATION spms_owner;

CREATE TABLE catalog.service (
    service_id                     uuid NOT NULL DEFAULT core.uuid_v7(),
    tenant_id                      uuid NOT NULL,
    code                           text NOT NULL,
    name                           text NOT NULL,
    catalog_type                   text NOT NULL DEFAULT 'Service',
    category_code                  text,
    short_description              text,
    duration_minutes               integer NOT NULL,
    pre_buffer_minutes             integer NOT NULL DEFAULT 0,
    post_buffer_minutes            integer NOT NULL DEFAULT 0,
    base_price_minor               bigint NOT NULL DEFAULT 0,
    currency_code                  char(3) NOT NULL,
    tax_code                       text,
    revenue_center_code            text,
    capacity_maximum               smallint NOT NULL DEFAULT 1,
    required_resource_type         text,
    required_capabilities          text[] NOT NULL DEFAULT '{}',
    required_license_type_codes    text[] NOT NULL DEFAULT '{}',
    requires_intake                boolean NOT NULL DEFAULT true,
    intake_form_code               text,
    deposit_required               boolean NOT NULL DEFAULT false,
    online_bookable                boolean NOT NULL DEFAULT false,
    minimum_guest_age              smallint,
    status                         text NOT NULL DEFAULT 'Draft',
    effective_from                 timestamptz NOT NULL DEFAULT now(),
    effective_to                   timestamptz,
    source_system                  text NOT NULL DEFAULT 'Spa',
    source_key                     text,
    version                        integer NOT NULL DEFAULT 1,
    created_at                     timestamptz NOT NULL DEFAULT now(),
    created_by                     uuid,
    updated_at                     timestamptz NOT NULL DEFAULT now(),
    updated_by                     uuid,
    correlation_id                 text,
    CONSTRAINT service_pkey PRIMARY KEY (service_id),
    CONSTRAINT service_catalog_type_ck CHECK (catalog_type IN ('Service', 'AddOn', 'Package')),
    CONSTRAINT service_duration_minutes_ck CHECK (duration_minutes > 0),
    CONSTRAINT service_pre_buffer_minutes_ck CHECK (pre_buffer_minutes >= 0),
    CONSTRAINT service_post_buffer_minutes_ck CHECK (post_buffer_minutes >= 0),
    CONSTRAINT service_base_price_minor_ck CHECK (base_price_minor >= 0),
    CONSTRAINT service_currency_code_ck CHECK (currency_code ~ '^[A-Z]{3}$'),
    CONSTRAINT service_capacity_maximum_ck CHECK (capacity_maximum >= 1),
    CONSTRAINT service_required_resource_type_ck CHECK (required_resource_type IN ('TreatmentRoom', 'WetRoom', 'CoupleRoom', 'Chair')),
    CONSTRAINT service_minimum_guest_age_ck CHECK (minimum_guest_age BETWEEN 0 AND 120),
    CONSTRAINT service_version_ck CHECK (version >= 1),
    CONSTRAINT service_tenant_identity_uq UNIQUE (tenant_id, service_id),
    CONSTRAINT service_status_known CHECK (status IN ('Draft', 'Active', 'Inactive', 'Retired')),
    CONSTRAINT service_effective_range_ck CHECK (effective_to IS NULL OR effective_to > effective_from),
    CONSTRAINT service_code_uq UNIQUE (tenant_id, code)
);
COMMENT ON TABLE catalog.service IS 'Tenant-wide service master. Changes are audited; an appointment freezes the duration and price it booked. [§53.2 Catalog; treatment_service_master.schema.json]';
COMMENT ON COLUMN catalog.service.category_code IS 'code_list ServiceCategory';
COMMENT ON COLUMN catalog.service.duration_minutes IS 'a zero duration would make end_at = start_at and disable CON-002';
COMMENT ON COLUMN catalog.service.revenue_center_code IS 'code_list RevenueCenter';
COMMENT ON COLUMN catalog.service.required_license_type_codes IS 'CON-003: a provider needs a verified credential of each type (code_list LicenseType)';

CREATE TABLE catalog.property_service (
    property_service_id            uuid NOT NULL DEFAULT core.uuid_v7(),
    tenant_id                      uuid NOT NULL,
    property_id                    uuid NOT NULL,
    service_id                     uuid NOT NULL,
    price_minor                    bigint,
    currency_code                  char(3),
    online_bookable                boolean,
    room_turnover_minutes          integer,
    provider_transition_minutes    integer,
    status                         text NOT NULL DEFAULT 'Active',
    effective_from                 timestamptz NOT NULL DEFAULT now(),
    effective_to                   timestamptz,
    source_system                  text NOT NULL DEFAULT 'Spa',
    source_key                     text,
    version                        integer NOT NULL DEFAULT 1,
    created_at                     timestamptz NOT NULL DEFAULT now(),
    created_by                     uuid,
    updated_at                     timestamptz NOT NULL DEFAULT now(),
    updated_by                     uuid,
    correlation_id                 text,
    CONSTRAINT property_service_pkey PRIMARY KEY (property_service_id),
    CONSTRAINT property_service_price_minor_ck CHECK (price_minor >= 0),
    CONSTRAINT property_service_currency_code_ck CHECK (currency_code ~ '^[A-Z]{3}$'),
    CONSTRAINT property_service_room_turnover_minutes_ck CHECK (room_turnover_minutes >= 0),
    CONSTRAINT property_service_provider_transition_minutes_ck CHECK (provider_transition_minutes >= 0),
    CONSTRAINT property_service_version_ck CHECK (version >= 1),
    CONSTRAINT property_service_tenant_identity_uq UNIQUE (tenant_id, property_service_id),
    CONSTRAINT property_service_status_known CHECK (status IN ('Active', 'Inactive')),
    CONSTRAINT property_service_effective_range_ck CHECK (effective_to IS NULL OR effective_to > effective_from),
    CONSTRAINT property_service_price_has_currency CHECK ((price_minor IS NULL) = (currency_code IS NULL)),
    CONSTRAINT property_service_service_uq UNIQUE (tenant_id, property_id, service_id)
);
COMMENT ON TABLE catalog.property_service IS 'Which services a property offers, with its own price and buffer overrides. [§53.2 Operating modes (per-property catalog authority); buffer overrides]';

CREATE TABLE catalog.service_option_rule (
    service_option_rule_id         uuid NOT NULL DEFAULT core.uuid_v7(),
    tenant_id                      uuid NOT NULL,
    service_id                     uuid NOT NULL,
    option_code                    text NOT NULL,
    option_type                    text NOT NULL,
    label                          text NOT NULL,
    price_delta_minor              bigint NOT NULL DEFAULT 0,
    duration_delta_minutes         integer NOT NULL DEFAULT 0,
    max_quantity                   smallint NOT NULL DEFAULT 1,
    status                         text NOT NULL DEFAULT 'Active',
    effective_from                 timestamptz NOT NULL DEFAULT now(),
    effective_to                   timestamptz,
    source_system                  text NOT NULL DEFAULT 'Spa',
    source_key                     text,
    version                        integer NOT NULL DEFAULT 1,
    created_at                     timestamptz NOT NULL DEFAULT now(),
    created_by                     uuid,
    updated_at                     timestamptz NOT NULL DEFAULT now(),
    updated_by                     uuid,
    correlation_id                 text,
    CONSTRAINT service_option_rule_pkey PRIMARY KEY (service_option_rule_id),
    CONSTRAINT service_option_rule_option_type_ck CHECK (option_type IN ('AddOn', 'Enhancement', 'DurationExtension', 'Preference')),
    CONSTRAINT service_option_rule_duration_delta_minutes_ck CHECK (duration_delta_minutes >= 0),
    CONSTRAINT service_option_rule_max_quantity_ck CHECK (max_quantity >= 1),
    CONSTRAINT service_option_rule_version_ck CHECK (version >= 1),
    CONSTRAINT service_option_rule_tenant_identity_uq UNIQUE (tenant_id, service_option_rule_id),
    CONSTRAINT service_option_rule_status_known CHECK (status IN ('Active', 'Retired')),
    CONSTRAINT service_option_rule_effective_range_ck CHECK (effective_to IS NULL OR effective_to > effective_from),
    CONSTRAINT service_option_rule_code_uq UNIQUE (tenant_id, service_id, option_code)
);

CREATE TABLE catalog.tax_rule (
    tax_rule_id                    uuid NOT NULL DEFAULT core.uuid_v7(),
    tenant_id                      uuid NOT NULL,
    property_id                    uuid,
    tax_code                       text NOT NULL,
    jurisdiction                   text NOT NULL,
    rate                           numeric(9,6) NOT NULL,
    inclusive                      boolean NOT NULL DEFAULT false,
    compound                       boolean NOT NULL DEFAULT false,
    status                         text NOT NULL DEFAULT 'Active',
    effective_from                 timestamptz NOT NULL DEFAULT now(),
    effective_to                   timestamptz,
    source_system                  text NOT NULL DEFAULT 'Spa',
    source_key                     text,
    version                        integer NOT NULL DEFAULT 1,
    created_at                     timestamptz NOT NULL DEFAULT now(),
    created_by                     uuid,
    updated_at                     timestamptz NOT NULL DEFAULT now(),
    updated_by                     uuid,
    correlation_id                 text,
    CONSTRAINT tax_rule_pkey PRIMARY KEY (tax_rule_id),
    CONSTRAINT tax_rule_rate_ck CHECK (rate >= 0 AND rate < 1),
    CONSTRAINT tax_rule_version_ck CHECK (version >= 1),
    CONSTRAINT tax_rule_tenant_identity_uq UNIQUE (tenant_id, tax_rule_id),
    CONSTRAINT tax_rule_status_known CHECK (status IN ('Active', 'Retired')),
    CONSTRAINT tax_rule_effective_range_ck CHECK (effective_to IS NULL OR effective_to > effective_from),
    CONSTRAINT tax_rule_code_uq UNIQUE NULLS NOT DISTINCT (tenant_id, property_id, tax_code, effective_from)
);
COMMENT ON TABLE catalog.tax_rule IS 'Kept typed: money-critical, never a code-list attribute.';

ALTER TABLE catalog.service ADD CONSTRAINT service_tenant_fk FOREIGN KEY (tenant_id) REFERENCES core.tenant (tenant_id);
ALTER TABLE catalog.property_service ADD CONSTRAINT property_service_service_id_fk FOREIGN KEY (tenant_id, service_id) REFERENCES catalog.service (tenant_id, service_id) ON DELETE RESTRICT;
CREATE INDEX property_service_service_id_ix ON catalog.property_service (tenant_id, service_id);
ALTER TABLE catalog.property_service ADD CONSTRAINT property_service_tenant_fk FOREIGN KEY (tenant_id) REFERENCES core.tenant (tenant_id);
ALTER TABLE catalog.property_service ADD CONSTRAINT property_service_property_fk FOREIGN KEY (tenant_id, property_id) REFERENCES core.property (tenant_id, property_id);
ALTER TABLE catalog.service_option_rule ADD CONSTRAINT service_option_rule_service_id_fk FOREIGN KEY (tenant_id, service_id) REFERENCES catalog.service (tenant_id, service_id) ON DELETE RESTRICT;
CREATE INDEX service_option_rule_service_id_ix ON catalog.service_option_rule (tenant_id, service_id);
ALTER TABLE catalog.service_option_rule ADD CONSTRAINT service_option_rule_tenant_fk FOREIGN KEY (tenant_id) REFERENCES core.tenant (tenant_id);
ALTER TABLE catalog.tax_rule ADD CONSTRAINT tax_rule_tenant_fk FOREIGN KEY (tenant_id) REFERENCES core.tenant (tenant_id);
ALTER TABLE catalog.tax_rule ADD CONSTRAINT tax_rule_property_fk FOREIGN KEY (tenant_id, property_id) REFERENCES core.property (tenant_id, property_id);

CREATE TRIGGER service_touch BEFORE UPDATE ON catalog.service FOR EACH ROW EXECUTE FUNCTION core.touch_versioned();
CREATE TRIGGER property_service_touch BEFORE UPDATE ON catalog.property_service FOR EACH ROW EXECUTE FUNCTION core.touch_versioned();
CREATE TRIGGER service_option_rule_touch BEFORE UPDATE ON catalog.service_option_rule FOR EACH ROW EXECUTE FUNCTION core.touch_versioned();
CREATE TRIGGER tax_rule_touch BEFORE UPDATE ON catalog.tax_rule FOR EACH ROW EXECUTE FUNCTION core.touch_versioned();
