-- 03 resources: generated by database/tools/generate.py from database/model/. Do not edit.
-- may reference: catalog, core

CREATE SCHEMA IF NOT EXISTS resources AUTHORIZATION spms_owner;

CREATE TABLE resources.location (
    location_id                    uuid NOT NULL DEFAULT core.uuid_v7(),
    tenant_id                      uuid NOT NULL,
    property_id                    uuid NOT NULL,
    parent_location_id             uuid,
    location_code                  text NOT NULL,
    location_name                  text NOT NULL,
    location_type                  text NOT NULL,
    layout                         jsonb,
    status                         text NOT NULL DEFAULT 'Active',
    effective_from                 timestamptz NOT NULL DEFAULT now(),
    effective_to                   timestamptz,
    source_system                  text NOT NULL DEFAULT 'Spa',
    source_key                     text,
    version                        integer NOT NULL DEFAULT 1,
    created_at                     timestamptz NOT NULL DEFAULT now(),
    created_by                     uuid,
    updated_at                     timestamptz NOT NULL DEFAULT now(),
    updated_by                     uuid,
    correlation_id                 text,
    CONSTRAINT location_pkey PRIMARY KEY (location_id),
    CONSTRAINT location_location_type_ck CHECK (location_type IN ('Facility', 'Floor', 'Treatment', 'Storage', 'Laundry', 'Retail', 'Reception', 'Locker', 'Relaxation')),
    CONSTRAINT location_version_ck CHECK (version >= 1),
    CONSTRAINT location_tenant_identity_uq UNIQUE (tenant_id, location_id),
    CONSTRAINT location_prop_ref_uq UNIQUE (tenant_id, property_id, location_id),
    CONSTRAINT location_status_known CHECK (status IN ('Active', 'Retired')),
    CONSTRAINT location_effective_range_ck CHECK (effective_to IS NULL OR effective_to > effective_from),
    CONSTRAINT location_code_uq UNIQUE (tenant_id, property_id, location_code)
);
COMMENT ON TABLE resources.location IS 'A place at the property, nestable (floor > wing > room store). The optional layout drives the floor plan. [stock grain; rooms; lockers]';
COMMENT ON COLUMN resources.location.layout IS 'floor-plan geometry for the board; presentation only';

CREATE TABLE resources.resource (
    resource_id                    uuid NOT NULL DEFAULT core.uuid_v7(),
    tenant_id                      uuid NOT NULL,
    property_id                    uuid NOT NULL,
    resource_type                  text NOT NULL,
    code                           text NOT NULL,
    name                           text NOT NULL,
    location_id                    uuid,
    capacity                       smallint NOT NULL DEFAULT 1,
    capabilities                   text[] NOT NULL DEFAULT '{}',
    accessible                     boolean NOT NULL DEFAULT false,
    status                         text NOT NULL DEFAULT 'Active',
    effective_from                 timestamptz NOT NULL DEFAULT now(),
    effective_to                   timestamptz,
    source_system                  text NOT NULL DEFAULT 'Spa',
    source_key                     text,
    version                        integer NOT NULL DEFAULT 1,
    created_at                     timestamptz NOT NULL DEFAULT now(),
    created_by                     uuid,
    updated_at                     timestamptz NOT NULL DEFAULT now(),
    updated_by                     uuid,
    correlation_id                 text,
    CONSTRAINT resource_pkey PRIMARY KEY (resource_id),
    CONSTRAINT resource_resource_type_ck CHECK (resource_type IN ('TreatmentRoom', 'WetRoom', 'CoupleRoom', 'Chair')),
    CONSTRAINT resource_capacity_ck CHECK (capacity >= 1),
    CONSTRAINT resource_version_ck CHECK (version >= 1),
    CONSTRAINT resource_tenant_identity_uq UNIQUE (tenant_id, resource_id),
    CONSTRAINT resource_prop_ref_uq UNIQUE (tenant_id, property_id, resource_id),
    CONSTRAINT resource_status_known CHECK (status IN ('Active', 'OutOfService', 'Retired')),
    CONSTRAINT resource_effective_range_ck CHECK (effective_to IS NULL OR effective_to > effective_from),
    CONSTRAINT resource_code_uq UNIQUE (tenant_id, property_id, code)
);
COMMENT ON TABLE resources.resource IS 'A bookable room or chair. CON-002 (no double booking) is enforced on scheduling.appointment. [CON-002; §53.2 rooms/resources]';

CREATE TABLE resources.maintenance_window (
    maintenance_window_id          uuid NOT NULL DEFAULT core.uuid_v7(),
    tenant_id                      uuid NOT NULL,
    property_id                    uuid NOT NULL,
    resource_id                    uuid NOT NULL,
    starts_at                      timestamptz NOT NULL,
    ends_at                        timestamptz NOT NULL,
    reason_code                    text NOT NULL,
    note                           text,
    status                         text NOT NULL DEFAULT 'Planned',
    source_system                  text NOT NULL DEFAULT 'Spa',
    source_key                     text,
    version                        integer NOT NULL DEFAULT 1,
    created_at                     timestamptz NOT NULL DEFAULT now(),
    created_by                     uuid,
    updated_at                     timestamptz NOT NULL DEFAULT now(),
    updated_by                     uuid,
    correlation_id                 text,
    CONSTRAINT maintenance_window_pkey PRIMARY KEY (maintenance_window_id),
    CONSTRAINT maintenance_window_version_ck CHECK (version >= 1),
    CONSTRAINT maintenance_window_tenant_identity_uq UNIQUE (tenant_id, maintenance_window_id),
    CONSTRAINT maintenance_window_status_known CHECK (status IN ('Planned', 'Active', 'Completed', 'Cancelled')),
    CONSTRAINT maintenance_window_range_forward CHECK (ends_at > starts_at)
);

ALTER TABLE resources.location ADD CONSTRAINT location_parent_location_id_fk FOREIGN KEY (tenant_id, property_id, parent_location_id) REFERENCES resources.location (tenant_id, property_id, location_id) ON DELETE RESTRICT;
CREATE INDEX location_parent_location_id_ix ON resources.location (tenant_id, property_id, parent_location_id);
ALTER TABLE resources.location ADD CONSTRAINT location_tenant_fk FOREIGN KEY (tenant_id) REFERENCES core.tenant (tenant_id);
ALTER TABLE resources.location ADD CONSTRAINT location_property_fk FOREIGN KEY (tenant_id, property_id) REFERENCES core.property (tenant_id, property_id);
ALTER TABLE resources.resource ADD CONSTRAINT resource_location_id_fk FOREIGN KEY (tenant_id, property_id, location_id) REFERENCES resources.location (tenant_id, property_id, location_id) ON DELETE RESTRICT;
CREATE INDEX resource_location_id_ix ON resources.resource (tenant_id, property_id, location_id);
ALTER TABLE resources.resource ADD CONSTRAINT resource_tenant_fk FOREIGN KEY (tenant_id) REFERENCES core.tenant (tenant_id);
ALTER TABLE resources.resource ADD CONSTRAINT resource_property_fk FOREIGN KEY (tenant_id, property_id) REFERENCES core.property (tenant_id, property_id);
ALTER TABLE resources.maintenance_window ADD CONSTRAINT maintenance_window_resource_id_fk FOREIGN KEY (tenant_id, property_id, resource_id) REFERENCES resources.resource (tenant_id, property_id, resource_id) ON DELETE RESTRICT;
CREATE INDEX maintenance_window_resource_id_ix ON resources.maintenance_window (tenant_id, property_id, resource_id);
ALTER TABLE resources.maintenance_window ADD CONSTRAINT maintenance_window_tenant_fk FOREIGN KEY (tenant_id) REFERENCES core.tenant (tenant_id);
ALTER TABLE resources.maintenance_window ADD CONSTRAINT maintenance_window_property_fk FOREIGN KEY (tenant_id, property_id) REFERENCES core.property (tenant_id, property_id);

CREATE TRIGGER location_touch BEFORE UPDATE ON resources.location FOR EACH ROW EXECUTE FUNCTION core.touch_versioned();
CREATE TRIGGER resource_touch BEFORE UPDATE ON resources.resource FOR EACH ROW EXECUTE FUNCTION core.touch_versioned();
CREATE TRIGGER maintenance_window_touch BEFORE UPDATE ON resources.maintenance_window FOR EACH ROW EXECUTE FUNCTION core.touch_versioned();
CREATE INDEX resource_capabilities_ix ON resources.resource USING gin (capabilities);

ALTER TABLE resources.maintenance_window ADD CONSTRAINT maintenance_window_no_overlap
    EXCLUDE USING gist (tenant_id WITH =, property_id WITH =, resource_id WITH =,
                        tstzrange(starts_at, ends_at, '[)') WITH &&)
    WHERE (status IN ('Planned', 'Active'));
