-- 09 commerce: generated by database/tools/generate.py from database/model/. Do not edit.
-- may reference: catalog, core, guest, inventory, resources, scheduling, workforce

CREATE SCHEMA IF NOT EXISTS commerce AUTHORIZATION spms_owner;

CREATE TABLE commerce.commerce_order (
    commerce_order_id              uuid NOT NULL DEFAULT core.uuid_v7(),
    tenant_id                      uuid NOT NULL,
    property_id                    uuid NOT NULL,
    order_number                   text,
    receipt_number                 text,
    guest_id                       uuid,
    visit_id                       uuid,
    owner_system                   text NOT NULL DEFAULT 'Spa',
    ordered_at                     timestamptz,
    currency_code                  char(3) NOT NULL,
    subtotal_minor                 bigint NOT NULL DEFAULT 0,
    discount_total_minor           bigint NOT NULL DEFAULT 0,
    tax_total_minor                bigint NOT NULL DEFAULT 0,
    tip_total_minor                bigint NOT NULL DEFAULT 0,
    total_minor                    bigint NOT NULL DEFAULT 0,
    receipt_issued_at              timestamptz,
    expires_at                     timestamptz,
    status                         text NOT NULL DEFAULT 'Draft',
    source_system                  text NOT NULL DEFAULT 'Spa',
    source_key                     text,
    version                        integer NOT NULL DEFAULT 1,
    created_at                     timestamptz NOT NULL DEFAULT now(),
    created_by                     uuid,
    updated_at                     timestamptz NOT NULL DEFAULT now(),
    updated_by                     uuid,
    correlation_id                 text,
    CONSTRAINT commerce_order_pkey PRIMARY KEY (commerce_order_id),
    CONSTRAINT commerce_order_owner_system_ck CHECK (owner_system IN ('Spa', 'Marquee', 'Pos')),
    CONSTRAINT commerce_order_currency_code_ck CHECK (currency_code ~ '^[A-Z]{3}$'),
    CONSTRAINT commerce_order_discount_total_minor_ck CHECK (discount_total_minor >= 0),
    CONSTRAINT commerce_order_tax_total_minor_ck CHECK (tax_total_minor >= 0),
    CONSTRAINT commerce_order_tip_total_minor_ck CHECK (tip_total_minor >= 0),
    CONSTRAINT commerce_order_version_ck CHECK (version >= 1),
    CONSTRAINT commerce_order_tenant_identity_uq UNIQUE (tenant_id, commerce_order_id),
    CONSTRAINT commerce_order_prop_ref_uq UNIQUE (tenant_id, property_id, commerce_order_id),
    CONSTRAINT commerce_order_status_known CHECK (status IN ('Draft', 'Open', 'Delegated', 'PartiallyPaid', 'Paid', 'PartiallyRefunded', 'Refunded', 'Voided', 'Abandoned')),
    CONSTRAINT commerce_order_delegated_is_external CHECK (status <> 'Delegated' OR owner_system <> 'Spa'),
    CONSTRAINT commerce_order_receipt_complete CHECK ((receipt_number IS NULL) = (receipt_issued_at IS NULL))
);
COMMENT ON TABLE commerce.commerce_order IS 'When Marquee owns commerce for the property, owner_system = ''Marquee'' and source_key is its order id. [§53.2 Commerce; DEC-001 (owner_system); DEC-002 (Marquee owns delegated commerce)]';
COMMENT ON COLUMN commerce.commerce_order.expires_at IS 'a Draft (cart) expires';

CREATE TABLE commerce.order_line (
    order_line_id                  uuid NOT NULL DEFAULT core.uuid_v7(),
    tenant_id                      uuid NOT NULL,
    property_id                    uuid NOT NULL,
    commerce_order_id              uuid NOT NULL,
    line_number                    smallint NOT NULL,
    line_kind                      text NOT NULL,
    appointment_id                 uuid,
    service_id                     uuid,
    option_code                    text,
    inventory_item_variant_id      uuid,
    location_id                    uuid,
    staff_id                       uuid,
    original_order_line_id         uuid,
    description                    text NOT NULL,
    quantity                       numeric(18,6) NOT NULL,
    unit_price_minor               bigint NOT NULL,
    discount_minor                 bigint NOT NULL DEFAULT 0,
    tax_minor                      bigint NOT NULL DEFAULT 0,
    tip_minor                      bigint NOT NULL DEFAULT 0,
    net_minor                      bigint NOT NULL,
    tax_code                       text,
    revenue_center_code            text,
    fulfilled_at                   timestamptz,
    created_at                     timestamptz NOT NULL DEFAULT now(),
    created_by                     uuid,
    updated_at                     timestamptz NOT NULL DEFAULT now(),
    updated_by                     uuid,
    correlation_id                 text,
    CONSTRAINT order_line_pkey PRIMARY KEY (order_line_id),
    CONSTRAINT order_line_line_number_ck CHECK (line_number >= 1),
    CONSTRAINT order_line_line_kind_ck CHECK (line_kind IN ('Service', 'Option', 'Retail', 'Fee', 'Deposit', 'Discount', 'Tip')),
    CONSTRAINT order_line_quantity_ck CHECK (quantity <> 0),
    CONSTRAINT order_line_tenant_identity_uq UNIQUE (tenant_id, order_line_id),
    CONSTRAINT order_line_retail_has_variant CHECK (line_kind <> 'Retail' OR inventory_item_variant_id IS NOT NULL),
    CONSTRAINT order_line_service_has_service CHECK (line_kind NOT IN ('Service', 'Option') OR service_id IS NOT NULL),
    CONSTRAINT order_line_number_uq UNIQUE (tenant_id, commerce_order_id, line_number)
);
COMMENT ON COLUMN commerce.order_line.staff_id IS 'provider credited (commission); workforce is not a commerce dependency';
COMMENT ON COLUMN commerce.order_line.original_order_line_id IS 'a return';

CREATE TABLE commerce.payment_intent (
    payment_intent_id              uuid NOT NULL DEFAULT core.uuid_v7(),
    tenant_id                      uuid NOT NULL,
    property_id                    uuid NOT NULL,
    purpose                        text NOT NULL,
    commerce_order_id              uuid,
    appointment_id                 uuid,
    original_transaction_id        uuid,
    amount_minor                   bigint NOT NULL,
    currency_code                  char(3) NOT NULL,
    provider_code                  text NOT NULL,
    provider_reference             text,
    capture_method                 text NOT NULL DEFAULT 'Automatic',
    reason_code                    text,
    approved_by                    uuid,
    approved_at                    timestamptz,
    idempotency_key                text NOT NULL,
    expires_at                     timestamptz,
    status                         text NOT NULL DEFAULT 'Requested',
    version                        integer NOT NULL DEFAULT 1,
    created_at                     timestamptz NOT NULL DEFAULT now(),
    created_by                     uuid,
    updated_at                     timestamptz NOT NULL DEFAULT now(),
    updated_by                     uuid,
    correlation_id                 text,
    CONSTRAINT payment_intent_pkey PRIMARY KEY (payment_intent_id),
    CONSTRAINT payment_intent_purpose_ck CHECK (purpose IN ('Deposit', 'Payment', 'NoShowFee', 'CancellationFee', 'Refund', 'DepositApplied', 'DepositForfeited')),
    CONSTRAINT payment_intent_amount_minor_ck CHECK (amount_minor > 0),
    CONSTRAINT payment_intent_currency_code_ck CHECK (currency_code ~ '^[A-Z]{3}$'),
    CONSTRAINT payment_intent_capture_method_ck CHECK (capture_method IN ('Automatic', 'Manual')),
    CONSTRAINT payment_intent_version_ck CHECK (version >= 1),
    CONSTRAINT payment_intent_tenant_identity_uq UNIQUE (tenant_id, payment_intent_id),
    CONSTRAINT payment_intent_prop_ref_uq UNIQUE (tenant_id, property_id, payment_intent_id),
    CONSTRAINT payment_intent_status_known CHECK (status IN ('Requested', 'Approved', 'RequiresPaymentMethod', 'RequiresAction', 'Authorized', 'Captured', 'Succeeded', 'Cancelled', 'Failed', 'Expired', 'Rejected')),
    CONSTRAINT payment_intent_has_subject CHECK (num_nonnulls(commerce_order_id, appointment_id) >= 1),
    CONSTRAINT payment_intent_refund_names_original CHECK ((purpose = 'Refund') = (original_transaction_id IS NOT NULL)),
    CONSTRAINT payment_intent_refund_approved CHECK (purpose <> 'Refund' OR status IN ('Requested', 'Rejected', 'Cancelled') OR approved_by IS NOT NULL),
    CONSTRAINT payment_intent_dual_control CHECK (approved_by IS NULL OR approved_by IS DISTINCT FROM created_by),
    CONSTRAINT payment_intent_idempotency_uq UNIQUE (tenant_id, idempotency_key)
);
COMMENT ON TABLE commerce.payment_intent IS 'A request to move money, in either direction. Refunds need an approver other than the requester. [§53.2 Commerce (standalone deposit/payment/refund); commerce:refund:approved; SEC-014]';
COMMENT ON COLUMN commerce.payment_intent.original_transaction_id IS 'the transaction a refund returns';
COMMENT ON COLUMN commerce.payment_intent.provider_code IS 'payment adapter, chosen when DEC-010 lands';

CREATE TABLE commerce.payment_transaction (
    payment_transaction_id         uuid NOT NULL DEFAULT core.uuid_v7(),
    tenant_id                      uuid NOT NULL,
    property_id                    uuid NOT NULL,
    payment_intent_id              uuid,
    commerce_order_id              uuid,
    tender_code                    text NOT NULL,
    transaction_type               text NOT NULL,
    outcome                        text NOT NULL,
    amount_minor                   bigint NOT NULL,
    currency_code                  char(3) NOT NULL,
    provider_code                  text NOT NULL,
    provider_reference             text,
    external_folio_reference       text,
    card_brand                     text,
    card_last4                     char(4),
    processed_at                   timestamptz NOT NULL,
    original_transaction_id        uuid,
    idempotency_key                text NOT NULL,
    created_at                     timestamptz NOT NULL DEFAULT now(),
    created_by                     uuid,
    correlation_id                 text,
    CONSTRAINT payment_transaction_pkey PRIMARY KEY (payment_transaction_id),
    CONSTRAINT payment_transaction_transaction_type_ck CHECK (transaction_type IN ('Authorization', 'Capture', 'Sale', 'Void', 'Refund', 'Chargeback', 'Adjustment', 'FolioPost')),
    CONSTRAINT payment_transaction_outcome_ck CHECK (outcome IN ('Approved', 'Declined', 'Error', 'Pending', 'Unknown')),
    CONSTRAINT payment_transaction_amount_minor_ck CHECK (amount_minor >= 0),
    CONSTRAINT payment_transaction_currency_code_ck CHECK (currency_code ~ '^[A-Z]{3}$'),
    CONSTRAINT payment_transaction_card_last4_ck CHECK (card_last4 ~ '^[0-9]{4}$'),
    CONSTRAINT payment_transaction_tenant_identity_uq UNIQUE (tenant_id, payment_transaction_id),
    CONSTRAINT payment_transaction_reversal_has_original CHECK (transaction_type NOT IN ('Void', 'Refund', 'Chargeback') OR original_transaction_id IS NOT NULL),
    CONSTRAINT payment_transaction_folio_has_reference CHECK (transaction_type <> 'FolioPost' OR external_folio_reference IS NOT NULL),
    CONSTRAINT payment_transaction_idempotency_uq UNIQUE (tenant_id, idempotency_key)
);
COMMENT ON TABLE commerce.payment_transaction IS 'What the payment provider, PMS folio or cash drawer actually did. Append-only. [PAYMENT_OUTCOME_AMBIGUOUS -> outcome ''Unknown'' pending reconciliation]';
COMMENT ON COLUMN commerce.payment_transaction.tender_code IS 'code_list Tender (Card, Cash, RoomCharge, GiftCard, MemberAccount)';
COMMENT ON COLUMN commerce.payment_transaction.external_folio_reference IS 'PMS folio for a room charge';

CREATE TABLE commerce.commerce_reference (
    reference_id                   uuid NOT NULL DEFAULT core.uuid_v7(),
    tenant_id                      uuid NOT NULL,
    property_id                    uuid NOT NULL,
    appointment_id                 uuid,
    commerce_order_id              uuid,
    capability_code                text NOT NULL,
    owner_system                   text NOT NULL,
    operation                      text NOT NULL,
    external_id                    text,
    amount_minor                   bigint,
    currency_code                  char(3),
    idempotency_key                text NOT NULL,
    last_error                     text,
    status                         text NOT NULL DEFAULT 'Pending',
    version                        integer NOT NULL DEFAULT 1,
    created_at                     timestamptz NOT NULL DEFAULT now(),
    created_by                     uuid,
    updated_at                     timestamptz NOT NULL DEFAULT now(),
    updated_by                     uuid,
    correlation_id                 text,
    CONSTRAINT commerce_reference_pkey PRIMARY KEY (reference_id),
    CONSTRAINT commerce_reference_owner_system_ck CHECK (owner_system IN ('Marquee', 'Pos', 'Pms', 'External')),
    CONSTRAINT commerce_reference_operation_ck CHECK (operation IN ('CreateCart', 'AddLine', 'Checkout', 'Refund', 'Void', 'PostCharge')),
    CONSTRAINT commerce_reference_currency_code_ck CHECK (currency_code ~ '^[A-Z]{3}$'),
    CONSTRAINT commerce_reference_version_ck CHECK (version >= 1),
    CONSTRAINT commerce_reference_tenant_identity_uq UNIQUE (tenant_id, reference_id),
    CONSTRAINT commerce_reference_status_known CHECK (status IN ('Pending', 'Sent', 'Confirmed', 'Failed', 'Ambiguous')),
    CONSTRAINT commerce_reference_idempotency_uq UNIQUE (tenant_id, idempotency_key)
);
COMMENT ON TABLE commerce.commerce_reference IS 'An outbound call to the system that owns commerce, and what came back. [MCI Marquee commerce delegation; OWNERSHIP_AMBIGUOUS]';

ALTER TABLE commerce.commerce_order ADD CONSTRAINT commerce_order_guest_id_fk FOREIGN KEY (tenant_id, guest_id) REFERENCES guest.guest (tenant_id, guest_id) ON DELETE RESTRICT;
CREATE INDEX commerce_order_guest_id_ix ON commerce.commerce_order (tenant_id, guest_id);
ALTER TABLE commerce.commerce_order ADD CONSTRAINT commerce_order_visit_id_fk FOREIGN KEY (tenant_id, property_id, visit_id) REFERENCES scheduling.visit (tenant_id, property_id, visit_id) ON DELETE RESTRICT;
CREATE INDEX commerce_order_visit_id_ix ON commerce.commerce_order (tenant_id, property_id, visit_id);
ALTER TABLE commerce.commerce_order ADD CONSTRAINT commerce_order_tenant_fk FOREIGN KEY (tenant_id) REFERENCES core.tenant (tenant_id);
ALTER TABLE commerce.commerce_order ADD CONSTRAINT commerce_order_property_fk FOREIGN KEY (tenant_id, property_id) REFERENCES core.property (tenant_id, property_id);
ALTER TABLE commerce.order_line ADD CONSTRAINT order_line_commerce_order_id_fk FOREIGN KEY (tenant_id, property_id, commerce_order_id) REFERENCES commerce.commerce_order (tenant_id, property_id, commerce_order_id) ON DELETE RESTRICT;
CREATE INDEX order_line_commerce_order_id_ix ON commerce.order_line (tenant_id, property_id, commerce_order_id);
ALTER TABLE commerce.order_line ADD CONSTRAINT order_line_appointment_id_fk FOREIGN KEY (tenant_id, property_id, appointment_id) REFERENCES scheduling.appointment (tenant_id, property_id, appointment_id) ON DELETE RESTRICT;
CREATE INDEX order_line_appointment_id_ix ON commerce.order_line (tenant_id, property_id, appointment_id);
ALTER TABLE commerce.order_line ADD CONSTRAINT order_line_service_id_fk FOREIGN KEY (tenant_id, service_id) REFERENCES catalog.service (tenant_id, service_id) ON DELETE RESTRICT;
CREATE INDEX order_line_service_id_ix ON commerce.order_line (tenant_id, service_id);
ALTER TABLE commerce.order_line ADD CONSTRAINT order_line_inventory_item_variant_id_fk FOREIGN KEY (tenant_id, inventory_item_variant_id) REFERENCES inventory.inventory_item_variant (tenant_id, inventory_item_variant_id) ON DELETE RESTRICT;
CREATE INDEX order_line_inventory_item_variant_id_ix ON commerce.order_line (tenant_id, inventory_item_variant_id);
ALTER TABLE commerce.order_line ADD CONSTRAINT order_line_location_id_fk FOREIGN KEY (tenant_id, property_id, location_id) REFERENCES resources.location (tenant_id, property_id, location_id) ON DELETE RESTRICT;
CREATE INDEX order_line_location_id_ix ON commerce.order_line (tenant_id, property_id, location_id);
ALTER TABLE commerce.order_line ADD CONSTRAINT order_line_original_order_line_id_fk FOREIGN KEY (tenant_id, original_order_line_id) REFERENCES commerce.order_line (tenant_id, order_line_id) ON DELETE RESTRICT;
CREATE INDEX order_line_original_order_line_id_ix ON commerce.order_line (tenant_id, original_order_line_id);
ALTER TABLE commerce.order_line ADD CONSTRAINT order_line_tenant_fk FOREIGN KEY (tenant_id) REFERENCES core.tenant (tenant_id);
ALTER TABLE commerce.order_line ADD CONSTRAINT order_line_property_fk FOREIGN KEY (tenant_id, property_id) REFERENCES core.property (tenant_id, property_id);
ALTER TABLE commerce.payment_intent ADD CONSTRAINT payment_intent_commerce_order_id_fk FOREIGN KEY (tenant_id, property_id, commerce_order_id) REFERENCES commerce.commerce_order (tenant_id, property_id, commerce_order_id) ON DELETE RESTRICT;
CREATE INDEX payment_intent_commerce_order_id_ix ON commerce.payment_intent (tenant_id, property_id, commerce_order_id);
ALTER TABLE commerce.payment_intent ADD CONSTRAINT payment_intent_appointment_id_fk FOREIGN KEY (tenant_id, property_id, appointment_id) REFERENCES scheduling.appointment (tenant_id, property_id, appointment_id) ON DELETE RESTRICT;
CREATE INDEX payment_intent_appointment_id_ix ON commerce.payment_intent (tenant_id, property_id, appointment_id);
ALTER TABLE commerce.payment_intent ADD CONSTRAINT payment_intent_original_transaction_id_fk FOREIGN KEY (tenant_id, original_transaction_id) REFERENCES commerce.payment_transaction (tenant_id, payment_transaction_id) ON DELETE RESTRICT;
CREATE INDEX payment_intent_original_transaction_id_ix ON commerce.payment_intent (tenant_id, original_transaction_id);
ALTER TABLE commerce.payment_intent ADD CONSTRAINT payment_intent_tenant_fk FOREIGN KEY (tenant_id) REFERENCES core.tenant (tenant_id);
ALTER TABLE commerce.payment_intent ADD CONSTRAINT payment_intent_property_fk FOREIGN KEY (tenant_id, property_id) REFERENCES core.property (tenant_id, property_id);
ALTER TABLE commerce.payment_transaction ADD CONSTRAINT payment_transaction_payment_intent_id_fk FOREIGN KEY (tenant_id, property_id, payment_intent_id) REFERENCES commerce.payment_intent (tenant_id, property_id, payment_intent_id) ON DELETE RESTRICT;
CREATE INDEX payment_transaction_payment_intent_id_ix ON commerce.payment_transaction (tenant_id, property_id, payment_intent_id);
ALTER TABLE commerce.payment_transaction ADD CONSTRAINT payment_transaction_commerce_order_id_fk FOREIGN KEY (tenant_id, property_id, commerce_order_id) REFERENCES commerce.commerce_order (tenant_id, property_id, commerce_order_id) ON DELETE RESTRICT;
CREATE INDEX payment_transaction_commerce_order_id_ix ON commerce.payment_transaction (tenant_id, property_id, commerce_order_id);
ALTER TABLE commerce.payment_transaction ADD CONSTRAINT payment_transaction_original_transaction_id_fk FOREIGN KEY (tenant_id, original_transaction_id) REFERENCES commerce.payment_transaction (tenant_id, payment_transaction_id) ON DELETE RESTRICT;
CREATE INDEX payment_transaction_original_transaction_id_ix ON commerce.payment_transaction (tenant_id, original_transaction_id);
ALTER TABLE commerce.payment_transaction ADD CONSTRAINT payment_transaction_tenant_fk FOREIGN KEY (tenant_id) REFERENCES core.tenant (tenant_id);
ALTER TABLE commerce.payment_transaction ADD CONSTRAINT payment_transaction_property_fk FOREIGN KEY (tenant_id, property_id) REFERENCES core.property (tenant_id, property_id);
ALTER TABLE commerce.commerce_reference ADD CONSTRAINT commerce_reference_appointment_id_fk FOREIGN KEY (tenant_id, property_id, appointment_id) REFERENCES scheduling.appointment (tenant_id, property_id, appointment_id) ON DELETE RESTRICT;
CREATE INDEX commerce_reference_appointment_id_ix ON commerce.commerce_reference (tenant_id, property_id, appointment_id);
ALTER TABLE commerce.commerce_reference ADD CONSTRAINT commerce_reference_commerce_order_id_fk FOREIGN KEY (tenant_id, property_id, commerce_order_id) REFERENCES commerce.commerce_order (tenant_id, property_id, commerce_order_id) ON DELETE RESTRICT;
CREATE INDEX commerce_reference_commerce_order_id_ix ON commerce.commerce_reference (tenant_id, property_id, commerce_order_id);
ALTER TABLE commerce.commerce_reference ADD CONSTRAINT commerce_reference_tenant_fk FOREIGN KEY (tenant_id) REFERENCES core.tenant (tenant_id);
ALTER TABLE commerce.commerce_reference ADD CONSTRAINT commerce_reference_property_fk FOREIGN KEY (tenant_id, property_id) REFERENCES core.property (tenant_id, property_id);

CREATE TRIGGER commerce_order_touch BEFORE UPDATE ON commerce.commerce_order FOR EACH ROW EXECUTE FUNCTION core.touch_versioned();
CREATE TRIGGER order_line_touch BEFORE UPDATE ON commerce.order_line FOR EACH ROW EXECUTE FUNCTION core.touch();
CREATE TRIGGER payment_intent_touch BEFORE UPDATE ON commerce.payment_intent FOR EACH ROW EXECUTE FUNCTION core.touch_versioned();
CREATE TRIGGER payment_transaction_append_only BEFORE UPDATE OR DELETE ON commerce.payment_transaction FOR EACH ROW EXECUTE FUNCTION core.forbid_mutation();
CREATE TRIGGER commerce_reference_touch BEFORE UPDATE ON commerce.commerce_reference FOR EACH ROW EXECUTE FUNCTION core.touch_versioned();
CREATE UNIQUE INDEX commerce_order_number_uq ON commerce.commerce_order (tenant_id, property_id, order_number) WHERE order_number IS NOT NULL;
CREATE UNIQUE INDEX commerce_order_receipt_uq ON commerce.commerce_order (tenant_id, property_id, receipt_number) WHERE receipt_number IS NOT NULL;

-- Lines of a Draft order (a cart) may be removed; once the order is placed its lines are evidence.
CREATE FUNCTION commerce.order_line_delete_only_draft() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM commerce.commerce_order o
                    WHERE o.tenant_id = OLD.tenant_id AND o.commerce_order_id = OLD.commerce_order_id
                      AND o.status = 'Draft') THEN
        RAISE EXCEPTION 'order_line can be deleted only while its order is Draft' USING ERRCODE = '42501';
    END IF;
    RETURN OLD;
END $$;
CREATE TRIGGER order_line_delete_only_draft BEFORE DELETE ON commerce.order_line
    FOR EACH ROW EXECUTE FUNCTION commerce.order_line_delete_only_draft();
CREATE UNIQUE INDEX payment_intent_provider_uq ON commerce.payment_intent (tenant_id, provider_code, provider_reference) WHERE provider_reference IS NOT NULL;
CREATE INDEX payment_intent_appointment_ix ON commerce.payment_intent (tenant_id, appointment_id, purpose);
