-- 10 messaging: generated by database/tools/generate.py from database/model/. Do not edit.
-- may reference: catalog, core, guest, resources, scheduling, workforce

CREATE SCHEMA IF NOT EXISTS messaging AUTHORIZATION spms_owner;

CREATE TABLE messaging.message_template (
    message_template_id            uuid NOT NULL DEFAULT core.uuid_v7(),
    tenant_id                      uuid NOT NULL,
    property_id                    uuid,
    template_code                  text NOT NULL,
    version_number                 integer NOT NULL,
    channel                        text NOT NULL,
    locale                         text NOT NULL,
    purpose                        text NOT NULL,
    subject                        text,
    body_template                  text NOT NULL,
    variables                      text[] NOT NULL DEFAULT '{}',
    provider_template_reference    text,
    trigger_event                  text,
    offset_minutes                 integer,
    service_id                     uuid,
    respect_quiet_hours            boolean NOT NULL DEFAULT true,
    approved_by                    uuid,
    approved_at                    timestamptz,
    status                         text NOT NULL DEFAULT 'Draft',
    effective_from                 timestamptz NOT NULL DEFAULT now(),
    effective_to                   timestamptz,
    source_system                  text NOT NULL DEFAULT 'Spa',
    source_key                     text,
    version                        integer NOT NULL DEFAULT 1,
    created_at                     timestamptz NOT NULL DEFAULT now(),
    created_by                     uuid,
    updated_at                     timestamptz NOT NULL DEFAULT now(),
    updated_by                     uuid,
    correlation_id                 text,
    CONSTRAINT message_template_pkey PRIMARY KEY (message_template_id),
    CONSTRAINT message_template_version_number_ck CHECK (version_number >= 1),
    CONSTRAINT message_template_channel_ck CHECK (channel IN ('Email', 'Sms', 'WhatsApp', 'Push')),
    CONSTRAINT message_template_purpose_ck CHECK (purpose IN ('Confirmation', 'Reminder', 'Cancellation', 'IntakeRequest', 'Receipt', 'Waitlist', 'Marketing', 'Transactional')),
    CONSTRAINT message_template_trigger_event_ck CHECK (trigger_event IN ('AppointmentConfirmed', 'BeforeStart', 'AfterCompletion', 'IntakeDue', 'WaitlistOffer')),
    CONSTRAINT message_template_version_ck CHECK (version >= 1),
    CONSTRAINT message_template_tenant_identity_uq UNIQUE (tenant_id, message_template_id),
    CONSTRAINT message_template_status_known CHECK (status IN ('Draft', 'Approved', 'Active', 'Retired')),
    CONSTRAINT message_template_effective_range_ck CHECK (effective_to IS NULL OR effective_to > effective_from),
    CONSTRAINT message_template_active_is_approved CHECK (status NOT IN ('Approved', 'Active') OR approved_by IS NOT NULL),
    CONSTRAINT message_template_trigger_pair CHECK ((trigger_event IS NULL) = (offset_minutes IS NULL)),
    CONSTRAINT message_template_version_uq UNIQUE NULLS NOT DISTINCT (tenant_id, property_id, template_code, channel, locale, version_number)
);
COMMENT ON TABLE messaging.message_template IS 'One row per approved version of a template in a channel and locale. Reminder timing is part of the template: trigger_event + offset_minutes. [§53.2 Guest messaging: reminders, quiet hours, consent; DEC-008]';
COMMENT ON COLUMN messaging.message_template.provider_template_reference IS 'WhatsApp/SMS provider-approved template id';
COMMENT ON COLUMN messaging.message_template.offset_minutes IS 'negative = before the event';
COMMENT ON COLUMN messaging.message_template.service_id IS 'NULL = every service';

CREATE TABLE messaging.scheduled_message (
    scheduled_message_id           uuid NOT NULL DEFAULT core.uuid_v7(),
    tenant_id                      uuid NOT NULL,
    property_id                    uuid NOT NULL,
    guest_id                       uuid NOT NULL,
    appointment_id                 uuid,
    message_template_id            uuid NOT NULL,
    consent_record_id              uuid,
    channel                        text NOT NULL,
    recipient_address_cipher       bytea NOT NULL,
    key_version                    text NOT NULL,
    send_after                     timestamptz NOT NULL,
    expires_at                     timestamptz,
    provider_code                  text,
    provider_message_id            text,
    attempt_count                  smallint NOT NULL DEFAULT 0,
    sent_at                        timestamptz,
    delivered_at                   timestamptz,
    failure_code                   text,
    idempotency_key                text NOT NULL,
    status                         text NOT NULL DEFAULT 'Scheduled',
    version                        integer NOT NULL DEFAULT 1,
    created_at                     timestamptz NOT NULL DEFAULT now(),
    created_by                     uuid,
    updated_at                     timestamptz NOT NULL DEFAULT now(),
    updated_by                     uuid,
    correlation_id                 text,
    CONSTRAINT scheduled_message_pkey PRIMARY KEY (scheduled_message_id),
    CONSTRAINT scheduled_message_channel_ck CHECK (channel IN ('Email', 'Sms', 'WhatsApp', 'Push')),
    CONSTRAINT scheduled_message_attempt_count_ck CHECK (attempt_count >= 0),
    CONSTRAINT scheduled_message_version_ck CHECK (version >= 1),
    CONSTRAINT scheduled_message_tenant_identity_uq UNIQUE (tenant_id, scheduled_message_id),
    CONSTRAINT scheduled_message_status_known CHECK (status IN ('Scheduled', 'Sending', 'Sent', 'Delivered', 'Failed', 'Bounced', 'Cancelled', 'Expired', 'Suppressed')),
    CONSTRAINT scheduled_message_sent_complete CHECK (status NOT IN ('Sent', 'Delivered') OR sent_at IS NOT NULL),
    CONSTRAINT scheduled_message_delivered_complete CHECK ((status = 'Delivered') = (delivered_at IS NOT NULL)),
    CONSTRAINT scheduled_message_idempotency_uq UNIQUE (tenant_id, idempotency_key)
);
COMMENT ON TABLE messaging.scheduled_message IS 'A message to one guest, from scheduling to delivery.';
COMMENT ON COLUMN messaging.scheduled_message.consent_record_id IS 'required for Marketing purpose';

ALTER TABLE messaging.message_template ADD CONSTRAINT message_template_service_id_fk FOREIGN KEY (tenant_id, service_id) REFERENCES catalog.service (tenant_id, service_id) ON DELETE RESTRICT;
CREATE INDEX message_template_service_id_ix ON messaging.message_template (tenant_id, service_id);
ALTER TABLE messaging.message_template ADD CONSTRAINT message_template_tenant_fk FOREIGN KEY (tenant_id) REFERENCES core.tenant (tenant_id);
ALTER TABLE messaging.message_template ADD CONSTRAINT message_template_property_fk FOREIGN KEY (tenant_id, property_id) REFERENCES core.property (tenant_id, property_id);
ALTER TABLE messaging.scheduled_message ADD CONSTRAINT scheduled_message_guest_id_fk FOREIGN KEY (tenant_id, guest_id) REFERENCES guest.guest (tenant_id, guest_id) ON DELETE RESTRICT;
CREATE INDEX scheduled_message_guest_id_ix ON messaging.scheduled_message (tenant_id, guest_id);
ALTER TABLE messaging.scheduled_message ADD CONSTRAINT scheduled_message_appointment_id_fk FOREIGN KEY (tenant_id, property_id, appointment_id) REFERENCES scheduling.appointment (tenant_id, property_id, appointment_id) ON DELETE RESTRICT;
CREATE INDEX scheduled_message_appointment_id_ix ON messaging.scheduled_message (tenant_id, property_id, appointment_id);
ALTER TABLE messaging.scheduled_message ADD CONSTRAINT scheduled_message_message_template_id_fk FOREIGN KEY (tenant_id, message_template_id) REFERENCES messaging.message_template (tenant_id, message_template_id) ON DELETE RESTRICT;
CREATE INDEX scheduled_message_message_template_id_ix ON messaging.scheduled_message (tenant_id, message_template_id);
ALTER TABLE messaging.scheduled_message ADD CONSTRAINT scheduled_message_consent_record_id_fk FOREIGN KEY (tenant_id, consent_record_id) REFERENCES guest.consent_record (tenant_id, consent_id) ON DELETE RESTRICT;
CREATE INDEX scheduled_message_consent_record_id_ix ON messaging.scheduled_message (tenant_id, consent_record_id);
ALTER TABLE messaging.scheduled_message ADD CONSTRAINT scheduled_message_tenant_fk FOREIGN KEY (tenant_id) REFERENCES core.tenant (tenant_id);
ALTER TABLE messaging.scheduled_message ADD CONSTRAINT scheduled_message_property_fk FOREIGN KEY (tenant_id, property_id) REFERENCES core.property (tenant_id, property_id);

CREATE TRIGGER message_template_touch BEFORE UPDATE ON messaging.message_template FOR EACH ROW EXECUTE FUNCTION core.touch_versioned();
CREATE TRIGGER scheduled_message_touch BEFORE UPDATE ON messaging.scheduled_message FOR EACH ROW EXECUTE FUNCTION core.touch_versioned();
CREATE INDEX scheduled_message_due_ix ON messaging.scheduled_message (send_after) WHERE status = 'Scheduled';
CREATE UNIQUE INDEX scheduled_message_provider_uq ON messaging.scheduled_message (provider_code, provider_message_id) WHERE provider_message_id IS NOT NULL;
