#!/usr/bin/env python3
"""
Generates the EF Core persistence layer from database/model/ - the same source
generate.py turns into the reviewed SQL.

    python3 database/tools/generate_ef.py          # write files
    python3 database/tools/generate_ef.py --check  # fail if generated files are stale

For every module it writes, under backend/src/Modules/Spms.Modules.<Module>/Data/Generated/:

  Entities.g.cs   one row class per table, one property per column
  Model.g.cs      an IModelContributor that maps them (table, column, store type,
                  nullability, keys, defaults, generated columns, concurrency)
  Statuses.g.cs   the status vocabulary of each table, as constants

The EF model is therefore derived from the schema rather than written beside it.
It cannot silently disagree with the SQL, and the database drift test
(Spms.Tests/Postgres/DriftTests) compares the two again against a live database.
Constraints, indexes, RLS and triggers stay in SQL: EF never owns them.
"""
from __future__ import annotations
import pathlib, re, sys

HERE = pathlib.Path(__file__).resolve().parent
ROOT = HERE.parent
REPO = ROOT.parent
sys.path.insert(0, str(HERE))
import generate  # noqa: E402
import dsl  # noqa: E402
from dsl import MASTER, AGGREGATE, CHILD, LEDGER, GLOBAL, TENANT, TENANT_OPT, PROPERTY  # noqa: E402

VERSIONED = (MASTER, AGGREGATE)

# Columns the database maintains itself (triggers). EF reads them back and never writes them.
DB_MAINTAINED = {
    "scheduling.appointment.end_at",
}


def pascal(name: str) -> str:
    return "".join(p[:1].upper() + p[1:] for p in name.split("_"))


def module_name(schema: str) -> str:
    return pascal(schema)


def clr_type(c) -> tuple[str, str]:
    """(C# type without nullability marker, store type for HasColumnType)."""
    t = c.type
    base = t.split(" GENERATED")[0].strip()
    if base == "uuid":
        return "Guid", "uuid"
    if base == "uuid[]":
        return "Guid[]", "uuid[]"
    if base in ("text",):
        return "string", "text"
    if base == "text[]":
        return "string[]", "text[]"
    if re.fullmatch(r"char\(\d+\)", base):
        return "string", "character(" + base[5:-1] + ")"
    if base == "integer":
        return "int", "integer"
    if base == "bigint":
        return "long", "bigint"
    if base == "smallint":
        return "short", "smallint"
    if base == "boolean":
        return "bool", "boolean"
    if base == "timestamptz":
        return "DateTimeOffset", "timestamp with time zone"
    if base == "date":
        return "DateOnly", "date"
    if base == "jsonb":
        return "string", "jsonb"
    if base == "bytea":
        return "byte[]", "bytea"
    if base == "tstzrange":
        return "NpgsqlRange<DateTime>", "tstzrange"
    m = re.fullmatch(r"numeric\((\d+),(\d+)\)", base)
    if m:
        return "decimal", f"numeric({m.group(1)},{m.group(2)})"
    raise SystemExit(f"unmapped column type {t!r} on {c.name}")


def literal(c, clr: str):
    """C# initializer for a literal SQL default, or None when the default is a SQL expression."""
    d = c.default
    if d is None:
        return None
    if clr == "bool" and d in ("true", "false"):
        return d
    if clr in ("int", "long", "short") and re.fullmatch(r"-?\d+", d):
        return d
    if clr == "decimal" and re.fullmatch(r"-?\d+(\.\d+)?", d):
        return d + "m"
    if clr == "string" and d.startswith("'") and d.endswith("'"):
        return '"' + d[1:-1].replace("''", "'").replace("\\", "\\\\").replace('"', '\\"') + '"'
    if clr in ("string[]", "Guid[]") and d == "'{}'":
        return "[]"
    return None


def cs_string(s: str) -> str:
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def entity_class(t) -> str:
    return pascal(t.name) + "Row"


def interfaces(t) -> list[str]:
    out = []
    if t.fq == "core.tenant":
        pass
    elif t.scope == TENANT:
        out.append("ITenantOwned")
    elif t.scope == TENANT_OPT:
        out.append("IOptionalPropertyOwned")
    elif t.scope == PROPERTY:
        out.append("IPropertyOwned")
    if t.kind in VERSIONED:
        out.append("IVersioned")
    if t.kind == LEDGER:
        out.append("IAppendOnly")
    names = {c.name for c in generate.all_columns(t)}
    if "created_by" in names:
        out.append("ICreatedBy")
    if "updated_by" in names:
        out.append("IUpdatedBy")
    if "correlation_id" in names:
        out.append("ICorrelated")
    return out


def gen_entities(module: str, tables) -> str:
    lines = [
        "// <auto-generated> by database/tools/generate_ef.py from database/model/. Do not edit.",
        "#nullable enable",
        "using NpgsqlTypes;",
        "using Spms.Persistence;",
        "",
        f"namespace Spms.Modules.{module_name(module)}.Data;",
        "",
    ]
    for t in tables:
        doc = (t.doc or t.name).replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
        lines.append(f"/// <summary>{t.fq}. {doc}</summary>")
        ifs = interfaces(t)
        lines.append(f"public sealed partial class {entity_class(t)}" + (" : " + ", ".join(ifs) if ifs else ""))
        lines.append("{")
        for c in generate.all_columns(t):
            clr, _ = clr_type(c)
            nullable = c.null
            prop = pascal(c.name)
            init = literal(c, clr)
            typ = clr + ("?" if nullable else "")
            if init is not None and not nullable:
                lines.append(f"    public {typ} {prop} {{ get; set; }} = {init};")
            elif init is not None and nullable:
                lines.append(f"    public {typ} {prop} {{ get; set; }} = {init};")
            elif not nullable and clr in ("string",):
                lines.append(f"    public {typ} {prop} {{ get; set; }} = string.Empty;")
            elif not nullable and clr in ("string[]", "Guid[]", "byte[]"):
                lines.append(f"    public {typ} {prop} {{ get; set; }} = [];")
            else:
                lines.append(f"    public {typ} {prop} {{ get; set; }}")
        lines.append("}")
        lines.append("")
    return "\n".join(lines)


def gen_model(module: str, tables) -> str:
    mod = module_name(module)
    lines = [
        "// <auto-generated> by database/tools/generate_ef.py from database/model/. Do not edit.",
        "#nullable enable",
        "using Microsoft.EntityFrameworkCore;",
        "using Microsoft.EntityFrameworkCore.Metadata;",
        "using Spms.Persistence;",
        "",
        f"namespace Spms.Modules.{mod}.Data;",
        "",
        f"/// <summary>Maps the {module} schema. Generated from the same model as database/schema/.</summary>",
        f"public sealed class {mod}ModelContributor : IModelContributor",
        "{",
        f"    public string Schema => {cs_string(module)};",
        "",
        "    public void Configure(ModelBuilder b)",
        "    {",
    ]
    for t in tables:
        cls = entity_class(t)
        lines.append(f"        b.Entity<{cls}>(e =>")
        lines.append("        {")
        lines.append(f"            e.ToTable({cs_string(t.name)}, {cs_string(t.schema)});")
        pk = [t.pk_col] + ([t.partition_by] if t.partition_by else [])
        if len(pk) == 1:
            lines.append(f"            e.HasKey(x => x.{pascal(pk[0])});")
        else:
            lines.append("            e.HasKey(x => new { " + ", ".join(f"x.{pascal(k)}" for k in pk) + " });")
        for c in generate.all_columns(t):
            clr, store = clr_type(c)
            prop = pascal(c.name)
            chain = [f"e.Property(x => x.{prop})", f".HasColumnName({cs_string(c.name)})", f".HasColumnType({cs_string(store)})"]
            if not c.null:
                chain.append(".IsRequired()")
            fq_col = f"{t.fq}.{c.name}"
            if " GENERATED ALWAYS AS " in c.type:
                expr = c.type.split(" GENERATED ALWAYS AS ", 1)[1]
                expr = expr[: expr.rfind(" STORED")].strip()
                if expr.startswith("(") and expr.endswith(")"):
                    expr = expr[1:-1]
                chain.append(f".HasComputedColumnSql({cs_string(expr)}, stored: true)")
            elif fq_col in DB_MAINTAINED:
                chain.append(".ValueGeneratedOnAddOrUpdate()")
            elif c.name == t.pk_col and c.default == "core.uuid_v7()":
                chain.append(".ValueGeneratedNever()")
            elif c.name == "updated_at" and c.default == "now()":
                chain.append(".HasDefaultValueSql(\"now()\").ValueGeneratedOnAddOrUpdate()")
            elif c.default is not None and literal(c, clr) is None:
                chain.append(f".HasDefaultValueSql({cs_string(c.default)})")
            if c.name == "version" and t.kind in VERSIONED:
                chain.append(".IsConcurrencyToken()")
            lines.append("            " + "".join(chain) + ";")
            if fq_col in DB_MAINTAINED or c.name == "updated_at":
                lines.append(f"            e.Property(x => x.{prop}).Metadata.SetBeforeSaveBehavior(PropertySaveBehavior.Ignore);")
                lines.append(f"            e.Property(x => x.{prop}).Metadata.SetAfterSaveBehavior(PropertySaveBehavior.Ignore);")
            if c.name in ("created_at", "created_by") and t.kind != LEDGER:
                lines.append(f"            e.Property(x => x.{prop}).Metadata.SetAfterSaveBehavior(PropertySaveBehavior.Ignore);")
        lines.append("        });")
        lines.append("")
    lines += ["    }", "}", ""]
    return "\n".join(lines)


def gen_statuses(module: str, tables) -> str:
    mod = module_name(module)
    lines = [
        "// <auto-generated> by database/tools/generate_ef.py from database/model/. Do not edit.",
        f"namespace Spms.Modules.{mod}.Data;",
        "",
    ]
    for t in tables:
        if not t.statuses:
            continue
        lines.append(f"/// <summary>status values of {t.fq} (the same PascalCase values as the API contract).</summary>")
        lines.append(f"public static class {pascal(t.name)}Statuses")
        lines.append("{")
        for s in t.statuses:
            lines.append(f"    public const string {s} = {cs_string(s)};")
        lines.append("    public static readonly IReadOnlyList<string> All = [" + ", ".join(t.statuses) + "];")
        lines.append("}")
        lines.append("")
    return "\n".join(lines)


def main(check: bool):
    tables = generate.load_models()
    generate.validate(tables)
    files: dict[pathlib.Path, str] = {}
    for module in dsl.MODULE_ORDER:
        mts = [t for t in tables if t.schema == module]
        base = REPO / "backend" / "src" / "Modules" / f"Spms.Modules.{module_name(module)}" / "Data" / "Generated"
        files[base / "Entities.g.cs"] = gen_entities(module, mts)
        files[base / "Model.g.cs"] = gen_model(module, mts)
        files[base / "Statuses.g.cs"] = gen_statuses(module, mts)

    stale = []
    for path, text in files.items():
        if check:
            if not path.exists() or path.read_text() != text:
                stale.append(str(path.relative_to(REPO)))
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(text)
    if check and stale:
        raise SystemExit("generated EF files are stale: " + ", ".join(stale))
    print(f"{len(tables)} tables -> EF model" + (" - up to date" if check else f" - wrote {len(files)} files"))


if __name__ == "__main__":
    main("--check" in sys.argv)
