-- 04 workforce: generated by database/tools/generate.py from database/model/. Do not edit.
-- may reference: catalog, core

CREATE SCHEMA IF NOT EXISTS workforce AUTHORIZATION spms_owner;

CREATE TABLE workforce.staff (
    staff_id                       uuid NOT NULL DEFAULT core.uuid_v7(),
    tenant_id                      uuid NOT NULL,
    principal_id                   uuid,
    home_property_id               uuid,
    department_id                  uuid,
    preferred_name                 text NOT NULL,
    employment_status              text NOT NULL DEFAULT 'Active',
    hris_system                    text,
    hris_worker_id                 text,
    payroll_system                 text,
    payroll_worker_id              text,
    version                        integer NOT NULL DEFAULT 1,
    created_at                     timestamptz NOT NULL DEFAULT now(),
    created_by                     uuid,
    updated_at                     timestamptz NOT NULL DEFAULT now(),
    updated_by                     uuid,
    correlation_id                 text,
    CONSTRAINT staff_pkey PRIMARY KEY (staff_id),
    CONSTRAINT staff_employment_status_ck CHECK (employment_status IN ('Pending', 'Active', 'OnLeave', 'Suspended', 'Terminated')),
    CONSTRAINT staff_version_ck CHECK (version >= 1),
    CONSTRAINT staff_tenant_identity_uq UNIQUE (tenant_id, staff_id),
    CONSTRAINT staff_principal_uq UNIQUE (principal_id),
    CONSTRAINT staff_hris_uq UNIQUE (tenant_id, hris_system, hris_worker_id)
);
COMMENT ON TABLE workforce.staff IS 'Operational staff profile, broadly visible. HR detail lives in spa_service_provider. [§Spa service provider and small HR module; §53.2 Staff management]';

CREATE TABLE workforce.staff_property (
    staff_property_id              uuid NOT NULL DEFAULT core.uuid_v7(),
    tenant_id                      uuid NOT NULL,
    property_id                    uuid NOT NULL,
    staff_id                       uuid NOT NULL,
    bookable                       boolean NOT NULL DEFAULT true,
    status                         text NOT NULL DEFAULT 'Active',
    effective_from                 timestamptz NOT NULL DEFAULT now(),
    effective_to                   timestamptz,
    source_system                  text NOT NULL DEFAULT 'Spa',
    source_key                     text,
    version                        integer NOT NULL DEFAULT 1,
    created_at                     timestamptz NOT NULL DEFAULT now(),
    created_by                     uuid,
    updated_at                     timestamptz NOT NULL DEFAULT now(),
    updated_by                     uuid,
    correlation_id                 text,
    CONSTRAINT staff_property_pkey PRIMARY KEY (staff_property_id),
    CONSTRAINT staff_property_version_ck CHECK (version >= 1),
    CONSTRAINT staff_property_tenant_identity_uq UNIQUE (tenant_id, staff_property_id),
    CONSTRAINT staff_property_status_known CHECK (status IN ('Active', 'Ended')),
    CONSTRAINT staff_property_effective_range_ck CHECK (effective_to IS NULL OR effective_to > effective_from)
);

CREATE TABLE workforce.spa_service_provider (
    spa_service_provider_id        uuid NOT NULL DEFAULT core.uuid_v7(),
    tenant_id                      uuid NOT NULL,
    staff_id                       uuid NOT NULL,
    employee_number                text NOT NULL,
    first_name                     text NOT NULL,
    middle_name                    text,
    last_name                      text NOT NULL,
    work_email                     text,
    personal_email                 text,
    mobile_phone                   text,
    work_phone                     text,
    address_line1                  text,
    address_line2                  text,
    city                           text,
    region                         text,
    postal_code                    text,
    country_code                   char(2),
    worker_type                    text NOT NULL,
    job_title                      text NOT NULL,
    supervisor_staff_id            uuid,
    hire_date                      date,
    end_date                       date,
    languages                      text[] NOT NULL DEFAULT '{}',
    public_bio                     text,
    public_profile_consent         boolean NOT NULL DEFAULT false,
    version                        integer NOT NULL DEFAULT 1,
    created_at                     timestamptz NOT NULL DEFAULT now(),
    created_by                     uuid,
    updated_at                     timestamptz NOT NULL DEFAULT now(),
    updated_by                     uuid,
    correlation_id                 text,
    CONSTRAINT spa_service_provider_pkey PRIMARY KEY (spa_service_provider_id),
    CONSTRAINT spa_service_provider_worker_type_ck CHECK (worker_type IN ('Employee', 'Contractor', 'Agency')),
    CONSTRAINT spa_service_provider_version_ck CHECK (version >= 1),
    CONSTRAINT spa_service_provider_tenant_identity_uq UNIQUE (tenant_id, spa_service_provider_id),
    CONSTRAINT spa_service_provider_dates_ordered CHECK (end_date IS NULL OR hire_date IS NULL OR end_date >= hire_date),
    CONSTRAINT spa_service_provider_staff_uq UNIQUE (staff_id),
    CONSTRAINT spa_service_provider_employee_number_uq UNIQUE (tenant_id, employee_number)
);
COMMENT ON TABLE workforce.spa_service_provider IS 'HR profile. Personal contact and address fields are HR-restricted (hr_compliance, or the worker). [§What belongs on file; SEC-007]';

CREATE TABLE workforce.provider_identity (
    provider_identity_id           uuid NOT NULL DEFAULT core.uuid_v7(),
    tenant_id                      uuid NOT NULL,
    staff_id                       uuid NOT NULL,
    principal_id                   uuid NOT NULL,
    username                       text NOT NULL,
    idp_issuer                     text NOT NULL,
    idp_subject                    text NOT NULL,
    mfa_required                   boolean NOT NULL DEFAULT true,
    last_authenticated_at          timestamptz,
    last_identity_sync_at          timestamptz,
    external_person_ref            text,
    status                         text NOT NULL DEFAULT 'Active',
    version                        integer NOT NULL DEFAULT 1,
    created_at                     timestamptz NOT NULL DEFAULT now(),
    created_by                     uuid,
    updated_at                     timestamptz NOT NULL DEFAULT now(),
    updated_by                     uuid,
    correlation_id                 text,
    CONSTRAINT provider_identity_pkey PRIMARY KEY (provider_identity_id),
    CONSTRAINT provider_identity_version_ck CHECK (version >= 1),
    CONSTRAINT provider_identity_tenant_identity_uq UNIQUE (tenant_id, provider_identity_id),
    CONSTRAINT provider_identity_status_known CHECK (status IN ('Active', 'Disabled', 'Locked')),
    CONSTRAINT provider_identity_subject_uq UNIQUE (idp_issuer, idp_subject),
    CONSTRAINT provider_identity_staff_uq UNIQUE (staff_id),
    CONSTRAINT provider_identity_principal_uq UNIQUE (principal_id)
);
COMMENT ON TABLE workforce.provider_identity IS 'Links a staff member''s principal to their Entra ID subject. The API resolves (issuer, subject) here. [§Security and audit (provider identity rows never contain a password); §24 OIDC/SSO]';
COMMENT ON COLUMN workforce.provider_identity.idp_subject IS 'Entra object id (oid)';

CREATE TABLE workforce.provider_license_type (
    license_type_code              text NOT NULL,
    name                           text NOT NULL,
    category                       text NOT NULL,
    typical_issuer                 text NOT NULL,
    jurisdiction_dependent         boolean NOT NULL DEFAULT true,
    usage_notes                    text NOT NULL,
    source_url                     text NOT NULL,
    reviewed_on                    date NOT NULL,
    status                         text NOT NULL DEFAULT 'Active',
    effective_from                 timestamptz NOT NULL DEFAULT now(),
    effective_to                   timestamptz,
    version                        integer NOT NULL DEFAULT 1,
    created_at                     timestamptz NOT NULL DEFAULT now(),
    created_by                     uuid,
    updated_at                     timestamptz NOT NULL DEFAULT now(),
    updated_by                     uuid,
    correlation_id                 text,
    CONSTRAINT provider_license_type_pkey PRIMARY KEY (license_type_code),
    CONSTRAINT provider_license_type_version_ck CHECK (version >= 1),
    CONSTRAINT provider_license_type_status_known CHECK (status IN ('Active', 'Retired')),
    CONSTRAINT provider_license_type_effective_range_ck CHECK (effective_to IS NULL OR effective_to > effective_from)
);

CREATE TABLE workforce.staff_document (
    document_id                    uuid NOT NULL DEFAULT core.uuid_v7(),
    tenant_id                      uuid NOT NULL,
    staff_id                       uuid NOT NULL,
    document_type                  text NOT NULL,
    object_reference               text NOT NULL,
    content_sha256                 char(64) NOT NULL,
    mime_type                      text NOT NULL,
    size_bytes                     bigint NOT NULL,
    malware_scan_status            text NOT NULL DEFAULT 'Pending',
    access_class                   text NOT NULL,
    data_retention_rule_id         uuid,
    expires_on                     date,
    acknowledged_at                timestamptz,
    template_version               text,
    status                         text NOT NULL DEFAULT 'Active',
    version                        integer NOT NULL DEFAULT 1,
    created_at                     timestamptz NOT NULL DEFAULT now(),
    created_by                     uuid,
    updated_at                     timestamptz NOT NULL DEFAULT now(),
    updated_by                     uuid,
    correlation_id                 text,
    CONSTRAINT staff_document_pkey PRIMARY KEY (document_id),
    CONSTRAINT staff_document_size_bytes_ck CHECK (size_bytes > 0),
    CONSTRAINT staff_document_malware_scan_status_ck CHECK (malware_scan_status IN ('Pending', 'Clean', 'Infected', 'Failed')),
    CONSTRAINT staff_document_access_class_ck CHECK (access_class IN ('Operational', 'Employment', 'Screening', 'Payroll')),
    CONSTRAINT staff_document_version_ck CHECK (version >= 1),
    CONSTRAINT staff_document_tenant_identity_uq UNIQUE (tenant_id, document_id),
    CONSTRAINT staff_document_status_known CHECK (status IN ('Active', 'Superseded', 'Expired'))
);
COMMENT ON TABLE workforce.staff_document IS 'Metadata only; the file lives in blob storage. [SEC-007; §53.2 document upload]';

CREATE TABLE workforce.credential (
    credential_id                  uuid NOT NULL DEFAULT core.uuid_v7(),
    tenant_id                      uuid NOT NULL,
    staff_id                       uuid NOT NULL,
    license_type_code              text NOT NULL,
    jurisdiction                   text,
    issuer_name                    text,
    number_cipher                  bytea,
    number_key_version             text,
    number_last4                   char(4),
    issued_at                      date,
    expires_at                     date,
    renewal_due_at                 date,
    verified_by                    uuid,
    verified_at                    timestamptz,
    verification_reference         text,
    evidence_document_id           uuid,
    restrictions                   text,
    status                         text NOT NULL DEFAULT 'Pending',
    version                        integer NOT NULL DEFAULT 1,
    created_at                     timestamptz NOT NULL DEFAULT now(),
    created_by                     uuid,
    updated_at                     timestamptz NOT NULL DEFAULT now(),
    updated_by                     uuid,
    correlation_id                 text,
    CONSTRAINT credential_pkey PRIMARY KEY (credential_id),
    CONSTRAINT credential_version_ck CHECK (version >= 1),
    CONSTRAINT credential_tenant_identity_uq UNIQUE (tenant_id, credential_id),
    CONSTRAINT credential_status_known CHECK (status IN ('Pending', 'Verified', 'Expired', 'Revoked', 'Rejected')),
    CONSTRAINT credential_cipher_has_key CHECK ((number_cipher IS NULL) = (number_key_version IS NULL)),
    CONSTRAINT credential_verified_complete CHECK (status <> 'Verified' OR (verified_by IS NOT NULL AND verified_at IS NOT NULL)),
    CONSTRAINT credential_dates_ordered CHECK (expires_at IS NULL OR issued_at IS NULL OR expires_at >= issued_at)
);

CREATE TABLE workforce.service_qualification_requirement (
    service_qualification_requirement_id uuid NOT NULL DEFAULT core.uuid_v7(),
    tenant_id                      uuid NOT NULL,
    service_id                     uuid NOT NULL,
    requirement_type               text NOT NULL,
    license_type_code              text,
    jurisdiction                   text,
    status                         text NOT NULL DEFAULT 'Active',
    effective_from                 timestamptz NOT NULL DEFAULT now(),
    effective_to                   timestamptz,
    source_system                  text NOT NULL DEFAULT 'Spa',
    source_key                     text,
    version                        integer NOT NULL DEFAULT 1,
    created_at                     timestamptz NOT NULL DEFAULT now(),
    created_by                     uuid,
    updated_at                     timestamptz NOT NULL DEFAULT now(),
    updated_by                     uuid,
    correlation_id                 text,
    CONSTRAINT service_qualification_requirement_pkey PRIMARY KEY (service_qualification_requirement_id),
    CONSTRAINT service_qualification_requirement_requirement_type_ck CHECK (requirement_type IN ('License', 'Certification', 'Training')),
    CONSTRAINT service_qualification_requirement_version_ck CHECK (version >= 1),
    CONSTRAINT service_qualification_requirement_tenant_identity_uq UNIQUE (tenant_id, service_qualification_requirement_id),
    CONSTRAINT service_qualification_requirement_status_known CHECK (status IN ('Active', 'Retired')),
    CONSTRAINT service_qualification_requirement_effective_range_ck CHECK (effective_to IS NULL OR effective_to > effective_from),
    CONSTRAINT service_qualification_requirement_license_named CHECK (requirement_type = 'Training' OR license_type_code IS NOT NULL)
);

CREATE TABLE workforce.staff_qualification (
    qualification_id               uuid NOT NULL DEFAULT core.uuid_v7(),
    tenant_id                      uuid NOT NULL,
    staff_id                       uuid NOT NULL,
    service_id                     uuid NOT NULL,
    credential_id                  uuid,
    effective_range                tstzrange NOT NULL,
    granted_by                     uuid,
    status                         text NOT NULL DEFAULT 'Active',
    version                        integer NOT NULL DEFAULT 1,
    created_at                     timestamptz NOT NULL DEFAULT now(),
    created_by                     uuid,
    updated_at                     timestamptz NOT NULL DEFAULT now(),
    updated_by                     uuid,
    correlation_id                 text,
    CONSTRAINT staff_qualification_pkey PRIMARY KEY (qualification_id),
    CONSTRAINT staff_qualification_version_ck CHECK (version >= 1),
    CONSTRAINT staff_qualification_tenant_identity_uq UNIQUE (tenant_id, qualification_id),
    CONSTRAINT staff_qualification_status_known CHECK (status IN ('Active', 'Suspended', 'Expired', 'Revoked'))
);

CREATE TABLE workforce.staff_role_assignment (
    staff_role_assignment_id       uuid NOT NULL DEFAULT core.uuid_v7(),
    tenant_id                      uuid NOT NULL,
    property_id                    uuid,
    staff_id                       uuid NOT NULL,
    role_code                      text NOT NULL,
    approved_by                    uuid,
    approved_at                    timestamptz,
    fga_synced_at                  timestamptz,
    status                         text NOT NULL DEFAULT 'Proposed',
    effective_from                 timestamptz NOT NULL DEFAULT now(),
    effective_to                   timestamptz,
    source_system                  text NOT NULL DEFAULT 'Spa',
    source_key                     text,
    version                        integer NOT NULL DEFAULT 1,
    created_at                     timestamptz NOT NULL DEFAULT now(),
    created_by                     uuid,
    updated_at                     timestamptz NOT NULL DEFAULT now(),
    updated_by                     uuid,
    correlation_id                 text,
    CONSTRAINT staff_role_assignment_pkey PRIMARY KEY (staff_role_assignment_id),
    CONSTRAINT staff_role_assignment_role_code_ck CHECK (role_code IN ('guest', 'provider', 'front_desk', 'spa_manager', 'hr_compliance', 'finance', 'platform_admin', 'configuration_approver', 'scheduler', 'housekeeping', 'inventory_manager', 'marketing', 'support', 'operations_analyst', 'executive', 'release_manager', 'security_admin', 'integration_service')),
    CONSTRAINT staff_role_assignment_version_ck CHECK (version >= 1),
    CONSTRAINT staff_role_assignment_tenant_identity_uq UNIQUE (tenant_id, staff_role_assignment_id),
    CONSTRAINT staff_role_assignment_status_known CHECK (status IN ('Proposed', 'Active', 'Revoked', 'Expired')),
    CONSTRAINT staff_role_assignment_effective_range_ck CHECK (effective_to IS NULL OR effective_to > effective_from),
    CONSTRAINT staff_role_assignment_active_is_approved CHECK (status <> 'Active' OR approved_by IS NOT NULL),
    CONSTRAINT staff_role_assignment_approver_not_proposer CHECK (approved_by IS NULL OR approved_by IS DISTINCT FROM created_by)
);
COMMENT ON TABLE workforce.staff_role_assignment IS 'Source of truth for OpenFGA role tuples. property_id NULL = tenant-wide role (e.g. hr_compliance). [technical/config/role_permissions.json; security.assign_role:approved]';
COMMENT ON COLUMN workforce.staff_role_assignment.fga_synced_at IS 'set when the outbox worker confirms the tuple write';

CREATE TABLE workforce.staff_leave (
    staff_leave_id                 uuid NOT NULL DEFAULT core.uuid_v7(),
    tenant_id                      uuid NOT NULL,
    staff_id                       uuid NOT NULL,
    leave_type                     text NOT NULL,
    starts_at                      timestamptz NOT NULL,
    ends_at                        timestamptz NOT NULL,
    approved_by                    uuid,
    approved_at                    timestamptz,
    status                         text NOT NULL DEFAULT 'Requested',
    version                        integer NOT NULL DEFAULT 1,
    created_at                     timestamptz NOT NULL DEFAULT now(),
    created_by                     uuid,
    updated_at                     timestamptz NOT NULL DEFAULT now(),
    updated_by                     uuid,
    correlation_id                 text,
    CONSTRAINT staff_leave_pkey PRIMARY KEY (staff_leave_id),
    CONSTRAINT staff_leave_leave_type_ck CHECK (leave_type IN ('Planned', 'Unplanned', 'Training', 'Other')),
    CONSTRAINT staff_leave_version_ck CHECK (version >= 1),
    CONSTRAINT staff_leave_tenant_identity_uq UNIQUE (tenant_id, staff_leave_id),
    CONSTRAINT staff_leave_status_known CHECK (status IN ('Requested', 'Approved', 'Rejected', 'Cancelled')),
    CONSTRAINT staff_leave_range_forward CHECK (ends_at > starts_at)
);

CREATE TABLE workforce.work_schedule (
    work_schedule_id               uuid NOT NULL DEFAULT core.uuid_v7(),
    tenant_id                      uuid NOT NULL,
    property_id                    uuid NOT NULL,
    staff_id                       uuid NOT NULL,
    schedule_date                  date NOT NULL,
    starts_at                      timestamptz NOT NULL,
    ends_at                        timestamptz NOT NULL,
    shift_type                     text NOT NULL DEFAULT 'Scheduled',
    status                         text NOT NULL DEFAULT 'Draft',
    version                        integer NOT NULL DEFAULT 1,
    created_at                     timestamptz NOT NULL DEFAULT now(),
    created_by                     uuid,
    updated_at                     timestamptz NOT NULL DEFAULT now(),
    updated_by                     uuid,
    correlation_id                 text,
    CONSTRAINT work_schedule_pkey PRIMARY KEY (work_schedule_id),
    CONSTRAINT work_schedule_shift_type_ck CHECK (shift_type IN ('Scheduled', 'OnCall')),
    CONSTRAINT work_schedule_version_ck CHECK (version >= 1),
    CONSTRAINT work_schedule_tenant_identity_uq UNIQUE (tenant_id, work_schedule_id),
    CONSTRAINT work_schedule_status_known CHECK (status IN ('Draft', 'Published', 'Cancelled')),
    CONSTRAINT work_schedule_range_forward CHECK (ends_at > starts_at)
);

CREATE TABLE workforce.background_screening (
    screening_id                   uuid NOT NULL DEFAULT core.uuid_v7(),
    tenant_id                      uuid NOT NULL,
    staff_id                       uuid NOT NULL,
    provider_name                  text NOT NULL,
    provider_case_reference        text NOT NULL,
    package_code                   text NOT NULL,
    jurisdiction                   text NOT NULL,
    consent_reference              text NOT NULL,
    requested_at                   timestamptz NOT NULL,
    completed_at                   timestamptz,
    expires_at                     timestamptz,
    adjudication                   text,
    adjudicated_by                 uuid,
    adjudicated_at                 timestamptz,
    status                         text NOT NULL DEFAULT 'Requested',
    version                        integer NOT NULL DEFAULT 1,
    created_at                     timestamptz NOT NULL DEFAULT now(),
    created_by                     uuid,
    updated_at                     timestamptz NOT NULL DEFAULT now(),
    updated_by                     uuid,
    correlation_id                 text,
    CONSTRAINT background_screening_pkey PRIMARY KEY (screening_id),
    CONSTRAINT background_screening_adjudication_ck CHECK (adjudication IN ('Eligible', 'NotEligible', 'ReviewRequired', 'Withdrawn')),
    CONSTRAINT background_screening_version_ck CHECK (version >= 1),
    CONSTRAINT background_screening_tenant_identity_uq UNIQUE (tenant_id, screening_id),
    CONSTRAINT background_screening_status_known CHECK (status IN ('Requested', 'InProgress', 'Completed', 'Cancelled', 'Expired')),
    CONSTRAINT background_screening_adjudication_complete CHECK ((adjudication IS NULL) = (adjudicated_at IS NULL))
);

ALTER TABLE workforce.staff ADD CONSTRAINT staff_principal_id_fk FOREIGN KEY (tenant_id, principal_id) REFERENCES core.principal (tenant_id, principal_id) ON DELETE RESTRICT;
CREATE INDEX staff_principal_id_ix ON workforce.staff (tenant_id, principal_id);
ALTER TABLE workforce.staff ADD CONSTRAINT staff_home_property_id_fk FOREIGN KEY (tenant_id, home_property_id) REFERENCES core.property (tenant_id, property_id) ON DELETE RESTRICT;
CREATE INDEX staff_home_property_id_ix ON workforce.staff (tenant_id, home_property_id);
ALTER TABLE workforce.staff ADD CONSTRAINT staff_department_id_fk FOREIGN KEY (tenant_id, department_id) REFERENCES core.department (tenant_id, department_id) ON DELETE RESTRICT;
CREATE INDEX staff_department_id_ix ON workforce.staff (tenant_id, department_id);
ALTER TABLE workforce.staff ADD CONSTRAINT staff_tenant_fk FOREIGN KEY (tenant_id) REFERENCES core.tenant (tenant_id);
ALTER TABLE workforce.staff_property ADD CONSTRAINT staff_property_staff_id_fk FOREIGN KEY (tenant_id, staff_id) REFERENCES workforce.staff (tenant_id, staff_id) ON DELETE RESTRICT;
CREATE INDEX staff_property_staff_id_ix ON workforce.staff_property (tenant_id, staff_id);
CREATE INDEX staff_property_scope_ix ON workforce.staff_property (tenant_id, property_id);
ALTER TABLE workforce.staff_property ADD CONSTRAINT staff_property_tenant_fk FOREIGN KEY (tenant_id) REFERENCES core.tenant (tenant_id);
ALTER TABLE workforce.staff_property ADD CONSTRAINT staff_property_property_fk FOREIGN KEY (tenant_id, property_id) REFERENCES core.property (tenant_id, property_id);
ALTER TABLE workforce.spa_service_provider ADD CONSTRAINT spa_service_provider_staff_id_fk FOREIGN KEY (tenant_id, staff_id) REFERENCES workforce.staff (tenant_id, staff_id) ON DELETE RESTRICT;
CREATE INDEX spa_service_provider_staff_id_ix ON workforce.spa_service_provider (tenant_id, staff_id);
ALTER TABLE workforce.spa_service_provider ADD CONSTRAINT spa_service_provider_supervisor_staff_id_fk FOREIGN KEY (tenant_id, supervisor_staff_id) REFERENCES workforce.staff (tenant_id, staff_id) ON DELETE RESTRICT;
CREATE INDEX spa_service_provider_supervisor_staff_id_ix ON workforce.spa_service_provider (tenant_id, supervisor_staff_id);
ALTER TABLE workforce.spa_service_provider ADD CONSTRAINT spa_service_provider_tenant_fk FOREIGN KEY (tenant_id) REFERENCES core.tenant (tenant_id);
ALTER TABLE workforce.provider_identity ADD CONSTRAINT provider_identity_staff_id_fk FOREIGN KEY (tenant_id, staff_id) REFERENCES workforce.staff (tenant_id, staff_id) ON DELETE RESTRICT;
CREATE INDEX provider_identity_staff_id_ix ON workforce.provider_identity (tenant_id, staff_id);
ALTER TABLE workforce.provider_identity ADD CONSTRAINT provider_identity_principal_id_fk FOREIGN KEY (tenant_id, principal_id) REFERENCES core.principal (tenant_id, principal_id) ON DELETE RESTRICT;
CREATE INDEX provider_identity_principal_id_ix ON workforce.provider_identity (tenant_id, principal_id);
ALTER TABLE workforce.provider_identity ADD CONSTRAINT provider_identity_tenant_fk FOREIGN KEY (tenant_id) REFERENCES core.tenant (tenant_id);
ALTER TABLE workforce.staff_document ADD CONSTRAINT staff_document_staff_id_fk FOREIGN KEY (tenant_id, staff_id) REFERENCES workforce.staff (tenant_id, staff_id) ON DELETE RESTRICT;
CREATE INDEX staff_document_staff_id_ix ON workforce.staff_document (tenant_id, staff_id);
ALTER TABLE workforce.staff_document ADD CONSTRAINT staff_document_data_retention_rule_id_fk FOREIGN KEY (tenant_id, data_retention_rule_id) REFERENCES core.data_retention_rule (tenant_id, data_retention_rule_id) ON DELETE RESTRICT;
CREATE INDEX staff_document_data_retention_rule_id_ix ON workforce.staff_document (tenant_id, data_retention_rule_id);
ALTER TABLE workforce.staff_document ADD CONSTRAINT staff_document_tenant_fk FOREIGN KEY (tenant_id) REFERENCES core.tenant (tenant_id);
ALTER TABLE workforce.credential ADD CONSTRAINT credential_staff_id_fk FOREIGN KEY (tenant_id, staff_id) REFERENCES workforce.staff (tenant_id, staff_id) ON DELETE RESTRICT;
CREATE INDEX credential_staff_id_ix ON workforce.credential (tenant_id, staff_id);
ALTER TABLE workforce.credential ADD CONSTRAINT credential_license_type_code_fk FOREIGN KEY (license_type_code) REFERENCES workforce.provider_license_type (license_type_code) ON DELETE RESTRICT;
CREATE INDEX credential_license_type_code_ix ON workforce.credential (license_type_code);
ALTER TABLE workforce.credential ADD CONSTRAINT credential_evidence_document_id_fk FOREIGN KEY (tenant_id, evidence_document_id) REFERENCES workforce.staff_document (tenant_id, document_id) ON DELETE RESTRICT;
CREATE INDEX credential_evidence_document_id_ix ON workforce.credential (tenant_id, evidence_document_id);
ALTER TABLE workforce.credential ADD CONSTRAINT credential_tenant_fk FOREIGN KEY (tenant_id) REFERENCES core.tenant (tenant_id);
ALTER TABLE workforce.service_qualification_requirement ADD CONSTRAINT service_qualification_requirement_service_id_fk FOREIGN KEY (tenant_id, service_id) REFERENCES catalog.service (tenant_id, service_id) ON DELETE RESTRICT;
CREATE INDEX service_qualification_requirement_service_id_ix ON workforce.service_qualification_requirement (tenant_id, service_id);
ALTER TABLE workforce.service_qualification_requirement ADD CONSTRAINT service_qualification_requirement_license_type_code_fk FOREIGN KEY (license_type_code) REFERENCES workforce.provider_license_type (license_type_code) ON DELETE RESTRICT;
CREATE INDEX service_qualification_requirement_license_type_code_ix ON workforce.service_qualification_requirement (license_type_code);
ALTER TABLE workforce.service_qualification_requirement ADD CONSTRAINT service_qualification_requirement_tenant_fk FOREIGN KEY (tenant_id) REFERENCES core.tenant (tenant_id);
ALTER TABLE workforce.staff_qualification ADD CONSTRAINT staff_qualification_staff_id_fk FOREIGN KEY (tenant_id, staff_id) REFERENCES workforce.staff (tenant_id, staff_id) ON DELETE RESTRICT;
CREATE INDEX staff_qualification_staff_id_ix ON workforce.staff_qualification (tenant_id, staff_id);
ALTER TABLE workforce.staff_qualification ADD CONSTRAINT staff_qualification_service_id_fk FOREIGN KEY (tenant_id, service_id) REFERENCES catalog.service (tenant_id, service_id) ON DELETE RESTRICT;
CREATE INDEX staff_qualification_service_id_ix ON workforce.staff_qualification (tenant_id, service_id);
ALTER TABLE workforce.staff_qualification ADD CONSTRAINT staff_qualification_credential_id_fk FOREIGN KEY (tenant_id, credential_id) REFERENCES workforce.credential (tenant_id, credential_id) ON DELETE RESTRICT;
CREATE INDEX staff_qualification_credential_id_ix ON workforce.staff_qualification (tenant_id, credential_id);
ALTER TABLE workforce.staff_qualification ADD CONSTRAINT staff_qualification_tenant_fk FOREIGN KEY (tenant_id) REFERENCES core.tenant (tenant_id);
ALTER TABLE workforce.staff_role_assignment ADD CONSTRAINT staff_role_assignment_staff_id_fk FOREIGN KEY (tenant_id, staff_id) REFERENCES workforce.staff (tenant_id, staff_id) ON DELETE RESTRICT;
CREATE INDEX staff_role_assignment_staff_id_ix ON workforce.staff_role_assignment (tenant_id, staff_id);
CREATE INDEX staff_role_assignment_scope_ix ON workforce.staff_role_assignment (tenant_id, property_id);
ALTER TABLE workforce.staff_role_assignment ADD CONSTRAINT staff_role_assignment_tenant_fk FOREIGN KEY (tenant_id) REFERENCES core.tenant (tenant_id);
ALTER TABLE workforce.staff_role_assignment ADD CONSTRAINT staff_role_assignment_property_fk FOREIGN KEY (tenant_id, property_id) REFERENCES core.property (tenant_id, property_id);
ALTER TABLE workforce.staff_leave ADD CONSTRAINT staff_leave_staff_id_fk FOREIGN KEY (tenant_id, staff_id) REFERENCES workforce.staff (tenant_id, staff_id) ON DELETE RESTRICT;
CREATE INDEX staff_leave_staff_id_ix ON workforce.staff_leave (tenant_id, staff_id);
ALTER TABLE workforce.staff_leave ADD CONSTRAINT staff_leave_tenant_fk FOREIGN KEY (tenant_id) REFERENCES core.tenant (tenant_id);
ALTER TABLE workforce.work_schedule ADD CONSTRAINT work_schedule_staff_id_fk FOREIGN KEY (tenant_id, staff_id) REFERENCES workforce.staff (tenant_id, staff_id) ON DELETE RESTRICT;
CREATE INDEX work_schedule_staff_id_ix ON workforce.work_schedule (tenant_id, staff_id);
CREATE INDEX work_schedule_scope_ix ON workforce.work_schedule (tenant_id, property_id);
ALTER TABLE workforce.work_schedule ADD CONSTRAINT work_schedule_tenant_fk FOREIGN KEY (tenant_id) REFERENCES core.tenant (tenant_id);
ALTER TABLE workforce.work_schedule ADD CONSTRAINT work_schedule_property_fk FOREIGN KEY (tenant_id, property_id) REFERENCES core.property (tenant_id, property_id);
ALTER TABLE workforce.background_screening ADD CONSTRAINT background_screening_staff_id_fk FOREIGN KEY (tenant_id, staff_id) REFERENCES workforce.staff (tenant_id, staff_id) ON DELETE RESTRICT;
CREATE INDEX background_screening_staff_id_ix ON workforce.background_screening (tenant_id, staff_id);
ALTER TABLE workforce.background_screening ADD CONSTRAINT background_screening_tenant_fk FOREIGN KEY (tenant_id) REFERENCES core.tenant (tenant_id);

CREATE TRIGGER staff_touch BEFORE UPDATE ON workforce.staff FOR EACH ROW EXECUTE FUNCTION core.touch_versioned();
CREATE TRIGGER staff_property_touch BEFORE UPDATE ON workforce.staff_property FOR EACH ROW EXECUTE FUNCTION core.touch_versioned();
CREATE TRIGGER spa_service_provider_touch BEFORE UPDATE ON workforce.spa_service_provider FOR EACH ROW EXECUTE FUNCTION core.touch_versioned();
CREATE TRIGGER provider_identity_touch BEFORE UPDATE ON workforce.provider_identity FOR EACH ROW EXECUTE FUNCTION core.touch_versioned();
CREATE TRIGGER provider_license_type_touch BEFORE UPDATE ON workforce.provider_license_type FOR EACH ROW EXECUTE FUNCTION core.touch_versioned();
CREATE TRIGGER staff_document_touch BEFORE UPDATE ON workforce.staff_document FOR EACH ROW EXECUTE FUNCTION core.touch_versioned();
CREATE TRIGGER credential_touch BEFORE UPDATE ON workforce.credential FOR EACH ROW EXECUTE FUNCTION core.touch_versioned();
CREATE TRIGGER service_qualification_requirement_touch BEFORE UPDATE ON workforce.service_qualification_requirement FOR EACH ROW EXECUTE FUNCTION core.touch_versioned();
CREATE TRIGGER staff_qualification_touch BEFORE UPDATE ON workforce.staff_qualification FOR EACH ROW EXECUTE FUNCTION core.touch_versioned();
CREATE TRIGGER staff_role_assignment_touch BEFORE UPDATE ON workforce.staff_role_assignment FOR EACH ROW EXECUTE FUNCTION core.touch_versioned();
CREATE TRIGGER staff_leave_touch BEFORE UPDATE ON workforce.staff_leave FOR EACH ROW EXECUTE FUNCTION core.touch_versioned();
CREATE TRIGGER work_schedule_touch BEFORE UPDATE ON workforce.work_schedule FOR EACH ROW EXECUTE FUNCTION core.touch_versioned();
CREATE TRIGGER background_screening_touch BEFORE UPDATE ON workforce.background_screening FOR EACH ROW EXECUTE FUNCTION core.touch_versioned();

ALTER TABLE workforce.staff_property ADD CONSTRAINT staff_property_no_overlap
    EXCLUDE USING gist (tenant_id WITH =, property_id WITH =, staff_id WITH =,
                        tstzrange(effective_from, coalesce(effective_to, 'infinity'), '[)') WITH &&)
    WHERE (status = 'Active');
CREATE INDEX credential_expiry_ix ON workforce.credential (tenant_id, expires_at) WHERE status = 'Verified';

ALTER TABLE workforce.staff_qualification ADD CONSTRAINT staff_qualification_no_overlap
    EXCLUDE USING gist (tenant_id WITH =, staff_id WITH =, service_id WITH =, effective_range WITH &&)
    WHERE (status = 'Active');

ALTER TABLE workforce.staff_role_assignment ADD CONSTRAINT staff_role_assignment_no_overlap
    EXCLUDE USING gist (tenant_id WITH =, (coalesce(property_id, '00000000-0000-0000-0000-000000000000'::uuid)) WITH =,
                        staff_id WITH =, role_code WITH =,
                        tstzrange(effective_from, coalesce(effective_to, 'infinity'), '[)') WITH &&)
    WHERE (status IN ('Proposed', 'Active'));
CREATE INDEX staff_leave_window_ix ON workforce.staff_leave USING gist (tenant_id, staff_id, tstzrange(starts_at, ends_at, '[)')) WHERE status = 'Approved';

-- A person is in one place at a time: no overlapping published shifts, across properties.
ALTER TABLE workforce.work_schedule ADD CONSTRAINT work_schedule_no_overlap
    EXCLUDE USING gist (tenant_id WITH =, staff_id WITH =, tstzrange(starts_at, ends_at, '[)') WITH &&)
    WHERE (status = 'Published');
