-- 05 guest: generated by database/tools/generate.py from database/model/. Do not edit.
-- may reference: core

CREATE SCHEMA IF NOT EXISTS guest AUTHORIZATION spms_owner;

CREATE TABLE guest.guest (
    guest_id                       uuid NOT NULL DEFAULT core.uuid_v7(),
    tenant_id                      uuid NOT NULL,
    principal_id                   uuid,
    home_property_id               uuid,
    legal_first_name               text,
    legal_last_name                text,
    preferred_name                 text,
    display_alias                  text,
    public_queue_id                text,
    birth_date                     date,
    locale                         text,
    preferences                    jsonb NOT NULL DEFAULT '{}',
    merged_into_guest_id           uuid,
    status                         text NOT NULL DEFAULT 'Active',
    source_system                  text NOT NULL DEFAULT 'Spa',
    source_key                     text,
    version                        integer NOT NULL DEFAULT 1,
    created_at                     timestamptz NOT NULL DEFAULT now(),
    created_by                     uuid,
    updated_at                     timestamptz NOT NULL DEFAULT now(),
    updated_by                     uuid,
    correlation_id                 text,
    CONSTRAINT guest_pkey PRIMARY KEY (guest_id),
    CONSTRAINT guest_version_ck CHECK (version >= 1),
    CONSTRAINT guest_tenant_identity_uq UNIQUE (tenant_id, guest_id),
    CONSTRAINT guest_status_known CHECK (status IN ('Active', 'Restricted', 'Merged', 'Deceased', 'Erased')),
    CONSTRAINT guest_merge_consistent CHECK ((status = 'Merged') = (merged_into_guest_id IS NOT NULL)),
    CONSTRAINT guest_not_self_merged CHECK (merged_into_guest_id IS DISTINCT FROM guest_id),
    CONSTRAINT guest_principal_uq UNIQUE (principal_id)
);
COMMENT ON TABLE guest.guest IS 'One person, recognised across the tenant''s properties. Never merged silently (IDN-001). [§43 Guest identity, household and delegated authority; IDN-001/002/004/005]';
COMMENT ON COLUMN guest.guest.principal_id IS 'set once the guest signs in (magic link)';
COMMENT ON COLUMN guest.guest.display_alias IS 'IDN-002 privacy alias shown instead of the legal name';
COMMENT ON COLUMN guest.guest.public_queue_id IS 'IDN-002 public identifier for queues and screens';
COMMENT ON COLUMN guest.guest.birth_date IS 'minor/guardian rules (IDN-004)';
COMMENT ON COLUMN guest.guest.preferences IS 'operational preferences (pressure, music, provider gender); health data is refused here - it is intake';

CREATE TABLE guest.guest_contact_point (
    guest_contact_point_id         uuid NOT NULL DEFAULT core.uuid_v7(),
    tenant_id                      uuid NOT NULL,
    guest_id                       uuid NOT NULL,
    contact_type                   text NOT NULL,
    contact_cipher                 bytea NOT NULL,
    key_version                    text NOT NULL,
    lookup_hash                    char(64) NOT NULL,
    display_hint                   text NOT NULL,
    is_primary                     boolean NOT NULL DEFAULT false,
    verified_at                    timestamptz,
    suppression_reason             text,
    status                         text NOT NULL DEFAULT 'Active',
    source_system                  text NOT NULL DEFAULT 'Spa',
    source_key                     text,
    version                        integer NOT NULL DEFAULT 1,
    created_at                     timestamptz NOT NULL DEFAULT now(),
    created_by                     uuid,
    updated_at                     timestamptz NOT NULL DEFAULT now(),
    updated_by                     uuid,
    correlation_id                 text,
    CONSTRAINT guest_contact_point_pkey PRIMARY KEY (guest_contact_point_id),
    CONSTRAINT guest_contact_point_contact_type_ck CHECK (contact_type IN ('Email', 'Mobile', 'Phone', 'Address')),
    CONSTRAINT guest_contact_point_suppression_reason_ck CHECK (suppression_reason IN ('Bounce', 'Complaint', 'Invalid')),
    CONSTRAINT guest_contact_point_version_ck CHECK (version >= 1),
    CONSTRAINT guest_contact_point_tenant_identity_uq UNIQUE (tenant_id, guest_contact_point_id),
    CONSTRAINT guest_contact_point_status_known CHECK (status IN ('Active', 'Retired', 'Suppressed')),
    CONSTRAINT guest_contact_point_suppressed_explained CHECK ((status = 'Suppressed') = (suppression_reason IS NOT NULL))
);
COMMENT ON TABLE guest.guest_contact_point IS 'lookup_hash is an HMAC of the normalised value (key in Key Vault): searchable without decrypting. [UX-002 universal search by phone/email; SEC-011 verified contact methods]';
COMMENT ON COLUMN guest.guest_contact_point.display_hint IS 'masked form for screens, e.g. j***@example.com';

CREATE TABLE guest.guest_relationship (
    guest_relationship_id          uuid NOT NULL DEFAULT core.uuid_v7(),
    tenant_id                      uuid NOT NULL,
    guest_id                       uuid NOT NULL,
    related_guest_id               uuid NOT NULL,
    relationship_type              text NOT NULL,
    status                         text NOT NULL DEFAULT 'Active',
    effective_from                 timestamptz NOT NULL DEFAULT now(),
    effective_to                   timestamptz,
    source_system                  text NOT NULL DEFAULT 'Spa',
    source_key                     text,
    version                        integer NOT NULL DEFAULT 1,
    created_at                     timestamptz NOT NULL DEFAULT now(),
    created_by                     uuid,
    updated_at                     timestamptz NOT NULL DEFAULT now(),
    updated_by                     uuid,
    correlation_id                 text,
    CONSTRAINT guest_relationship_pkey PRIMARY KEY (guest_relationship_id),
    CONSTRAINT guest_relationship_relationship_type_ck CHECK (relationship_type IN ('Household', 'SpousePartner', 'ParentGuardian', 'Child', 'Dependent', 'Assistant', 'Organizer', 'Payer', 'EmergencyContact')),
    CONSTRAINT guest_relationship_version_ck CHECK (version >= 1),
    CONSTRAINT guest_relationship_tenant_identity_uq UNIQUE (tenant_id, guest_relationship_id),
    CONSTRAINT guest_relationship_status_known CHECK (status IN ('Active', 'Ended')),
    CONSTRAINT guest_relationship_effective_range_ck CHECK (effective_to IS NULL OR effective_to > effective_from),
    CONSTRAINT guest_relationship_not_self CHECK (guest_id <> related_guest_id)
);

CREATE TABLE guest.guest_merge_case (
    guest_merge_case_id            uuid NOT NULL DEFAULT core.uuid_v7(),
    tenant_id                      uuid NOT NULL,
    surviving_guest_id             uuid NOT NULL,
    duplicate_guest_id             uuid NOT NULL,
    match_signals                  jsonb NOT NULL DEFAULT '{}',
    confidence                     numeric(7,6) NOT NULL,
    decision_reason                text,
    reviewed_by                    uuid,
    reviewed_at                    timestamptz,
    merged_at                      timestamptz,
    split_at                       timestamptz,
    split_reason                   text,
    status                         text NOT NULL DEFAULT 'Candidate',
    source_system                  text NOT NULL DEFAULT 'Spa',
    source_key                     text,
    version                        integer NOT NULL DEFAULT 1,
    created_at                     timestamptz NOT NULL DEFAULT now(),
    created_by                     uuid,
    updated_at                     timestamptz NOT NULL DEFAULT now(),
    updated_by                     uuid,
    correlation_id                 text,
    CONSTRAINT guest_merge_case_pkey PRIMARY KEY (guest_merge_case_id),
    CONSTRAINT guest_merge_case_confidence_ck CHECK (confidence BETWEEN 0 AND 1),
    CONSTRAINT guest_merge_case_version_ck CHECK (version >= 1),
    CONSTRAINT guest_merge_case_tenant_identity_uq UNIQUE (tenant_id, guest_merge_case_id),
    CONSTRAINT guest_merge_case_status_known CHECK (status IN ('Candidate', 'Approved', 'Merged', 'Rejected', 'Split')),
    CONSTRAINT guest_merge_case_distinct_guests CHECK (surviving_guest_id <> duplicate_guest_id),
    CONSTRAINT guest_merge_case_human_reviewed CHECK (status NOT IN ('Approved', 'Merged') OR reviewed_by IS NOT NULL),
    CONSTRAINT guest_merge_case_split_explained CHECK (status <> 'Split' OR (split_at IS NOT NULL AND split_reason IS NOT NULL))
);
COMMENT ON TABLE guest.guest_merge_case IS 'Kept typed: a reviewed, reversible merge is evidence with its own lifecycle. [IDN-001; IDENTITY_MERGE_SPLIT_CONTROL.md]';

CREATE TABLE guest.delegated_authority (
    delegated_authority_id         uuid NOT NULL DEFAULT core.uuid_v7(),
    tenant_id                      uuid NOT NULL,
    guest_id                       uuid NOT NULL,
    delegate_guest_id              uuid,
    delegate_principal_id          uuid,
    allowed_actions                text[] NOT NULL,
    property_ids                   uuid[],
    financial_limit_minor          bigint,
    currency_code                  char(3),
    information_visibility         text NOT NULL,
    evidence_reference             text NOT NULL,
    revoked_at                     timestamptz,
    revoked_by                     uuid,
    fga_synced_at                  timestamptz,
    status                         text NOT NULL DEFAULT 'Active',
    effective_from                 timestamptz NOT NULL DEFAULT now(),
    effective_to                   timestamptz,
    source_system                  text NOT NULL DEFAULT 'Spa',
    source_key                     text,
    version                        integer NOT NULL DEFAULT 1,
    created_at                     timestamptz NOT NULL DEFAULT now(),
    created_by                     uuid,
    updated_at                     timestamptz NOT NULL DEFAULT now(),
    updated_by                     uuid,
    correlation_id                 text,
    CONSTRAINT delegated_authority_pkey PRIMARY KEY (delegated_authority_id),
    CONSTRAINT delegated_authority_allowed_actions_ck CHECK (allowed_actions <@ ARRAY['Book', 'Cancel', 'Reschedule', 'Pay', 'ViewItinerary', 'CompleteIntake']::text[] AND cardinality(allowed_actions) > 0),
    CONSTRAINT delegated_authority_financial_limit_minor_ck CHECK (financial_limit_minor >= 0),
    CONSTRAINT delegated_authority_currency_code_ck CHECK (currency_code ~ '^[A-Z]{3}$'),
    CONSTRAINT delegated_authority_information_visibility_ck CHECK (information_visibility IN ('ItineraryOnly', 'Standard')),
    CONSTRAINT delegated_authority_version_ck CHECK (version >= 1),
    CONSTRAINT delegated_authority_tenant_identity_uq UNIQUE (tenant_id, delegated_authority_id),
    CONSTRAINT delegated_authority_status_known CHECK (status IN ('Active', 'Revoked', 'Expired')),
    CONSTRAINT delegated_authority_effective_range_ck CHECK (effective_to IS NULL OR effective_to > effective_from),
    CONSTRAINT delegated_authority_one_delegate CHECK (num_nonnulls(delegate_guest_id, delegate_principal_id) = 1),
    CONSTRAINT delegated_authority_not_self CHECK (delegate_guest_id IS DISTINCT FROM guest_id),
    CONSTRAINT delegated_authority_limit_has_currency CHECK ((financial_limit_minor IS NULL) = (currency_code IS NULL)),
    CONSTRAINT delegated_authority_revocation_complete CHECK ((status = 'Revoked') = (revoked_at IS NOT NULL AND revoked_by IS NOT NULL)),
    CONSTRAINT delegated_authority_expires CHECK (effective_to IS NOT NULL)
);
COMMENT ON TABLE guest.delegated_authority IS 'A delegate acts only within what is written here. Mirrored to OpenFGA as a conditional tuple. [IDN-003 (explicit scope, actions, financial limit, visibility, expiry, revocation, evidence)]';
COMMENT ON COLUMN guest.delegated_authority.guest_id IS 'the guest whose affairs are delegated';
COMMENT ON COLUMN guest.delegated_authority.property_ids IS 'NULL = every property of the tenant';
COMMENT ON COLUMN guest.delegated_authority.information_visibility IS 'there is deliberately no level that includes intake or treatment notes';

CREATE TABLE guest.consent_record (
    consent_id                     uuid NOT NULL DEFAULT core.uuid_v7(),
    tenant_id                      uuid NOT NULL,
    property_id                    uuid,
    guest_id                       uuid NOT NULL,
    granted_by_guest_id            uuid,
    purpose                        text NOT NULL,
    channel                        text,
    template_id                    text NOT NULL,
    template_version               integer NOT NULL,
    evidence_cipher                bytea NOT NULL,
    key_version                    text NOT NULL,
    effective_at                   timestamptz NOT NULL DEFAULT now(),
    expires_at                     timestamptz,
    revoked_at                     timestamptz,
    revoked_by                     uuid,
    status                         text NOT NULL DEFAULT 'Active',
    version                        integer NOT NULL DEFAULT 1,
    created_at                     timestamptz NOT NULL DEFAULT now(),
    created_by                     uuid,
    updated_at                     timestamptz NOT NULL DEFAULT now(),
    updated_by                     uuid,
    correlation_id                 text,
    CONSTRAINT consent_record_pkey PRIMARY KEY (consent_id),
    CONSTRAINT consent_record_purpose_ck CHECK (purpose IN ('Transactional', 'Marketing', 'HealthIntake', 'Photography', 'MinorService', 'DataSharing', 'Profiling')),
    CONSTRAINT consent_record_channel_ck CHECK (channel IN ('Email', 'Sms', 'WhatsApp', 'Push', 'Phone')),
    CONSTRAINT consent_record_version_ck CHECK (version >= 1),
    CONSTRAINT consent_record_tenant_identity_uq UNIQUE (tenant_id, consent_id),
    CONSTRAINT consent_record_status_known CHECK (status IN ('Active', 'Revoked', 'Expired')),
    CONSTRAINT consent_record_revocation_complete CHECK ((status = 'Revoked') = (revoked_at IS NOT NULL))
);
COMMENT ON TABLE guest.consent_record IS 'Consent evidence is immutable once written; only revocation may change afterwards (trigger-enforced). An SMS STOP or unsubscribe is a revocation. [§24 Privacy purpose/consent; DEC-008; IDN-004 guardian consent]';
COMMENT ON COLUMN guest.consent_record.granted_by_guest_id IS 'guardian granting for a minor';

CREATE TABLE guest.privacy_request (
    privacy_request_id             uuid NOT NULL DEFAULT core.uuid_v7(),
    tenant_id                      uuid NOT NULL,
    guest_id                       uuid NOT NULL,
    request_type                   text NOT NULL,
    jurisdiction                   text,
    requested_at                   timestamptz NOT NULL DEFAULT now(),
    due_at                         timestamptz NOT NULL,
    verified_at                    timestamptz,
    verified_by                    uuid,
    fulfilled_at                   timestamptz,
    rejection_reason               text,
    status                         text NOT NULL DEFAULT 'Received',
    source_system                  text NOT NULL DEFAULT 'Spa',
    source_key                     text,
    version                        integer NOT NULL DEFAULT 1,
    created_at                     timestamptz NOT NULL DEFAULT now(),
    created_by                     uuid,
    updated_at                     timestamptz NOT NULL DEFAULT now(),
    updated_by                     uuid,
    correlation_id                 text,
    CONSTRAINT privacy_request_pkey PRIMARY KEY (privacy_request_id),
    CONSTRAINT privacy_request_request_type_ck CHECK (request_type IN ('Access', 'Export', 'Correction', 'Restriction', 'Deletion', 'ConsentWithdrawal')),
    CONSTRAINT privacy_request_version_ck CHECK (version >= 1),
    CONSTRAINT privacy_request_tenant_identity_uq UNIQUE (tenant_id, privacy_request_id),
    CONSTRAINT privacy_request_status_known CHECK (status IN ('Received', 'Verified', 'InProgress', 'Fulfilled', 'Rejected', 'OnHold')),
    CONSTRAINT privacy_request_fulfilled_complete CHECK ((status = 'Fulfilled') = (fulfilled_at IS NOT NULL)),
    CONSTRAINT privacy_request_rejected_explained CHECK (status <> 'Rejected' OR rejection_reason IS NOT NULL)
);

CREATE TABLE guest.guest_magic_link (
    guest_magic_link_id            uuid NOT NULL DEFAULT core.uuid_v7(),
    tenant_id                      uuid NOT NULL,
    guest_id                       uuid NOT NULL,
    principal_id                   uuid NOT NULL,
    guest_contact_point_id         uuid NOT NULL,
    token_hash                     bytea NOT NULL,
    purpose                        text NOT NULL,
    scope_entity_type              text,
    scope_entity_id                uuid,
    issued_at                      timestamptz NOT NULL DEFAULT now(),
    expires_at                     timestamptz NOT NULL,
    consumed_at                    timestamptz,
    revoked_at                     timestamptz,
    created_at                     timestamptz NOT NULL DEFAULT now(),
    created_by                     uuid,
    updated_at                     timestamptz NOT NULL DEFAULT now(),
    updated_by                     uuid,
    correlation_id                 text,
    CONSTRAINT guest_magic_link_pkey PRIMARY KEY (guest_magic_link_id),
    CONSTRAINT guest_magic_link_token_hash_ck CHECK (octet_length(token_hash) = 32),
    CONSTRAINT guest_magic_link_purpose_ck CHECK (purpose IN ('SignIn', 'ManageBooking', 'CompleteIntake', 'Pay')),
    CONSTRAINT guest_magic_link_tenant_identity_uq UNIQUE (tenant_id, guest_magic_link_id),
    CONSTRAINT guest_magic_link_expiry_forward CHECK (expires_at > issued_at),
    CONSTRAINT guest_magic_link_scope_pair CHECK ((scope_entity_type IS NULL) = (scope_entity_id IS NULL)),
    CONSTRAINT guest_magic_link_token_uq UNIQUE (token_hash)
);
COMMENT ON TABLE guest.guest_magic_link IS 'Only the SHA-256 of the token is stored. Single use: guest.resolve_magic_link consumes it atomically. [SEC-010 (signed, short-lived, revocable, purpose-limited); SEC-011]';

ALTER TABLE guest.guest ADD CONSTRAINT guest_principal_id_fk FOREIGN KEY (tenant_id, principal_id) REFERENCES core.principal (tenant_id, principal_id) ON DELETE RESTRICT;
CREATE INDEX guest_principal_id_ix ON guest.guest (tenant_id, principal_id);
ALTER TABLE guest.guest ADD CONSTRAINT guest_home_property_id_fk FOREIGN KEY (tenant_id, home_property_id) REFERENCES core.property (tenant_id, property_id) ON DELETE RESTRICT;
CREATE INDEX guest_home_property_id_ix ON guest.guest (tenant_id, home_property_id);
ALTER TABLE guest.guest ADD CONSTRAINT guest_merged_into_guest_id_fk FOREIGN KEY (tenant_id, merged_into_guest_id) REFERENCES guest.guest (tenant_id, guest_id) ON DELETE RESTRICT;
CREATE INDEX guest_merged_into_guest_id_ix ON guest.guest (tenant_id, merged_into_guest_id);
ALTER TABLE guest.guest ADD CONSTRAINT guest_tenant_fk FOREIGN KEY (tenant_id) REFERENCES core.tenant (tenant_id);
ALTER TABLE guest.guest_contact_point ADD CONSTRAINT guest_contact_point_guest_id_fk FOREIGN KEY (tenant_id, guest_id) REFERENCES guest.guest (tenant_id, guest_id) ON DELETE RESTRICT;
CREATE INDEX guest_contact_point_guest_id_ix ON guest.guest_contact_point (tenant_id, guest_id);
ALTER TABLE guest.guest_contact_point ADD CONSTRAINT guest_contact_point_tenant_fk FOREIGN KEY (tenant_id) REFERENCES core.tenant (tenant_id);
ALTER TABLE guest.guest_relationship ADD CONSTRAINT guest_relationship_guest_id_fk FOREIGN KEY (tenant_id, guest_id) REFERENCES guest.guest (tenant_id, guest_id) ON DELETE RESTRICT;
CREATE INDEX guest_relationship_guest_id_ix ON guest.guest_relationship (tenant_id, guest_id);
ALTER TABLE guest.guest_relationship ADD CONSTRAINT guest_relationship_related_guest_id_fk FOREIGN KEY (tenant_id, related_guest_id) REFERENCES guest.guest (tenant_id, guest_id) ON DELETE RESTRICT;
CREATE INDEX guest_relationship_related_guest_id_ix ON guest.guest_relationship (tenant_id, related_guest_id);
ALTER TABLE guest.guest_relationship ADD CONSTRAINT guest_relationship_tenant_fk FOREIGN KEY (tenant_id) REFERENCES core.tenant (tenant_id);
ALTER TABLE guest.guest_merge_case ADD CONSTRAINT guest_merge_case_surviving_guest_id_fk FOREIGN KEY (tenant_id, surviving_guest_id) REFERENCES guest.guest (tenant_id, guest_id) ON DELETE RESTRICT;
CREATE INDEX guest_merge_case_surviving_guest_id_ix ON guest.guest_merge_case (tenant_id, surviving_guest_id);
ALTER TABLE guest.guest_merge_case ADD CONSTRAINT guest_merge_case_duplicate_guest_id_fk FOREIGN KEY (tenant_id, duplicate_guest_id) REFERENCES guest.guest (tenant_id, guest_id) ON DELETE RESTRICT;
CREATE INDEX guest_merge_case_duplicate_guest_id_ix ON guest.guest_merge_case (tenant_id, duplicate_guest_id);
ALTER TABLE guest.guest_merge_case ADD CONSTRAINT guest_merge_case_tenant_fk FOREIGN KEY (tenant_id) REFERENCES core.tenant (tenant_id);
ALTER TABLE guest.delegated_authority ADD CONSTRAINT delegated_authority_guest_id_fk FOREIGN KEY (tenant_id, guest_id) REFERENCES guest.guest (tenant_id, guest_id) ON DELETE RESTRICT;
CREATE INDEX delegated_authority_guest_id_ix ON guest.delegated_authority (tenant_id, guest_id);
ALTER TABLE guest.delegated_authority ADD CONSTRAINT delegated_authority_delegate_guest_id_fk FOREIGN KEY (tenant_id, delegate_guest_id) REFERENCES guest.guest (tenant_id, guest_id) ON DELETE RESTRICT;
CREATE INDEX delegated_authority_delegate_guest_id_ix ON guest.delegated_authority (tenant_id, delegate_guest_id);
ALTER TABLE guest.delegated_authority ADD CONSTRAINT delegated_authority_delegate_principal_id_fk FOREIGN KEY (tenant_id, delegate_principal_id) REFERENCES core.principal (tenant_id, principal_id) ON DELETE RESTRICT;
CREATE INDEX delegated_authority_delegate_principal_id_ix ON guest.delegated_authority (tenant_id, delegate_principal_id);
ALTER TABLE guest.delegated_authority ADD CONSTRAINT delegated_authority_tenant_fk FOREIGN KEY (tenant_id) REFERENCES core.tenant (tenant_id);
ALTER TABLE guest.consent_record ADD CONSTRAINT consent_record_guest_id_fk FOREIGN KEY (tenant_id, guest_id) REFERENCES guest.guest (tenant_id, guest_id) ON DELETE RESTRICT;
CREATE INDEX consent_record_guest_id_ix ON guest.consent_record (tenant_id, guest_id);
ALTER TABLE guest.consent_record ADD CONSTRAINT consent_record_granted_by_guest_id_fk FOREIGN KEY (tenant_id, granted_by_guest_id) REFERENCES guest.guest (tenant_id, guest_id) ON DELETE RESTRICT;
CREATE INDEX consent_record_granted_by_guest_id_ix ON guest.consent_record (tenant_id, granted_by_guest_id);
CREATE INDEX consent_record_scope_ix ON guest.consent_record (tenant_id, property_id);
ALTER TABLE guest.consent_record ADD CONSTRAINT consent_record_tenant_fk FOREIGN KEY (tenant_id) REFERENCES core.tenant (tenant_id);
ALTER TABLE guest.consent_record ADD CONSTRAINT consent_record_property_fk FOREIGN KEY (tenant_id, property_id) REFERENCES core.property (tenant_id, property_id);
ALTER TABLE guest.privacy_request ADD CONSTRAINT privacy_request_guest_id_fk FOREIGN KEY (tenant_id, guest_id) REFERENCES guest.guest (tenant_id, guest_id) ON DELETE RESTRICT;
CREATE INDEX privacy_request_guest_id_ix ON guest.privacy_request (tenant_id, guest_id);
ALTER TABLE guest.privacy_request ADD CONSTRAINT privacy_request_tenant_fk FOREIGN KEY (tenant_id) REFERENCES core.tenant (tenant_id);
ALTER TABLE guest.guest_magic_link ADD CONSTRAINT guest_magic_link_guest_id_fk FOREIGN KEY (tenant_id, guest_id) REFERENCES guest.guest (tenant_id, guest_id) ON DELETE RESTRICT;
CREATE INDEX guest_magic_link_guest_id_ix ON guest.guest_magic_link (tenant_id, guest_id);
ALTER TABLE guest.guest_magic_link ADD CONSTRAINT guest_magic_link_principal_id_fk FOREIGN KEY (tenant_id, principal_id) REFERENCES core.principal (tenant_id, principal_id) ON DELETE RESTRICT;
CREATE INDEX guest_magic_link_principal_id_ix ON guest.guest_magic_link (tenant_id, principal_id);
ALTER TABLE guest.guest_magic_link ADD CONSTRAINT guest_magic_link_guest_contact_point_id_fk FOREIGN KEY (tenant_id, guest_contact_point_id) REFERENCES guest.guest_contact_point (tenant_id, guest_contact_point_id) ON DELETE RESTRICT;
CREATE INDEX guest_magic_link_guest_contact_point_id_ix ON guest.guest_magic_link (tenant_id, guest_contact_point_id);
ALTER TABLE guest.guest_magic_link ADD CONSTRAINT guest_magic_link_tenant_fk FOREIGN KEY (tenant_id) REFERENCES core.tenant (tenant_id);

CREATE TRIGGER guest_touch BEFORE UPDATE ON guest.guest FOR EACH ROW EXECUTE FUNCTION core.touch_versioned();
CREATE TRIGGER guest_contact_point_touch BEFORE UPDATE ON guest.guest_contact_point FOR EACH ROW EXECUTE FUNCTION core.touch_versioned();
CREATE TRIGGER guest_relationship_touch BEFORE UPDATE ON guest.guest_relationship FOR EACH ROW EXECUTE FUNCTION core.touch_versioned();
CREATE TRIGGER guest_merge_case_touch BEFORE UPDATE ON guest.guest_merge_case FOR EACH ROW EXECUTE FUNCTION core.touch_versioned();
CREATE TRIGGER delegated_authority_touch BEFORE UPDATE ON guest.delegated_authority FOR EACH ROW EXECUTE FUNCTION core.touch_versioned();
CREATE TRIGGER consent_record_touch BEFORE UPDATE ON guest.consent_record FOR EACH ROW EXECUTE FUNCTION core.touch_versioned();
CREATE TRIGGER privacy_request_touch BEFORE UPDATE ON guest.privacy_request FOR EACH ROW EXECUTE FUNCTION core.touch_versioned();
CREATE TRIGGER guest_magic_link_touch BEFORE UPDATE ON guest.guest_magic_link FOR EACH ROW EXECUTE FUNCTION core.touch();
CREATE INDEX guest_name_trgm_ix ON guest.guest USING gin ((coalesce(legal_last_name, '') || ' ' || coalesce(legal_first_name, '') || ' ' || coalesce(preferred_name, '')) gin_trgm_ops) WHERE status IN ('Active', 'Restricted');
CREATE UNIQUE INDEX guest_public_queue_id_uq ON guest.guest (tenant_id, public_queue_id) WHERE public_queue_id IS NOT NULL;
CREATE INDEX guest_contact_point_lookup_ix ON guest.guest_contact_point (tenant_id, contact_type, lookup_hash) WHERE status <> 'Retired';
CREATE UNIQUE INDEX guest_contact_point_primary_uq ON guest.guest_contact_point (tenant_id, guest_id, contact_type) WHERE is_primary AND status = 'Active';

ALTER TABLE guest.guest_relationship ADD CONSTRAINT guest_relationship_no_overlap
    EXCLUDE USING gist (tenant_id WITH =, guest_id WITH =, related_guest_id WITH =, relationship_type WITH =,
                        tstzrange(effective_from, coalesce(effective_to, 'infinity'), '[)') WITH &&)
    WHERE (status = 'Active');
CREATE INDEX consent_record_purpose_ix ON guest.consent_record (tenant_id, guest_id, purpose, channel) WHERE status = 'Active';

CREATE FUNCTION guest.consent_record_immutable() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    IF (NEW.guest_id, NEW.granted_by_guest_id, NEW.purpose, NEW.channel, NEW.template_id, NEW.template_version,
        NEW.evidence_cipher, NEW.key_version, NEW.effective_at, NEW.property_id, NEW.tenant_id)
       IS DISTINCT FROM
       (OLD.guest_id, OLD.granted_by_guest_id, OLD.purpose, OLD.channel, OLD.template_id, OLD.template_version,
        OLD.evidence_cipher, OLD.key_version, OLD.effective_at, OLD.property_id, OLD.tenant_id)
       AND current_setting('spms.redacting', true) IS DISTINCT FROM 'on' THEN
        RAISE EXCEPTION 'guest.consent_record evidence is immutable; revoke and record a new consent'
            USING ERRCODE = '42501';
    END IF;
    RETURN NEW;
END $$;
CREATE TRIGGER consent_record_immutable BEFORE UPDATE ON guest.consent_record
    FOR EACH ROW EXECUTE FUNCTION guest.consent_record_immutable();
CREATE INDEX guest_magic_link_expiry_ix ON guest.guest_magic_link (expires_at) WHERE consumed_at IS NULL;
