-- 08 visit: generated by database/tools/generate.py from database/model/. Do not edit.
-- may reference: catalog, core, guest, resources, scheduling, workforce

CREATE SCHEMA IF NOT EXISTS visit AUTHORIZATION spms_owner;

CREATE TABLE visit.visit (
    visit_id                       uuid NOT NULL DEFAULT core.uuid_v7(),
    tenant_id                      uuid NOT NULL,
    property_id                    uuid NOT NULL,
    visit_type                     text NOT NULL,
    primary_guest_id               uuid,
    operating_mode                 text NOT NULL,
    scheduled_arrival_at           timestamptz,
    scheduled_departure_at         timestamptz,
    actual_arrival_at              timestamptz,
    actual_departure_at            timestamptz,
    opened_at                      timestamptz NOT NULL DEFAULT now(),
    closed_at                      timestamptz,
    status                         text NOT NULL DEFAULT 'Expected',
    source_system                  text NOT NULL DEFAULT 'Spa',
    source_key                     text,
    version                        integer NOT NULL DEFAULT 1,
    created_at                     timestamptz NOT NULL DEFAULT now(),
    created_by                     uuid,
    updated_at                     timestamptz NOT NULL DEFAULT now(),
    updated_by                     uuid,
    correlation_id                 text,
    CONSTRAINT visit_pkey PRIMARY KEY (visit_id),
    CONSTRAINT visit_visit_type_ck CHECK (visit_type IN ('DayGuest', 'HotelGuest', 'Member', 'Group', 'WalkIn')),
    CONSTRAINT visit_operating_mode_ck CHECK (operating_mode IN ('Standalone', 'MarqueeIntegrated')),
    CONSTRAINT visit_version_ck CHECK (version >= 1),
    CONSTRAINT visit_tenant_identity_uq UNIQUE (tenant_id, visit_id),
    CONSTRAINT visit_prop_ref_uq UNIQUE (tenant_id, property_id, visit_id),
    CONSTRAINT visit_status_known CHECK (status IN ('Expected', 'Arrived', 'InProgress', 'Closed', 'Cancelled', 'NoShow')),
    CONSTRAINT visit_closed_complete CHECK ((status = 'Closed') = (closed_at IS NOT NULL))
);
COMMENT ON COLUMN visit.visit.operating_mode IS 'frozen at open: the mode this visit was operated under';

CREATE TABLE visit.visit_appointment (
    visit_appointment_id           uuid NOT NULL DEFAULT core.uuid_v7(),
    tenant_id                      uuid NOT NULL,
    property_id                    uuid NOT NULL,
    visit_id                       uuid NOT NULL,
    appointment_id                 uuid NOT NULL,
    created_at                     timestamptz NOT NULL DEFAULT now(),
    created_by                     uuid,
    updated_at                     timestamptz NOT NULL DEFAULT now(),
    updated_by                     uuid,
    correlation_id                 text,
    CONSTRAINT visit_appointment_pkey PRIMARY KEY (visit_appointment_id),
    CONSTRAINT visit_appointment_tenant_identity_uq UNIQUE (tenant_id, visit_appointment_id),
    CONSTRAINT visit_appointment_appointment_uq UNIQUE (tenant_id, appointment_id)
);

CREATE TABLE visit.visit_participant (
    visit_participant_id           uuid NOT NULL DEFAULT core.uuid_v7(),
    tenant_id                      uuid NOT NULL,
    property_id                    uuid NOT NULL,
    visit_id                       uuid NOT NULL,
    guest_id                       uuid NOT NULL,
    participant_role               text NOT NULL,
    arrival_state                  text NOT NULL DEFAULT 'Expected',
    checked_in_at                  timestamptz,
    checked_in_by_staff_id         uuid,
    checked_out_at                 timestamptz,
    created_at                     timestamptz NOT NULL DEFAULT now(),
    created_by                     uuid,
    updated_at                     timestamptz NOT NULL DEFAULT now(),
    updated_by                     uuid,
    correlation_id                 text,
    CONSTRAINT visit_participant_pkey PRIMARY KEY (visit_participant_id),
    CONSTRAINT visit_participant_participant_role_ck CHECK (participant_role IN ('Primary', 'Companion', 'Minor', 'Guardian')),
    CONSTRAINT visit_participant_arrival_state_ck CHECK (arrival_state IN ('Expected', 'Arrived', 'Departed', 'NoShow')),
    CONSTRAINT visit_participant_tenant_identity_uq UNIQUE (tenant_id, visit_participant_id),
    CONSTRAINT visit_participant_prop_ref_uq UNIQUE (tenant_id, property_id, visit_participant_id),
    CONSTRAINT visit_participant_guest_uq UNIQUE (tenant_id, visit_id, guest_id)
);

CREATE TABLE visit.visit_event (
    visit_event_id                 uuid NOT NULL DEFAULT core.uuid_v7(),
    tenant_id                      uuid NOT NULL,
    property_id                    uuid NOT NULL,
    visit_id                       uuid NOT NULL,
    visit_participant_id           uuid,
    event_type                     text NOT NULL,
    prior_state                    text,
    new_state                      text,
    reason_code                    text,
    occurred_at                    timestamptz NOT NULL,
    performed_by_staff_id          uuid,
    evidence_reference             text,
    details                        jsonb,
    created_at                     timestamptz NOT NULL DEFAULT now(),
    created_by                     uuid,
    correlation_id                 text,
    CONSTRAINT visit_event_pkey PRIMARY KEY (visit_event_id),
    CONSTRAINT visit_event_event_type_ck CHECK (event_type IN ('Opened', 'Arrived', 'CheckedIn', 'CredentialIssued', 'CredentialReturned', 'Departed', 'Closed', 'Reopened', 'ExceptionRaised', 'ExceptionResolved')),
    CONSTRAINT visit_event_tenant_identity_uq UNIQUE (tenant_id, visit_event_id)
);

CREATE TABLE visit.visit_exception (
    visit_exception_id             uuid NOT NULL DEFAULT core.uuid_v7(),
    tenant_id                      uuid NOT NULL,
    property_id                    uuid NOT NULL,
    visit_id                       uuid NOT NULL,
    visit_participant_id           uuid,
    exception_type                 text NOT NULL,
    severity                       text NOT NULL,
    resolved_at                    timestamptz,
    resolved_by_staff_id           uuid,
    resolution_note                text,
    status                         text NOT NULL DEFAULT 'Open',
    version                        integer NOT NULL DEFAULT 1,
    created_at                     timestamptz NOT NULL DEFAULT now(),
    created_by                     uuid,
    updated_at                     timestamptz NOT NULL DEFAULT now(),
    updated_by                     uuid,
    correlation_id                 text,
    CONSTRAINT visit_exception_pkey PRIMARY KEY (visit_exception_id),
    CONSTRAINT visit_exception_exception_type_ck CHECK (exception_type IN ('PaymentOutstanding', 'IntakeIncomplete', 'IdentityMismatch', 'CredentialFailed', 'AccessFailed', 'ConsentMissing', 'Other')),
    CONSTRAINT visit_exception_severity_ck CHECK (severity IN ('Info', 'Warning', 'Blocking')),
    CONSTRAINT visit_exception_version_ck CHECK (version >= 1),
    CONSTRAINT visit_exception_tenant_identity_uq UNIQUE (tenant_id, visit_exception_id),
    CONSTRAINT visit_exception_status_known CHECK (status IN ('Open', 'Resolved', 'Waived')),
    CONSTRAINT visit_exception_resolution_complete CHECK ((status = 'Open') = (resolved_at IS NULL))
);

ALTER TABLE visit.visit ADD CONSTRAINT visit_primary_guest_id_fk FOREIGN KEY (tenant_id, primary_guest_id) REFERENCES guest.guest (tenant_id, guest_id) ON DELETE RESTRICT;
CREATE INDEX visit_primary_guest_id_ix ON visit.visit (tenant_id, primary_guest_id);
ALTER TABLE visit.visit ADD CONSTRAINT visit_tenant_fk FOREIGN KEY (tenant_id) REFERENCES core.tenant (tenant_id);
ALTER TABLE visit.visit ADD CONSTRAINT visit_property_fk FOREIGN KEY (tenant_id, property_id) REFERENCES core.property (tenant_id, property_id);
ALTER TABLE visit.visit_appointment ADD CONSTRAINT visit_appointment_visit_id_fk FOREIGN KEY (tenant_id, property_id, visit_id) REFERENCES visit.visit (tenant_id, property_id, visit_id) ON DELETE RESTRICT;
CREATE INDEX visit_appointment_visit_id_ix ON visit.visit_appointment (tenant_id, property_id, visit_id);
ALTER TABLE visit.visit_appointment ADD CONSTRAINT visit_appointment_appointment_id_fk FOREIGN KEY (tenant_id, property_id, appointment_id) REFERENCES scheduling.appointment (tenant_id, property_id, appointment_id) ON DELETE RESTRICT;
CREATE INDEX visit_appointment_appointment_id_ix ON visit.visit_appointment (tenant_id, property_id, appointment_id);
ALTER TABLE visit.visit_appointment ADD CONSTRAINT visit_appointment_tenant_fk FOREIGN KEY (tenant_id) REFERENCES core.tenant (tenant_id);
ALTER TABLE visit.visit_appointment ADD CONSTRAINT visit_appointment_property_fk FOREIGN KEY (tenant_id, property_id) REFERENCES core.property (tenant_id, property_id);
ALTER TABLE visit.visit_participant ADD CONSTRAINT visit_participant_visit_id_fk FOREIGN KEY (tenant_id, property_id, visit_id) REFERENCES visit.visit (tenant_id, property_id, visit_id) ON DELETE RESTRICT;
CREATE INDEX visit_participant_visit_id_ix ON visit.visit_participant (tenant_id, property_id, visit_id);
ALTER TABLE visit.visit_participant ADD CONSTRAINT visit_participant_guest_id_fk FOREIGN KEY (tenant_id, guest_id) REFERENCES guest.guest (tenant_id, guest_id) ON DELETE RESTRICT;
CREATE INDEX visit_participant_guest_id_ix ON visit.visit_participant (tenant_id, guest_id);
ALTER TABLE visit.visit_participant ADD CONSTRAINT visit_participant_checked_in_by_staff_id_fk FOREIGN KEY (tenant_id, checked_in_by_staff_id) REFERENCES workforce.staff (tenant_id, staff_id) ON DELETE RESTRICT;
CREATE INDEX visit_participant_checked_in_by_staff_id_ix ON visit.visit_participant (tenant_id, checked_in_by_staff_id);
ALTER TABLE visit.visit_participant ADD CONSTRAINT visit_participant_tenant_fk FOREIGN KEY (tenant_id) REFERENCES core.tenant (tenant_id);
ALTER TABLE visit.visit_participant ADD CONSTRAINT visit_participant_property_fk FOREIGN KEY (tenant_id, property_id) REFERENCES core.property (tenant_id, property_id);
ALTER TABLE visit.visit_event ADD CONSTRAINT visit_event_visit_id_fk FOREIGN KEY (tenant_id, property_id, visit_id) REFERENCES visit.visit (tenant_id, property_id, visit_id) ON DELETE RESTRICT;
CREATE INDEX visit_event_visit_id_ix ON visit.visit_event (tenant_id, property_id, visit_id);
ALTER TABLE visit.visit_event ADD CONSTRAINT visit_event_visit_participant_id_fk FOREIGN KEY (tenant_id, property_id, visit_participant_id) REFERENCES visit.visit_participant (tenant_id, property_id, visit_participant_id) ON DELETE RESTRICT;
CREATE INDEX visit_event_visit_participant_id_ix ON visit.visit_event (tenant_id, property_id, visit_participant_id);
ALTER TABLE visit.visit_event ADD CONSTRAINT visit_event_performed_by_staff_id_fk FOREIGN KEY (tenant_id, performed_by_staff_id) REFERENCES workforce.staff (tenant_id, staff_id) ON DELETE RESTRICT;
CREATE INDEX visit_event_performed_by_staff_id_ix ON visit.visit_event (tenant_id, performed_by_staff_id);
ALTER TABLE visit.visit_event ADD CONSTRAINT visit_event_tenant_fk FOREIGN KEY (tenant_id) REFERENCES core.tenant (tenant_id);
ALTER TABLE visit.visit_event ADD CONSTRAINT visit_event_property_fk FOREIGN KEY (tenant_id, property_id) REFERENCES core.property (tenant_id, property_id);
ALTER TABLE visit.visit_exception ADD CONSTRAINT visit_exception_visit_id_fk FOREIGN KEY (tenant_id, property_id, visit_id) REFERENCES visit.visit (tenant_id, property_id, visit_id) ON DELETE RESTRICT;
CREATE INDEX visit_exception_visit_id_ix ON visit.visit_exception (tenant_id, property_id, visit_id);
ALTER TABLE visit.visit_exception ADD CONSTRAINT visit_exception_visit_participant_id_fk FOREIGN KEY (tenant_id, property_id, visit_participant_id) REFERENCES visit.visit_participant (tenant_id, property_id, visit_participant_id) ON DELETE RESTRICT;
CREATE INDEX visit_exception_visit_participant_id_ix ON visit.visit_exception (tenant_id, property_id, visit_participant_id);
ALTER TABLE visit.visit_exception ADD CONSTRAINT visit_exception_resolved_by_staff_id_fk FOREIGN KEY (tenant_id, resolved_by_staff_id) REFERENCES workforce.staff (tenant_id, staff_id) ON DELETE RESTRICT;
CREATE INDEX visit_exception_resolved_by_staff_id_ix ON visit.visit_exception (tenant_id, resolved_by_staff_id);
ALTER TABLE visit.visit_exception ADD CONSTRAINT visit_exception_tenant_fk FOREIGN KEY (tenant_id) REFERENCES core.tenant (tenant_id);
ALTER TABLE visit.visit_exception ADD CONSTRAINT visit_exception_property_fk FOREIGN KEY (tenant_id, property_id) REFERENCES core.property (tenant_id, property_id);

CREATE TRIGGER visit_touch BEFORE UPDATE ON visit.visit FOR EACH ROW EXECUTE FUNCTION core.touch_versioned();
CREATE TRIGGER visit_appointment_touch BEFORE UPDATE ON visit.visit_appointment FOR EACH ROW EXECUTE FUNCTION core.touch();
CREATE TRIGGER visit_participant_touch BEFORE UPDATE ON visit.visit_participant FOR EACH ROW EXECUTE FUNCTION core.touch();
CREATE TRIGGER visit_event_append_only BEFORE UPDATE OR DELETE ON visit.visit_event FOR EACH ROW EXECUTE FUNCTION core.forbid_mutation();
CREATE TRIGGER visit_exception_touch BEFORE UPDATE ON visit.visit_exception FOR EACH ROW EXECUTE FUNCTION core.touch_versioned();
CREATE INDEX visit_day_ix ON visit.visit (tenant_id, property_id, scheduled_arrival_at);
CREATE INDEX visit_event_visit_ix ON visit.visit_event (tenant_id, visit_id, occurred_at);
CREATE INDEX visit_exception_open_ix ON visit.visit_exception (tenant_id, property_id, severity) WHERE status = 'Open';
