-- 08 inventory: generated by database/tools/generate.py from database/model/. Do not edit.
-- may reference: catalog, core, guest, resources, scheduling, workforce

CREATE SCHEMA IF NOT EXISTS inventory AUTHORIZATION spms_owner;

CREATE TABLE inventory.inventory_item (
    inventory_item_id              uuid NOT NULL DEFAULT core.uuid_v7(),
    tenant_id                      uuid NOT NULL,
    item_code                      text NOT NULL,
    item_name                      text NOT NULL,
    item_kind                      text NOT NULL,
    tracking_method                text NOT NULL DEFAULT 'Quantity',
    base_uom                       text NOT NULL DEFAULT 'ea',
    category_code                  text,
    brand_name                     text,
    reorder_point                  numeric(18,6) NOT NULL DEFAULT 0,
    maximum_stock                  numeric(18,6),
    lead_time_days                 integer NOT NULL DEFAULT 0,
    status                         text NOT NULL DEFAULT 'Active',
    effective_from                 timestamptz NOT NULL DEFAULT now(),
    effective_to                   timestamptz,
    source_system                  text NOT NULL DEFAULT 'Spa',
    source_key                     text,
    version                        integer NOT NULL DEFAULT 1,
    created_at                     timestamptz NOT NULL DEFAULT now(),
    created_by                     uuid,
    updated_at                     timestamptz NOT NULL DEFAULT now(),
    updated_by                     uuid,
    correlation_id                 text,
    CONSTRAINT inventory_item_pkey PRIMARY KEY (inventory_item_id),
    CONSTRAINT inventory_item_item_kind_ck CHECK (item_kind IN ('Retail', 'Linen', 'Amenity', 'Consumable', 'Professional')),
    CONSTRAINT inventory_item_tracking_method_ck CHECK (tracking_method IN ('Quantity', 'Lot')),
    CONSTRAINT inventory_item_reorder_point_ck CHECK (reorder_point >= 0),
    CONSTRAINT inventory_item_lead_time_days_ck CHECK (lead_time_days >= 0),
    CONSTRAINT inventory_item_version_ck CHECK (version >= 1),
    CONSTRAINT inventory_item_tenant_identity_uq UNIQUE (tenant_id, inventory_item_id),
    CONSTRAINT inventory_item_status_known CHECK (status IN ('Active', 'Inactive', 'Retired')),
    CONSTRAINT inventory_item_effective_range_ck CHECK (effective_to IS NULL OR effective_to > effective_from),
    CONSTRAINT inventory_item_code_uq UNIQUE (tenant_id, item_code)
);
COMMENT ON COLUMN inventory.inventory_item.category_code IS 'code_list ItemCategory';

CREATE TABLE inventory.inventory_item_variant (
    inventory_item_variant_id      uuid NOT NULL DEFAULT core.uuid_v7(),
    tenant_id                      uuid NOT NULL,
    inventory_item_id              uuid NOT NULL,
    variant_code                   text NOT NULL,
    barcode                        text,
    size_code                      text,
    color_code                     text,
    base_uom                       text NOT NULL DEFAULT 'ea',
    sell_price_minor               bigint,
    currency_code                  char(3),
    tax_code                       text,
    inventory_enabled              boolean NOT NULL DEFAULT true,
    status                         text NOT NULL DEFAULT 'Active',
    effective_from                 timestamptz NOT NULL DEFAULT now(),
    effective_to                   timestamptz,
    source_system                  text NOT NULL DEFAULT 'Spa',
    source_key                     text,
    version                        integer NOT NULL DEFAULT 1,
    created_at                     timestamptz NOT NULL DEFAULT now(),
    created_by                     uuid,
    updated_at                     timestamptz NOT NULL DEFAULT now(),
    updated_by                     uuid,
    correlation_id                 text,
    CONSTRAINT inventory_item_variant_pkey PRIMARY KEY (inventory_item_variant_id),
    CONSTRAINT inventory_item_variant_sell_price_minor_ck CHECK (sell_price_minor >= 0),
    CONSTRAINT inventory_item_variant_currency_code_ck CHECK (currency_code ~ '^[A-Z]{3}$'),
    CONSTRAINT inventory_item_variant_version_ck CHECK (version >= 1),
    CONSTRAINT inventory_item_variant_tenant_identity_uq UNIQUE (tenant_id, inventory_item_variant_id),
    CONSTRAINT inventory_item_variant_status_known CHECK (status IN ('Active', 'Inactive', 'Retired')),
    CONSTRAINT inventory_item_variant_effective_range_ck CHECK (effective_to IS NULL OR effective_to > effective_from),
    CONSTRAINT inventory_item_variant_price_has_currency CHECK ((sell_price_minor IS NULL) = (currency_code IS NULL)),
    CONSTRAINT inventory_item_variant_code_uq UNIQUE (tenant_id, variant_code)
);
COMMENT ON TABLE inventory.inventory_item_variant IS 'The stock-keeping and selling unit. A retail sale references the variant and its price.';
COMMENT ON COLUMN inventory.inventory_item_variant.barcode IS 'GTIN/UPC as text; leading zeros are significant';
COMMENT ON COLUMN inventory.inventory_item_variant.sell_price_minor IS 'NULL = not sold';

CREATE TABLE inventory.inventory_location_balance (
    inventory_location_balance_id  uuid NOT NULL DEFAULT core.uuid_v7(),
    tenant_id                      uuid NOT NULL,
    property_id                    uuid NOT NULL,
    inventory_item_variant_id      uuid NOT NULL,
    location_id                    uuid NOT NULL,
    lot_number                     text,
    stock_state                    text NOT NULL DEFAULT 'Saleable',
    on_hand                        numeric(18,6) NOT NULL DEFAULT 0,
    allocated                      numeric(18,6) NOT NULL DEFAULT 0,
    available                      numeric(18,6) GENERATED ALWAYS AS (on_hand - allocated) STORED NOT NULL,
    unit_cost_minor                numeric(24,6) NOT NULL DEFAULT 0,
    created_at                     timestamptz NOT NULL DEFAULT now(),
    created_by                     uuid,
    updated_at                     timestamptz NOT NULL DEFAULT now(),
    updated_by                     uuid,
    correlation_id                 text,
    CONSTRAINT inventory_location_balance_pkey PRIMARY KEY (inventory_location_balance_id),
    CONSTRAINT inventory_location_balance_stock_state_ck CHECK (stock_state IN ('Saleable', 'Clean', 'Soiled', 'InLaundry', 'Damaged', 'Quarantine')),
    CONSTRAINT inventory_location_balance_allocated_ck CHECK (allocated >= 0),
    CONSTRAINT inventory_location_balance_unit_cost_minor_ck CHECK (unit_cost_minor >= 0),
    CONSTRAINT inventory_location_balance_tenant_identity_uq UNIQUE (tenant_id, inventory_location_balance_id),
    CONSTRAINT inventory_location_balance_grain_uq UNIQUE NULLS NOT DISTINCT (tenant_id, property_id, inventory_item_variant_id, location_id, lot_number, stock_state)
);
COMMENT ON TABLE inventory.inventory_location_balance IS 'Projection of the ledger, updated in the same transaction as each ledger entry.';

CREATE TABLE inventory.inventory_ledger_entry (
    entry_id                       uuid NOT NULL DEFAULT core.uuid_v7(),
    tenant_id                      uuid NOT NULL,
    property_id                    uuid NOT NULL,
    inventory_item_variant_id      uuid NOT NULL,
    location_id                    uuid NOT NULL,
    lot_number                     text,
    stock_state                    text NOT NULL,
    movement_type                  text NOT NULL,
    quantity                       numeric(18,6) NOT NULL,
    unit_cost_minor                numeric(24,6),
    value_delta_minor              numeric(24,6),
    reason_code                    text,
    original_entry_id              uuid,
    source_document_type           text,
    source_document_id             uuid,
    owner_system                   text NOT NULL DEFAULT 'Spa',
    idempotency_key                text NOT NULL,
    occurred_at                    timestamptz NOT NULL DEFAULT now(),
    created_by                     uuid,
    correlation_id                 text,
    CONSTRAINT inventory_ledger_entry_pkey PRIMARY KEY (entry_id, occurred_at),
    CONSTRAINT inventory_ledger_entry_stock_state_ck CHECK (stock_state IN ('Saleable', 'Clean', 'Soiled', 'InLaundry', 'Damaged', 'Quarantine')),
    CONSTRAINT inventory_ledger_entry_movement_type_ck CHECK (movement_type IN ('Receipt', 'Issue', 'Sale', 'Return', 'Adjustment', 'TransferOut', 'TransferIn', 'LaundryOut', 'LaundryIn', 'LaundryLoss', 'Consumption', 'CountVariance', 'StateChange', 'Reversal')),
    CONSTRAINT inventory_ledger_entry_quantity_ck CHECK (quantity <> 0),
    CONSTRAINT inventory_ledger_entry_source_document_type_ck CHECK (source_document_type IN ('Appointment', 'OrderLine', 'LaundryBatch', 'StockCount', 'Transfer', 'Receipt')),
    CONSTRAINT inventory_ledger_entry_owner_system_ck CHECK (owner_system IN ('Spa', 'Marquee', 'Pos', 'External')),
    CONSTRAINT inventory_ledger_entry_reversal_has_target CHECK ((movement_type = 'Reversal') = (original_entry_id IS NOT NULL)),
    CONSTRAINT inventory_ledger_entry_source_pair CHECK ((source_document_type IS NULL) = (source_document_id IS NULL))
) PARTITION BY RANGE (occurred_at);
COMMENT ON TABLE inventory.inventory_ledger_entry IS 'Signed stock movements. Never updated: a correction is a reversing entry (original_entry_id). [§Stock grain and posting; §Numbers and six decimal places]';
COMMENT ON COLUMN inventory.inventory_ledger_entry.original_entry_id IS 'reversal target (no FK: partitioned)';

CREATE TABLE inventory.laundry_batch (
    laundry_batch_id               uuid NOT NULL DEFAULT core.uuid_v7(),
    tenant_id                      uuid NOT NULL,
    property_id                    uuid NOT NULL,
    dispatch_location_id           uuid NOT NULL,
    return_location_id             uuid NOT NULL,
    dispatched_at                  timestamptz,
    expected_return_at             timestamptz,
    received_at                    timestamptz,
    supplier_reference             text,
    status                         text NOT NULL DEFAULT 'Draft',
    version                        integer NOT NULL DEFAULT 1,
    created_at                     timestamptz NOT NULL DEFAULT now(),
    created_by                     uuid,
    updated_at                     timestamptz NOT NULL DEFAULT now(),
    updated_by                     uuid,
    correlation_id                 text,
    CONSTRAINT laundry_batch_pkey PRIMARY KEY (laundry_batch_id),
    CONSTRAINT laundry_batch_version_ck CHECK (version >= 1),
    CONSTRAINT laundry_batch_tenant_identity_uq UNIQUE (tenant_id, laundry_batch_id),
    CONSTRAINT laundry_batch_status_known CHECK (status IN ('Draft', 'Dispatched', 'PartiallyReceived', 'Received', 'Closed'))
);
COMMENT ON TABLE inventory.laundry_batch IS 'The batch''s lifecycle only; what went out and came back are its ledger entries. [§53.2 Inventory: towels, robes, linens - wash actions]';

CREATE TABLE inventory.service_supply (
    service_supply_id              uuid NOT NULL DEFAULT core.uuid_v7(),
    tenant_id                      uuid NOT NULL,
    service_id                     uuid NOT NULL,
    inventory_item_variant_id      uuid NOT NULL,
    quantity                       numeric(18,6) NOT NULL,
    waste_percent                  numeric(9,6) NOT NULL DEFAULT 0,
    is_returnable                  boolean NOT NULL DEFAULT false,
    status                         text NOT NULL DEFAULT 'Active',
    effective_from                 timestamptz NOT NULL DEFAULT now(),
    effective_to                   timestamptz,
    source_system                  text NOT NULL DEFAULT 'Spa',
    source_key                     text,
    version                        integer NOT NULL DEFAULT 1,
    created_at                     timestamptz NOT NULL DEFAULT now(),
    created_by                     uuid,
    updated_at                     timestamptz NOT NULL DEFAULT now(),
    updated_by                     uuid,
    correlation_id                 text,
    CONSTRAINT service_supply_pkey PRIMARY KEY (service_supply_id),
    CONSTRAINT service_supply_quantity_ck CHECK (quantity > 0),
    CONSTRAINT service_supply_waste_percent_ck CHECK (waste_percent >= 0 AND waste_percent < 1),
    CONSTRAINT service_supply_version_ck CHECK (version >= 1),
    CONSTRAINT service_supply_tenant_identity_uq UNIQUE (tenant_id, service_supply_id),
    CONSTRAINT service_supply_status_known CHECK (status IN ('Active', 'Retired')),
    CONSTRAINT service_supply_effective_range_ck CHECK (effective_to IS NULL OR effective_to > effective_from),
    CONSTRAINT service_supply_variant_uq UNIQUE (tenant_id, service_id, inventory_item_variant_id, effective_from)
);
COMMENT ON TABLE inventory.service_supply IS 'What one appointment of a service consumes or cycles (towels, robes, product) - the booking-driven forecast is computed from this and the schedule, not stored.';
COMMENT ON COLUMN inventory.service_supply.is_returnable IS 'linen returns to laundry rather than being consumed';

CREATE TABLE inventory.stock_count (
    stock_count_id                 uuid NOT NULL DEFAULT core.uuid_v7(),
    tenant_id                      uuid NOT NULL,
    property_id                    uuid NOT NULL,
    inventory_item_variant_id      uuid NOT NULL,
    location_id                    uuid NOT NULL,
    lot_number                     text,
    stock_state                    text NOT NULL DEFAULT 'Saleable',
    expected_quantity              numeric(18,6) NOT NULL,
    observed_quantity              numeric(18,6),
    recount_quantity               numeric(18,6),
    variance_quantity              numeric(18,6) GENERATED ALWAYS AS (coalesce(recount_quantity, observed_quantity) - expected_quantity) STORED,
    counted_at                     timestamptz,
    counted_by                     uuid,
    approved_by                    uuid,
    approved_at                    timestamptz,
    reason_code                    text,
    status                         text NOT NULL DEFAULT 'Open',
    version                        integer NOT NULL DEFAULT 1,
    created_at                     timestamptz NOT NULL DEFAULT now(),
    created_by                     uuid,
    updated_at                     timestamptz NOT NULL DEFAULT now(),
    updated_by                     uuid,
    correlation_id                 text,
    CONSTRAINT stock_count_pkey PRIMARY KEY (stock_count_id),
    CONSTRAINT stock_count_stock_state_ck CHECK (stock_state IN ('Saleable', 'Clean', 'Soiled', 'InLaundry', 'Damaged', 'Quarantine')),
    CONSTRAINT stock_count_version_ck CHECK (version >= 1),
    CONSTRAINT stock_count_tenant_identity_uq UNIQUE (tenant_id, stock_count_id),
    CONSTRAINT stock_count_status_known CHECK (status IN ('Open', 'Counted', 'Recounted', 'Approved', 'Posted', 'Cancelled')),
    CONSTRAINT stock_count_approver_not_counter CHECK (approved_by IS NULL OR approved_by IS DISTINCT FROM counted_by)
);
COMMENT ON TABLE inventory.stock_count IS 'Kept typed: a count has an approval step (counter != approver) before its variance posts.';
COMMENT ON COLUMN inventory.stock_count.variance_quantity IS 'NULL until counted';

ALTER TABLE inventory.inventory_item ADD CONSTRAINT inventory_item_tenant_fk FOREIGN KEY (tenant_id) REFERENCES core.tenant (tenant_id);
ALTER TABLE inventory.inventory_item_variant ADD CONSTRAINT inventory_item_variant_inventory_item_id_fk FOREIGN KEY (tenant_id, inventory_item_id) REFERENCES inventory.inventory_item (tenant_id, inventory_item_id) ON DELETE RESTRICT;
CREATE INDEX inventory_item_variant_inventory_item_id_ix ON inventory.inventory_item_variant (tenant_id, inventory_item_id);
ALTER TABLE inventory.inventory_item_variant ADD CONSTRAINT inventory_item_variant_tenant_fk FOREIGN KEY (tenant_id) REFERENCES core.tenant (tenant_id);
ALTER TABLE inventory.inventory_location_balance ADD CONSTRAINT inventory_location_balance_inventory_item_variant_id_fk FOREIGN KEY (tenant_id, inventory_item_variant_id) REFERENCES inventory.inventory_item_variant (tenant_id, inventory_item_variant_id) ON DELETE RESTRICT;
CREATE INDEX inventory_location_balance_inventory_item_variant_id_ix ON inventory.inventory_location_balance (tenant_id, inventory_item_variant_id);
ALTER TABLE inventory.inventory_location_balance ADD CONSTRAINT inventory_location_balance_location_id_fk FOREIGN KEY (tenant_id, property_id, location_id) REFERENCES resources.location (tenant_id, property_id, location_id) ON DELETE RESTRICT;
CREATE INDEX inventory_location_balance_location_id_ix ON inventory.inventory_location_balance (tenant_id, property_id, location_id);
ALTER TABLE inventory.inventory_location_balance ADD CONSTRAINT inventory_location_balance_tenant_fk FOREIGN KEY (tenant_id) REFERENCES core.tenant (tenant_id);
ALTER TABLE inventory.inventory_location_balance ADD CONSTRAINT inventory_location_balance_property_fk FOREIGN KEY (tenant_id, property_id) REFERENCES core.property (tenant_id, property_id);
ALTER TABLE inventory.inventory_ledger_entry ADD CONSTRAINT inventory_ledger_entry_inventory_item_variant_id_fk FOREIGN KEY (tenant_id, inventory_item_variant_id) REFERENCES inventory.inventory_item_variant (tenant_id, inventory_item_variant_id) ON DELETE RESTRICT;
CREATE INDEX inventory_ledger_entry_inventory_item_variant_id_ix ON inventory.inventory_ledger_entry (tenant_id, inventory_item_variant_id);
ALTER TABLE inventory.inventory_ledger_entry ADD CONSTRAINT inventory_ledger_entry_location_id_fk FOREIGN KEY (tenant_id, property_id, location_id) REFERENCES resources.location (tenant_id, property_id, location_id) ON DELETE RESTRICT;
CREATE INDEX inventory_ledger_entry_location_id_ix ON inventory.inventory_ledger_entry (tenant_id, property_id, location_id);
ALTER TABLE inventory.inventory_ledger_entry ADD CONSTRAINT inventory_ledger_entry_tenant_fk FOREIGN KEY (tenant_id) REFERENCES core.tenant (tenant_id);
ALTER TABLE inventory.inventory_ledger_entry ADD CONSTRAINT inventory_ledger_entry_property_fk FOREIGN KEY (tenant_id, property_id) REFERENCES core.property (tenant_id, property_id);
ALTER TABLE inventory.laundry_batch ADD CONSTRAINT laundry_batch_dispatch_location_id_fk FOREIGN KEY (tenant_id, property_id, dispatch_location_id) REFERENCES resources.location (tenant_id, property_id, location_id) ON DELETE RESTRICT;
CREATE INDEX laundry_batch_dispatch_location_id_ix ON inventory.laundry_batch (tenant_id, property_id, dispatch_location_id);
ALTER TABLE inventory.laundry_batch ADD CONSTRAINT laundry_batch_return_location_id_fk FOREIGN KEY (tenant_id, property_id, return_location_id) REFERENCES resources.location (tenant_id, property_id, location_id) ON DELETE RESTRICT;
CREATE INDEX laundry_batch_return_location_id_ix ON inventory.laundry_batch (tenant_id, property_id, return_location_id);
ALTER TABLE inventory.laundry_batch ADD CONSTRAINT laundry_batch_tenant_fk FOREIGN KEY (tenant_id) REFERENCES core.tenant (tenant_id);
ALTER TABLE inventory.laundry_batch ADD CONSTRAINT laundry_batch_property_fk FOREIGN KEY (tenant_id, property_id) REFERENCES core.property (tenant_id, property_id);
ALTER TABLE inventory.service_supply ADD CONSTRAINT service_supply_service_id_fk FOREIGN KEY (tenant_id, service_id) REFERENCES catalog.service (tenant_id, service_id) ON DELETE RESTRICT;
CREATE INDEX service_supply_service_id_ix ON inventory.service_supply (tenant_id, service_id);
ALTER TABLE inventory.service_supply ADD CONSTRAINT service_supply_inventory_item_variant_id_fk FOREIGN KEY (tenant_id, inventory_item_variant_id) REFERENCES inventory.inventory_item_variant (tenant_id, inventory_item_variant_id) ON DELETE RESTRICT;
CREATE INDEX service_supply_inventory_item_variant_id_ix ON inventory.service_supply (tenant_id, inventory_item_variant_id);
ALTER TABLE inventory.service_supply ADD CONSTRAINT service_supply_tenant_fk FOREIGN KEY (tenant_id) REFERENCES core.tenant (tenant_id);
ALTER TABLE inventory.stock_count ADD CONSTRAINT stock_count_inventory_item_variant_id_fk FOREIGN KEY (tenant_id, inventory_item_variant_id) REFERENCES inventory.inventory_item_variant (tenant_id, inventory_item_variant_id) ON DELETE RESTRICT;
CREATE INDEX stock_count_inventory_item_variant_id_ix ON inventory.stock_count (tenant_id, inventory_item_variant_id);
ALTER TABLE inventory.stock_count ADD CONSTRAINT stock_count_location_id_fk FOREIGN KEY (tenant_id, property_id, location_id) REFERENCES resources.location (tenant_id, property_id, location_id) ON DELETE RESTRICT;
CREATE INDEX stock_count_location_id_ix ON inventory.stock_count (tenant_id, property_id, location_id);
ALTER TABLE inventory.stock_count ADD CONSTRAINT stock_count_tenant_fk FOREIGN KEY (tenant_id) REFERENCES core.tenant (tenant_id);
ALTER TABLE inventory.stock_count ADD CONSTRAINT stock_count_property_fk FOREIGN KEY (tenant_id, property_id) REFERENCES core.property (tenant_id, property_id);

CREATE TRIGGER inventory_item_touch BEFORE UPDATE ON inventory.inventory_item FOR EACH ROW EXECUTE FUNCTION core.touch_versioned();
CREATE TRIGGER inventory_item_variant_touch BEFORE UPDATE ON inventory.inventory_item_variant FOR EACH ROW EXECUTE FUNCTION core.touch_versioned();
CREATE TRIGGER inventory_location_balance_touch BEFORE UPDATE ON inventory.inventory_location_balance FOR EACH ROW EXECUTE FUNCTION core.touch();
CREATE TRIGGER inventory_ledger_entry_append_only BEFORE UPDATE OR DELETE ON inventory.inventory_ledger_entry FOR EACH ROW EXECUTE FUNCTION core.forbid_mutation();
DO $$ BEGIN PERFORM core.ensure_monthly_partitions('inventory.inventory_ledger_entry'::regclass, (date_trunc('month', now() AT TIME ZONE 'UTC') - interval '1 month')::date, 4); END $$;
CREATE TABLE inventory.inventory_ledger_entry_default PARTITION OF inventory.inventory_ledger_entry DEFAULT;
CREATE TRIGGER laundry_batch_touch BEFORE UPDATE ON inventory.laundry_batch FOR EACH ROW EXECUTE FUNCTION core.touch_versioned();
CREATE TRIGGER service_supply_touch BEFORE UPDATE ON inventory.service_supply FOR EACH ROW EXECUTE FUNCTION core.touch_versioned();
CREATE TRIGGER stock_count_touch BEFORE UPDATE ON inventory.stock_count FOR EACH ROW EXECUTE FUNCTION core.touch_versioned();
CREATE UNIQUE INDEX inventory_item_variant_barcode_uq ON inventory.inventory_item_variant (tenant_id, barcode) WHERE barcode IS NOT NULL;
CREATE INDEX inventory_ledger_entry_grain_ix ON inventory.inventory_ledger_entry (tenant_id, property_id, inventory_item_variant_id, location_id, occurred_at);
CREATE INDEX inventory_ledger_entry_source_ix ON inventory.inventory_ledger_entry (tenant_id, source_document_type, source_document_id);
