-- 09 inventory: generated by database/tools/generate.py from database/model/. Do not edit.
-- may reference: catalog, core, guest, resources, scheduling, workforce

CREATE SCHEMA IF NOT EXISTS inventory AUTHORIZATION spms_owner;

CREATE TABLE inventory.inventory_item (
    inventory_item_id              uuid NOT NULL DEFAULT core.uuid_v7(),
    tenant_id                      uuid NOT NULL,
    item_code                      text NOT NULL,
    item_name                      text NOT NULL,
    item_kind                      text NOT NULL,
    tracking_method                text NOT NULL DEFAULT 'Quantity',
    base_uom                       text NOT NULL DEFAULT 'ea',
    description                    text,
    brand_name                     text,
    category_code                  text,
    reorder_point                  numeric(18,6) NOT NULL DEFAULT 0,
    maximum_stock                  numeric(18,6),
    lead_time_days                 integer NOT NULL DEFAULT 0,
    usage_notes                    text,
    status                         text NOT NULL DEFAULT 'Active',
    effective_from                 timestamptz NOT NULL DEFAULT now(),
    effective_to                   timestamptz,
    source_system                  text NOT NULL DEFAULT 'Spa',
    source_key                     text,
    version                        integer NOT NULL DEFAULT 1,
    created_at                     timestamptz NOT NULL DEFAULT now(),
    created_by                     uuid,
    updated_at                     timestamptz NOT NULL DEFAULT now(),
    updated_by                     uuid,
    correlation_id                 text,
    CONSTRAINT inventory_item_pkey PRIMARY KEY (inventory_item_id),
    CONSTRAINT inventory_item_item_kind_ck CHECK (item_kind IN ('Retail', 'Linen', 'Amenity', 'Consumable', 'Professional')),
    CONSTRAINT inventory_item_tracking_method_ck CHECK (tracking_method IN ('Quantity', 'Lot', 'Serial')),
    CONSTRAINT inventory_item_reorder_point_ck CHECK (reorder_point >= 0),
    CONSTRAINT inventory_item_lead_time_days_ck CHECK (lead_time_days >= 0),
    CONSTRAINT inventory_item_version_ck CHECK (version >= 1),
    CONSTRAINT inventory_item_tenant_identity_uq UNIQUE (tenant_id, inventory_item_id),
    CONSTRAINT inventory_item_status_known CHECK (status IN ('Active', 'Inactive', 'Retired')),
    CONSTRAINT inventory_item_effective_range_ck CHECK (effective_to IS NULL OR effective_to > effective_from),
    CONSTRAINT inventory_item_code_uq UNIQUE (tenant_id, item_code)
);

CREATE TABLE inventory.inventory_item_variant (
    inventory_item_variant_id      uuid NOT NULL DEFAULT core.uuid_v7(),
    tenant_id                      uuid NOT NULL,
    inventory_item_id              uuid NOT NULL,
    variant_code                   text NOT NULL,
    barcode                        text,
    size_code                      text,
    color_code                     text,
    base_uom                       text NOT NULL DEFAULT 'ea',
    net_content                    numeric(18,6),
    net_content_uom                text,
    manufacturer_item_number       text,
    commerce_catalog_item_id       uuid,
    inventory_enabled              boolean NOT NULL DEFAULT true,
    status                         text NOT NULL DEFAULT 'Active',
    effective_from                 timestamptz NOT NULL DEFAULT now(),
    effective_to                   timestamptz,
    source_system                  text NOT NULL DEFAULT 'Spa',
    source_key                     text,
    version                        integer NOT NULL DEFAULT 1,
    created_at                     timestamptz NOT NULL DEFAULT now(),
    created_by                     uuid,
    updated_at                     timestamptz NOT NULL DEFAULT now(),
    updated_by                     uuid,
    correlation_id                 text,
    CONSTRAINT inventory_item_variant_pkey PRIMARY KEY (inventory_item_variant_id),
    CONSTRAINT inventory_item_variant_version_ck CHECK (version >= 1),
    CONSTRAINT inventory_item_variant_tenant_identity_uq UNIQUE (tenant_id, inventory_item_variant_id),
    CONSTRAINT inventory_item_variant_status_known CHECK (status IN ('Active', 'Inactive', 'Retired')),
    CONSTRAINT inventory_item_variant_effective_range_ck CHECK (effective_to IS NULL OR effective_to > effective_from),
    CONSTRAINT inventory_item_variant_code_uq UNIQUE (tenant_id, variant_code)
);
COMMENT ON COLUMN inventory.inventory_item_variant.barcode IS 'GTIN/UPC as text; leading zeros are significant';

CREATE TABLE inventory.product_lot (
    product_lot_id                 uuid NOT NULL DEFAULT core.uuid_v7(),
    tenant_id                      uuid NOT NULL,
    inventory_item_variant_id      uuid NOT NULL,
    lot_number                     text NOT NULL,
    expires_on                     date,
    received_at                    timestamptz,
    status                         text NOT NULL DEFAULT 'Active',
    version                        integer NOT NULL DEFAULT 1,
    created_at                     timestamptz NOT NULL DEFAULT now(),
    created_by                     uuid,
    updated_at                     timestamptz NOT NULL DEFAULT now(),
    updated_by                     uuid,
    correlation_id                 text,
    CONSTRAINT product_lot_pkey PRIMARY KEY (product_lot_id),
    CONSTRAINT product_lot_version_ck CHECK (version >= 1),
    CONSTRAINT product_lot_tenant_identity_uq UNIQUE (tenant_id, product_lot_id),
    CONSTRAINT product_lot_status_known CHECK (status IN ('Active', 'Expired', 'Recalled', 'Consumed')),
    CONSTRAINT product_lot_lot_uq UNIQUE (tenant_id, inventory_item_variant_id, lot_number)
);

CREATE TABLE inventory.inventory_location_balance (
    inventory_location_balance_id  uuid NOT NULL DEFAULT core.uuid_v7(),
    tenant_id                      uuid NOT NULL,
    property_id                    uuid NOT NULL,
    inventory_item_variant_id      uuid NOT NULL,
    location_id                    uuid NOT NULL,
    product_lot_id                 uuid,
    stock_state                    text NOT NULL DEFAULT 'Saleable',
    on_hand                        numeric(18,6) NOT NULL DEFAULT 0,
    allocated                      numeric(18,6) NOT NULL DEFAULT 0,
    available                      numeric(18,6) GENERATED ALWAYS AS (on_hand - allocated) STORED NOT NULL,
    unit_cost_minor                numeric(24,6) NOT NULL DEFAULT 0,
    created_at                     timestamptz NOT NULL DEFAULT now(),
    created_by                     uuid,
    updated_at                     timestamptz NOT NULL DEFAULT now(),
    updated_by                     uuid,
    correlation_id                 text,
    CONSTRAINT inventory_location_balance_pkey PRIMARY KEY (inventory_location_balance_id),
    CONSTRAINT inventory_location_balance_stock_state_ck CHECK (stock_state IN ('Saleable', 'Clean', 'Soiled', 'InLaundry', 'Damaged', 'Quarantine')),
    CONSTRAINT inventory_location_balance_allocated_ck CHECK (allocated >= 0),
    CONSTRAINT inventory_location_balance_unit_cost_minor_ck CHECK (unit_cost_minor >= 0),
    CONSTRAINT inventory_location_balance_tenant_identity_uq UNIQUE (tenant_id, inventory_location_balance_id),
    CONSTRAINT inventory_location_balance_grain_uq UNIQUE NULLS NOT DISTINCT (tenant_id, property_id, inventory_item_variant_id, location_id, product_lot_id, stock_state)
);
COMMENT ON TABLE inventory.inventory_location_balance IS 'Projection of the ledger, updated in the same transaction as each ledger entry.';

CREATE TABLE inventory.inventory_ledger_entry (
    entry_id                       uuid NOT NULL DEFAULT core.uuid_v7(),
    tenant_id                      uuid NOT NULL,
    property_id                    uuid NOT NULL,
    inventory_item_variant_id      uuid NOT NULL,
    location_id                    uuid NOT NULL,
    product_lot_id                 uuid,
    stock_state                    text NOT NULL,
    movement_type                  text NOT NULL,
    quantity                       numeric(18,6) NOT NULL,
    base_uom                       text NOT NULL,
    unit_cost_minor                numeric(24,6),
    value_delta_minor              numeric(24,6),
    reason_code                    text,
    original_entry_id              uuid,
    source_document_type           text,
    source_document_id             uuid,
    owner_system                   text NOT NULL DEFAULT 'Spa',
    idempotency_key                text NOT NULL,
    occurred_at                    timestamptz NOT NULL DEFAULT now(),
    created_by                     uuid,
    correlation_id                 text,
    CONSTRAINT inventory_ledger_entry_pkey PRIMARY KEY (entry_id, occurred_at),
    CONSTRAINT inventory_ledger_entry_stock_state_ck CHECK (stock_state IN ('Saleable', 'Clean', 'Soiled', 'InLaundry', 'Damaged', 'Quarantine')),
    CONSTRAINT inventory_ledger_entry_movement_type_ck CHECK (movement_type IN ('Receipt', 'Issue', 'Sale', 'Return', 'Adjustment', 'TransferOut', 'TransferIn', 'LaundryOut', 'LaundryIn', 'Consumption', 'CountVariance', 'StateChange', 'Reversal')),
    CONSTRAINT inventory_ledger_entry_quantity_ck CHECK (quantity <> 0),
    CONSTRAINT inventory_ledger_entry_owner_system_ck CHECK (owner_system IN ('Spa', 'Marquee', 'Pos', 'External')),
    CONSTRAINT inventory_ledger_entry_reversal_has_target CHECK ((movement_type = 'Reversal') = (original_entry_id IS NOT NULL))
) PARTITION BY RANGE (occurred_at);
COMMENT ON TABLE inventory.inventory_ledger_entry IS 'Signed stock movements. Never updated: a correction is a reversing entry (original_entry_id). [§Stock grain and posting; §Numbers and six decimal places]';
COMMENT ON COLUMN inventory.inventory_ledger_entry.original_entry_id IS 'reversal target (no FK: partitioned)';

CREATE TABLE inventory.inventory_transfer (
    inventory_transfer_id          uuid NOT NULL DEFAULT core.uuid_v7(),
    tenant_id                      uuid NOT NULL,
    property_id                    uuid NOT NULL,
    inventory_item_variant_id      uuid NOT NULL,
    product_lot_id                 uuid,
    from_location_id               uuid NOT NULL,
    to_location_id                 uuid NOT NULL,
    from_state                     text NOT NULL DEFAULT 'Saleable',
    to_state                       text NOT NULL DEFAULT 'Saleable',
    quantity                       numeric(18,6) NOT NULL,
    shipped_quantity               numeric(18,6) NOT NULL DEFAULT 0,
    received_quantity              numeric(18,6) NOT NULL DEFAULT 0,
    damaged_quantity               numeric(18,6) NOT NULL DEFAULT 0,
    shipped_at                     timestamptz,
    received_at                    timestamptz,
    approved_by                    uuid,
    status                         text NOT NULL DEFAULT 'Draft',
    version                        integer NOT NULL DEFAULT 1,
    created_at                     timestamptz NOT NULL DEFAULT now(),
    created_by                     uuid,
    updated_at                     timestamptz NOT NULL DEFAULT now(),
    updated_by                     uuid,
    correlation_id                 text,
    CONSTRAINT inventory_transfer_pkey PRIMARY KEY (inventory_transfer_id),
    CONSTRAINT inventory_transfer_from_state_ck CHECK (from_state IN ('Saleable', 'Clean', 'Soiled', 'InLaundry', 'Damaged', 'Quarantine')),
    CONSTRAINT inventory_transfer_to_state_ck CHECK (to_state IN ('Saleable', 'Clean', 'Soiled', 'InLaundry', 'Damaged', 'Quarantine')),
    CONSTRAINT inventory_transfer_quantity_ck CHECK (quantity > 0),
    CONSTRAINT inventory_transfer_version_ck CHECK (version >= 1),
    CONSTRAINT inventory_transfer_tenant_identity_uq UNIQUE (tenant_id, inventory_transfer_id),
    CONSTRAINT inventory_transfer_status_known CHECK (status IN ('Draft', 'Shipped', 'Received', 'Cancelled')),
    CONSTRAINT inventory_transfer_distinct_ends CHECK (from_location_id <> to_location_id OR from_state <> to_state),
    CONSTRAINT inventory_transfer_received_within_shipped CHECK (received_quantity + damaged_quantity <= shipped_quantity)
);
COMMENT ON COLUMN inventory.inventory_transfer.quantity IS 'requested';

CREATE TABLE inventory.laundry_batch (
    laundry_batch_id               uuid NOT NULL DEFAULT core.uuid_v7(),
    tenant_id                      uuid NOT NULL,
    property_id                    uuid NOT NULL,
    dispatch_location_id           uuid NOT NULL,
    return_location_id             uuid NOT NULL,
    dispatched_at                  timestamptz,
    expected_return_at             timestamptz,
    received_at                    timestamptz,
    supplier_reference             text,
    status                         text NOT NULL DEFAULT 'Draft',
    version                        integer NOT NULL DEFAULT 1,
    created_at                     timestamptz NOT NULL DEFAULT now(),
    created_by                     uuid,
    updated_at                     timestamptz NOT NULL DEFAULT now(),
    updated_by                     uuid,
    correlation_id                 text,
    CONSTRAINT laundry_batch_pkey PRIMARY KEY (laundry_batch_id),
    CONSTRAINT laundry_batch_version_ck CHECK (version >= 1),
    CONSTRAINT laundry_batch_tenant_identity_uq UNIQUE (tenant_id, laundry_batch_id),
    CONSTRAINT laundry_batch_prop_ref_uq UNIQUE (tenant_id, property_id, laundry_batch_id),
    CONSTRAINT laundry_batch_status_known CHECK (status IN ('Draft', 'Dispatched', 'PartiallyReceived', 'Received', 'Closed'))
);

CREATE TABLE inventory.laundry_batch_line (
    laundry_batch_line_id          uuid NOT NULL DEFAULT core.uuid_v7(),
    tenant_id                      uuid NOT NULL,
    property_id                    uuid NOT NULL,
    laundry_batch_id               uuid NOT NULL,
    inventory_item_variant_id      uuid NOT NULL,
    product_lot_id                 uuid,
    dispatched_quantity            numeric(18,6) NOT NULL,
    received_quantity              numeric(18,6) NOT NULL DEFAULT 0,
    lost_quantity                  numeric(18,6) NOT NULL DEFAULT 0,
    created_at                     timestamptz NOT NULL DEFAULT now(),
    created_by                     uuid,
    updated_at                     timestamptz NOT NULL DEFAULT now(),
    updated_by                     uuid,
    correlation_id                 text,
    CONSTRAINT laundry_batch_line_pkey PRIMARY KEY (laundry_batch_line_id),
    CONSTRAINT laundry_batch_line_dispatched_quantity_ck CHECK (dispatched_quantity > 0),
    CONSTRAINT laundry_batch_line_received_quantity_ck CHECK (received_quantity >= 0),
    CONSTRAINT laundry_batch_line_lost_quantity_ck CHECK (lost_quantity >= 0),
    CONSTRAINT laundry_batch_line_tenant_identity_uq UNIQUE (tenant_id, laundry_batch_line_id),
    CONSTRAINT laundry_batch_line_accounted CHECK (received_quantity + lost_quantity <= dispatched_quantity),
    CONSTRAINT laundry_batch_line_variant_uq UNIQUE NULLS NOT DISTINCT (tenant_id, laundry_batch_id, inventory_item_variant_id, product_lot_id)
);

CREATE TABLE inventory.supply_recipe (
    supply_recipe_id               uuid NOT NULL DEFAULT core.uuid_v7(),
    tenant_id                      uuid NOT NULL,
    service_id                     uuid NOT NULL,
    recipe_code                    text NOT NULL,
    recipe_revision                integer NOT NULL DEFAULT 1,
    yield_quantity                 numeric(18,6) NOT NULL DEFAULT 1,
    published_at                   timestamptz,
    status                         text NOT NULL DEFAULT 'Draft',
    effective_from                 timestamptz NOT NULL DEFAULT now(),
    effective_to                   timestamptz,
    source_system                  text NOT NULL DEFAULT 'Spa',
    source_key                     text,
    version                        integer NOT NULL DEFAULT 1,
    created_at                     timestamptz NOT NULL DEFAULT now(),
    created_by                     uuid,
    updated_at                     timestamptz NOT NULL DEFAULT now(),
    updated_by                     uuid,
    correlation_id                 text,
    CONSTRAINT supply_recipe_pkey PRIMARY KEY (supply_recipe_id),
    CONSTRAINT supply_recipe_recipe_revision_ck CHECK (recipe_revision >= 1),
    CONSTRAINT supply_recipe_yield_quantity_ck CHECK (yield_quantity > 0),
    CONSTRAINT supply_recipe_version_ck CHECK (version >= 1),
    CONSTRAINT supply_recipe_tenant_identity_uq UNIQUE (tenant_id, supply_recipe_id),
    CONSTRAINT supply_recipe_status_known CHECK (status IN ('Draft', 'Published', 'Retired')),
    CONSTRAINT supply_recipe_effective_range_ck CHECK (effective_to IS NULL OR effective_to > effective_from),
    CONSTRAINT supply_recipe_revision_uq UNIQUE (tenant_id, recipe_code, recipe_revision)
);
COMMENT ON TABLE inventory.supply_recipe IS 'What a service consumes (towels, robes, product) - the input to the booking-driven forecast.';

CREATE TABLE inventory.supply_recipe_line (
    supply_recipe_line_id          uuid NOT NULL DEFAULT core.uuid_v7(),
    tenant_id                      uuid NOT NULL,
    supply_recipe_id               uuid NOT NULL,
    inventory_item_variant_id      uuid NOT NULL,
    base_quantity                  numeric(18,6) NOT NULL,
    waste_percent                  numeric(9,6) NOT NULL DEFAULT 0,
    is_returnable                  boolean NOT NULL DEFAULT false,
    substitute_variant_id          uuid,
    created_at                     timestamptz NOT NULL DEFAULT now(),
    created_by                     uuid,
    updated_at                     timestamptz NOT NULL DEFAULT now(),
    updated_by                     uuid,
    correlation_id                 text,
    CONSTRAINT supply_recipe_line_pkey PRIMARY KEY (supply_recipe_line_id),
    CONSTRAINT supply_recipe_line_base_quantity_ck CHECK (base_quantity > 0),
    CONSTRAINT supply_recipe_line_waste_percent_ck CHECK (waste_percent >= 0 AND waste_percent < 1),
    CONSTRAINT supply_recipe_line_tenant_identity_uq UNIQUE (tenant_id, supply_recipe_line_id),
    CONSTRAINT supply_recipe_line_variant_uq UNIQUE (tenant_id, supply_recipe_id, inventory_item_variant_id)
);
COMMENT ON COLUMN inventory.supply_recipe_line.is_returnable IS 'linen returns to laundry rather than being consumed';

CREATE TABLE inventory.demand_forecast (
    demand_forecast_id             uuid NOT NULL DEFAULT core.uuid_v7(),
    tenant_id                      uuid NOT NULL,
    property_id                    uuid NOT NULL,
    forecast_at                    timestamptz NOT NULL DEFAULT now(),
    horizon_start                  timestamptz NOT NULL,
    horizon_end                    timestamptz NOT NULL,
    model_version                  text NOT NULL,
    input_watermark                timestamptz NOT NULL,
    assumptions                    jsonb NOT NULL DEFAULT '{}',
    status                         text NOT NULL DEFAULT 'Draft',
    version                        integer NOT NULL DEFAULT 1,
    created_at                     timestamptz NOT NULL DEFAULT now(),
    created_by                     uuid,
    updated_at                     timestamptz NOT NULL DEFAULT now(),
    updated_by                     uuid,
    correlation_id                 text,
    CONSTRAINT demand_forecast_pkey PRIMARY KEY (demand_forecast_id),
    CONSTRAINT demand_forecast_version_ck CHECK (version >= 1),
    CONSTRAINT demand_forecast_tenant_identity_uq UNIQUE (tenant_id, demand_forecast_id),
    CONSTRAINT demand_forecast_prop_ref_uq UNIQUE (tenant_id, property_id, demand_forecast_id),
    CONSTRAINT demand_forecast_status_known CHECK (status IN ('Draft', 'Published', 'Superseded')),
    CONSTRAINT demand_forecast_horizon_forward CHECK (horizon_end > horizon_start)
);

CREATE TABLE inventory.forecast_line (
    forecast_line_id               uuid NOT NULL DEFAULT core.uuid_v7(),
    tenant_id                      uuid NOT NULL,
    property_id                    uuid NOT NULL,
    demand_forecast_id             uuid NOT NULL,
    inventory_item_variant_id      uuid NOT NULL,
    location_id                    uuid NOT NULL,
    bucket_start                   timestamptz NOT NULL,
    bucket_end                     timestamptz NOT NULL,
    gross_clean                    numeric(18,6) NOT NULL,
    reserved                       numeric(18,6) NOT NULL,
    gross_demand                   numeric(18,6) NOT NULL,
    expected_receipts              numeric(18,6) NOT NULL,
    expected_laundry               numeric(18,6) NOT NULL,
    safety_stock                   numeric(18,6) NOT NULL,
    projected_balance              numeric(18,6) NOT NULL,
    confidence                     numeric(7,6) NOT NULL,
    created_at                     timestamptz NOT NULL DEFAULT now(),
    created_by                     uuid,
    updated_at                     timestamptz NOT NULL DEFAULT now(),
    updated_by                     uuid,
    correlation_id                 text,
    CONSTRAINT forecast_line_pkey PRIMARY KEY (forecast_line_id),
    CONSTRAINT forecast_line_confidence_ck CHECK (confidence BETWEEN 0 AND 1),
    CONSTRAINT forecast_line_tenant_identity_uq UNIQUE (tenant_id, forecast_line_id),
    CONSTRAINT forecast_line_bucket_forward CHECK (bucket_end > bucket_start),
    CONSTRAINT forecast_line_bucket_uq UNIQUE (tenant_id, demand_forecast_id, inventory_item_variant_id, location_id, bucket_start)
);

CREATE TABLE inventory.stock_count (
    stock_count_id                 uuid NOT NULL DEFAULT core.uuid_v7(),
    tenant_id                      uuid NOT NULL,
    property_id                    uuid NOT NULL,
    inventory_item_variant_id      uuid NOT NULL,
    location_id                    uuid NOT NULL,
    product_lot_id                 uuid,
    stock_state                    text NOT NULL DEFAULT 'Saleable',
    expected_quantity              numeric(18,6) NOT NULL,
    observed_quantity              numeric(18,6),
    recount_quantity               numeric(18,6),
    variance_quantity              numeric(18,6) GENERATED ALWAYS AS (coalesce(recount_quantity, observed_quantity) - expected_quantity) STORED NOT NULL,
    counted_at                     timestamptz,
    counted_by                     uuid,
    approved_by                    uuid,
    approved_at                    timestamptz,
    reason_code                    text,
    posted_entry_id                uuid,
    status                         text NOT NULL DEFAULT 'Open',
    version                        integer NOT NULL DEFAULT 1,
    created_at                     timestamptz NOT NULL DEFAULT now(),
    created_by                     uuid,
    updated_at                     timestamptz NOT NULL DEFAULT now(),
    updated_by                     uuid,
    correlation_id                 text,
    CONSTRAINT stock_count_pkey PRIMARY KEY (stock_count_id),
    CONSTRAINT stock_count_stock_state_ck CHECK (stock_state IN ('Saleable', 'Clean', 'Soiled', 'InLaundry', 'Damaged', 'Quarantine')),
    CONSTRAINT stock_count_version_ck CHECK (version >= 1),
    CONSTRAINT stock_count_tenant_identity_uq UNIQUE (tenant_id, stock_count_id),
    CONSTRAINT stock_count_status_known CHECK (status IN ('Open', 'Counted', 'Recounted', 'Approved', 'Posted', 'Cancelled')),
    CONSTRAINT stock_count_approver_not_counter CHECK (approved_by IS NULL OR approved_by IS DISTINCT FROM counted_by)
);
COMMENT ON COLUMN inventory.stock_count.posted_entry_id IS 'the CountVariance ledger entry';

CREATE TABLE inventory.service_product_use (
    service_product_use_id         uuid NOT NULL DEFAULT core.uuid_v7(),
    tenant_id                      uuid NOT NULL,
    property_id                    uuid NOT NULL,
    appointment_id                 uuid NOT NULL,
    inventory_item_variant_id      uuid NOT NULL,
    product_lot_id                 uuid,
    quantity                       numeric(18,6) NOT NULL,
    used_by                        uuid NOT NULL,
    ledger_entry_id                uuid,
    created_at                     timestamptz NOT NULL DEFAULT now(),
    created_by                     uuid,
    correlation_id                 text,
    CONSTRAINT service_product_use_pkey PRIMARY KEY (service_product_use_id),
    CONSTRAINT service_product_use_quantity_ck CHECK (quantity > 0),
    CONSTRAINT service_product_use_tenant_identity_uq UNIQUE (tenant_id, service_product_use_id)
);
COMMENT ON COLUMN inventory.service_product_use.used_by IS 'principal of the provider';
COMMENT ON COLUMN inventory.service_product_use.ledger_entry_id IS 'the Consumption ledger entry (no FK: partitioned)';

ALTER TABLE inventory.inventory_item ADD CONSTRAINT inventory_item_tenant_fk FOREIGN KEY (tenant_id) REFERENCES core.tenant (tenant_id);
ALTER TABLE inventory.inventory_item_variant ADD CONSTRAINT inventory_item_variant_inventory_item_id_fk FOREIGN KEY (tenant_id, inventory_item_id) REFERENCES inventory.inventory_item (tenant_id, inventory_item_id) ON DELETE RESTRICT;
CREATE INDEX inventory_item_variant_inventory_item_id_ix ON inventory.inventory_item_variant (tenant_id, inventory_item_id);
ALTER TABLE inventory.inventory_item_variant ADD CONSTRAINT inventory_item_variant_commerce_catalog_item_id_fk FOREIGN KEY (tenant_id, commerce_catalog_item_id) REFERENCES catalog.commerce_catalog_item (tenant_id, commerce_catalog_item_id) ON DELETE RESTRICT;
CREATE INDEX inventory_item_variant_commerce_catalog_item_id_ix ON inventory.inventory_item_variant (tenant_id, commerce_catalog_item_id);
ALTER TABLE inventory.inventory_item_variant ADD CONSTRAINT inventory_item_variant_tenant_fk FOREIGN KEY (tenant_id) REFERENCES core.tenant (tenant_id);
ALTER TABLE inventory.product_lot ADD CONSTRAINT product_lot_inventory_item_variant_id_fk FOREIGN KEY (tenant_id, inventory_item_variant_id) REFERENCES inventory.inventory_item_variant (tenant_id, inventory_item_variant_id) ON DELETE RESTRICT;
CREATE INDEX product_lot_inventory_item_variant_id_ix ON inventory.product_lot (tenant_id, inventory_item_variant_id);
ALTER TABLE inventory.product_lot ADD CONSTRAINT product_lot_tenant_fk FOREIGN KEY (tenant_id) REFERENCES core.tenant (tenant_id);
ALTER TABLE inventory.inventory_location_balance ADD CONSTRAINT inventory_location_balance_inventory_item_variant_id_fk FOREIGN KEY (tenant_id, inventory_item_variant_id) REFERENCES inventory.inventory_item_variant (tenant_id, inventory_item_variant_id) ON DELETE RESTRICT;
CREATE INDEX inventory_location_balance_inventory_item_variant_id_ix ON inventory.inventory_location_balance (tenant_id, inventory_item_variant_id);
ALTER TABLE inventory.inventory_location_balance ADD CONSTRAINT inventory_location_balance_location_id_fk FOREIGN KEY (tenant_id, property_id, location_id) REFERENCES resources.location (tenant_id, property_id, location_id) ON DELETE RESTRICT;
CREATE INDEX inventory_location_balance_location_id_ix ON inventory.inventory_location_balance (tenant_id, property_id, location_id);
ALTER TABLE inventory.inventory_location_balance ADD CONSTRAINT inventory_location_balance_product_lot_id_fk FOREIGN KEY (tenant_id, product_lot_id) REFERENCES inventory.product_lot (tenant_id, product_lot_id) ON DELETE RESTRICT;
CREATE INDEX inventory_location_balance_product_lot_id_ix ON inventory.inventory_location_balance (tenant_id, product_lot_id);
ALTER TABLE inventory.inventory_location_balance ADD CONSTRAINT inventory_location_balance_tenant_fk FOREIGN KEY (tenant_id) REFERENCES core.tenant (tenant_id);
ALTER TABLE inventory.inventory_location_balance ADD CONSTRAINT inventory_location_balance_property_fk FOREIGN KEY (tenant_id, property_id) REFERENCES core.property (tenant_id, property_id);
ALTER TABLE inventory.inventory_ledger_entry ADD CONSTRAINT inventory_ledger_entry_inventory_item_variant_id_fk FOREIGN KEY (tenant_id, inventory_item_variant_id) REFERENCES inventory.inventory_item_variant (tenant_id, inventory_item_variant_id) ON DELETE RESTRICT;
CREATE INDEX inventory_ledger_entry_inventory_item_variant_id_ix ON inventory.inventory_ledger_entry (tenant_id, inventory_item_variant_id);
ALTER TABLE inventory.inventory_ledger_entry ADD CONSTRAINT inventory_ledger_entry_location_id_fk FOREIGN KEY (tenant_id, property_id, location_id) REFERENCES resources.location (tenant_id, property_id, location_id) ON DELETE RESTRICT;
CREATE INDEX inventory_ledger_entry_location_id_ix ON inventory.inventory_ledger_entry (tenant_id, property_id, location_id);
ALTER TABLE inventory.inventory_ledger_entry ADD CONSTRAINT inventory_ledger_entry_product_lot_id_fk FOREIGN KEY (tenant_id, product_lot_id) REFERENCES inventory.product_lot (tenant_id, product_lot_id) ON DELETE RESTRICT;
CREATE INDEX inventory_ledger_entry_product_lot_id_ix ON inventory.inventory_ledger_entry (tenant_id, product_lot_id);
ALTER TABLE inventory.inventory_ledger_entry ADD CONSTRAINT inventory_ledger_entry_tenant_fk FOREIGN KEY (tenant_id) REFERENCES core.tenant (tenant_id);
ALTER TABLE inventory.inventory_ledger_entry ADD CONSTRAINT inventory_ledger_entry_property_fk FOREIGN KEY (tenant_id, property_id) REFERENCES core.property (tenant_id, property_id);
ALTER TABLE inventory.inventory_transfer ADD CONSTRAINT inventory_transfer_inventory_item_variant_id_fk FOREIGN KEY (tenant_id, inventory_item_variant_id) REFERENCES inventory.inventory_item_variant (tenant_id, inventory_item_variant_id) ON DELETE RESTRICT;
CREATE INDEX inventory_transfer_inventory_item_variant_id_ix ON inventory.inventory_transfer (tenant_id, inventory_item_variant_id);
ALTER TABLE inventory.inventory_transfer ADD CONSTRAINT inventory_transfer_product_lot_id_fk FOREIGN KEY (tenant_id, product_lot_id) REFERENCES inventory.product_lot (tenant_id, product_lot_id) ON DELETE RESTRICT;
CREATE INDEX inventory_transfer_product_lot_id_ix ON inventory.inventory_transfer (tenant_id, product_lot_id);
ALTER TABLE inventory.inventory_transfer ADD CONSTRAINT inventory_transfer_from_location_id_fk FOREIGN KEY (tenant_id, property_id, from_location_id) REFERENCES resources.location (tenant_id, property_id, location_id) ON DELETE RESTRICT;
CREATE INDEX inventory_transfer_from_location_id_ix ON inventory.inventory_transfer (tenant_id, property_id, from_location_id);
ALTER TABLE inventory.inventory_transfer ADD CONSTRAINT inventory_transfer_to_location_id_fk FOREIGN KEY (tenant_id, property_id, to_location_id) REFERENCES resources.location (tenant_id, property_id, location_id) ON DELETE RESTRICT;
CREATE INDEX inventory_transfer_to_location_id_ix ON inventory.inventory_transfer (tenant_id, property_id, to_location_id);
ALTER TABLE inventory.inventory_transfer ADD CONSTRAINT inventory_transfer_tenant_fk FOREIGN KEY (tenant_id) REFERENCES core.tenant (tenant_id);
ALTER TABLE inventory.inventory_transfer ADD CONSTRAINT inventory_transfer_property_fk FOREIGN KEY (tenant_id, property_id) REFERENCES core.property (tenant_id, property_id);
ALTER TABLE inventory.laundry_batch ADD CONSTRAINT laundry_batch_dispatch_location_id_fk FOREIGN KEY (tenant_id, property_id, dispatch_location_id) REFERENCES resources.location (tenant_id, property_id, location_id) ON DELETE RESTRICT;
CREATE INDEX laundry_batch_dispatch_location_id_ix ON inventory.laundry_batch (tenant_id, property_id, dispatch_location_id);
ALTER TABLE inventory.laundry_batch ADD CONSTRAINT laundry_batch_return_location_id_fk FOREIGN KEY (tenant_id, property_id, return_location_id) REFERENCES resources.location (tenant_id, property_id, location_id) ON DELETE RESTRICT;
CREATE INDEX laundry_batch_return_location_id_ix ON inventory.laundry_batch (tenant_id, property_id, return_location_id);
ALTER TABLE inventory.laundry_batch ADD CONSTRAINT laundry_batch_tenant_fk FOREIGN KEY (tenant_id) REFERENCES core.tenant (tenant_id);
ALTER TABLE inventory.laundry_batch ADD CONSTRAINT laundry_batch_property_fk FOREIGN KEY (tenant_id, property_id) REFERENCES core.property (tenant_id, property_id);
ALTER TABLE inventory.laundry_batch_line ADD CONSTRAINT laundry_batch_line_laundry_batch_id_fk FOREIGN KEY (tenant_id, property_id, laundry_batch_id) REFERENCES inventory.laundry_batch (tenant_id, property_id, laundry_batch_id) ON DELETE RESTRICT;
CREATE INDEX laundry_batch_line_laundry_batch_id_ix ON inventory.laundry_batch_line (tenant_id, property_id, laundry_batch_id);
ALTER TABLE inventory.laundry_batch_line ADD CONSTRAINT laundry_batch_line_inventory_item_variant_id_fk FOREIGN KEY (tenant_id, inventory_item_variant_id) REFERENCES inventory.inventory_item_variant (tenant_id, inventory_item_variant_id) ON DELETE RESTRICT;
CREATE INDEX laundry_batch_line_inventory_item_variant_id_ix ON inventory.laundry_batch_line (tenant_id, inventory_item_variant_id);
ALTER TABLE inventory.laundry_batch_line ADD CONSTRAINT laundry_batch_line_product_lot_id_fk FOREIGN KEY (tenant_id, product_lot_id) REFERENCES inventory.product_lot (tenant_id, product_lot_id) ON DELETE RESTRICT;
CREATE INDEX laundry_batch_line_product_lot_id_ix ON inventory.laundry_batch_line (tenant_id, product_lot_id);
ALTER TABLE inventory.laundry_batch_line ADD CONSTRAINT laundry_batch_line_tenant_fk FOREIGN KEY (tenant_id) REFERENCES core.tenant (tenant_id);
ALTER TABLE inventory.laundry_batch_line ADD CONSTRAINT laundry_batch_line_property_fk FOREIGN KEY (tenant_id, property_id) REFERENCES core.property (tenant_id, property_id);
ALTER TABLE inventory.supply_recipe ADD CONSTRAINT supply_recipe_service_id_fk FOREIGN KEY (tenant_id, service_id) REFERENCES catalog.service (tenant_id, service_id) ON DELETE RESTRICT;
CREATE INDEX supply_recipe_service_id_ix ON inventory.supply_recipe (tenant_id, service_id);
ALTER TABLE inventory.supply_recipe ADD CONSTRAINT supply_recipe_tenant_fk FOREIGN KEY (tenant_id) REFERENCES core.tenant (tenant_id);
ALTER TABLE inventory.supply_recipe_line ADD CONSTRAINT supply_recipe_line_supply_recipe_id_fk FOREIGN KEY (tenant_id, supply_recipe_id) REFERENCES inventory.supply_recipe (tenant_id, supply_recipe_id) ON DELETE RESTRICT;
CREATE INDEX supply_recipe_line_supply_recipe_id_ix ON inventory.supply_recipe_line (tenant_id, supply_recipe_id);
ALTER TABLE inventory.supply_recipe_line ADD CONSTRAINT supply_recipe_line_inventory_item_variant_id_fk FOREIGN KEY (tenant_id, inventory_item_variant_id) REFERENCES inventory.inventory_item_variant (tenant_id, inventory_item_variant_id) ON DELETE RESTRICT;
CREATE INDEX supply_recipe_line_inventory_item_variant_id_ix ON inventory.supply_recipe_line (tenant_id, inventory_item_variant_id);
ALTER TABLE inventory.supply_recipe_line ADD CONSTRAINT supply_recipe_line_substitute_variant_id_fk FOREIGN KEY (tenant_id, substitute_variant_id) REFERENCES inventory.inventory_item_variant (tenant_id, inventory_item_variant_id) ON DELETE RESTRICT;
CREATE INDEX supply_recipe_line_substitute_variant_id_ix ON inventory.supply_recipe_line (tenant_id, substitute_variant_id);
ALTER TABLE inventory.supply_recipe_line ADD CONSTRAINT supply_recipe_line_tenant_fk FOREIGN KEY (tenant_id) REFERENCES core.tenant (tenant_id);
CREATE INDEX demand_forecast_scope_ix ON inventory.demand_forecast (tenant_id, property_id);
ALTER TABLE inventory.demand_forecast ADD CONSTRAINT demand_forecast_tenant_fk FOREIGN KEY (tenant_id) REFERENCES core.tenant (tenant_id);
ALTER TABLE inventory.demand_forecast ADD CONSTRAINT demand_forecast_property_fk FOREIGN KEY (tenant_id, property_id) REFERENCES core.property (tenant_id, property_id);
ALTER TABLE inventory.forecast_line ADD CONSTRAINT forecast_line_demand_forecast_id_fk FOREIGN KEY (tenant_id, property_id, demand_forecast_id) REFERENCES inventory.demand_forecast (tenant_id, property_id, demand_forecast_id) ON DELETE RESTRICT;
CREATE INDEX forecast_line_demand_forecast_id_ix ON inventory.forecast_line (tenant_id, property_id, demand_forecast_id);
ALTER TABLE inventory.forecast_line ADD CONSTRAINT forecast_line_inventory_item_variant_id_fk FOREIGN KEY (tenant_id, inventory_item_variant_id) REFERENCES inventory.inventory_item_variant (tenant_id, inventory_item_variant_id) ON DELETE RESTRICT;
CREATE INDEX forecast_line_inventory_item_variant_id_ix ON inventory.forecast_line (tenant_id, inventory_item_variant_id);
ALTER TABLE inventory.forecast_line ADD CONSTRAINT forecast_line_location_id_fk FOREIGN KEY (tenant_id, property_id, location_id) REFERENCES resources.location (tenant_id, property_id, location_id) ON DELETE RESTRICT;
CREATE INDEX forecast_line_location_id_ix ON inventory.forecast_line (tenant_id, property_id, location_id);
ALTER TABLE inventory.forecast_line ADD CONSTRAINT forecast_line_tenant_fk FOREIGN KEY (tenant_id) REFERENCES core.tenant (tenant_id);
ALTER TABLE inventory.forecast_line ADD CONSTRAINT forecast_line_property_fk FOREIGN KEY (tenant_id, property_id) REFERENCES core.property (tenant_id, property_id);
ALTER TABLE inventory.stock_count ADD CONSTRAINT stock_count_inventory_item_variant_id_fk FOREIGN KEY (tenant_id, inventory_item_variant_id) REFERENCES inventory.inventory_item_variant (tenant_id, inventory_item_variant_id) ON DELETE RESTRICT;
CREATE INDEX stock_count_inventory_item_variant_id_ix ON inventory.stock_count (tenant_id, inventory_item_variant_id);
ALTER TABLE inventory.stock_count ADD CONSTRAINT stock_count_location_id_fk FOREIGN KEY (tenant_id, property_id, location_id) REFERENCES resources.location (tenant_id, property_id, location_id) ON DELETE RESTRICT;
CREATE INDEX stock_count_location_id_ix ON inventory.stock_count (tenant_id, property_id, location_id);
ALTER TABLE inventory.stock_count ADD CONSTRAINT stock_count_product_lot_id_fk FOREIGN KEY (tenant_id, product_lot_id) REFERENCES inventory.product_lot (tenant_id, product_lot_id) ON DELETE RESTRICT;
CREATE INDEX stock_count_product_lot_id_ix ON inventory.stock_count (tenant_id, product_lot_id);
ALTER TABLE inventory.stock_count ADD CONSTRAINT stock_count_tenant_fk FOREIGN KEY (tenant_id) REFERENCES core.tenant (tenant_id);
ALTER TABLE inventory.stock_count ADD CONSTRAINT stock_count_property_fk FOREIGN KEY (tenant_id, property_id) REFERENCES core.property (tenant_id, property_id);
ALTER TABLE inventory.service_product_use ADD CONSTRAINT service_product_use_appointment_id_fk FOREIGN KEY (tenant_id, property_id, appointment_id) REFERENCES scheduling.appointment (tenant_id, property_id, appointment_id) ON DELETE RESTRICT;
CREATE INDEX service_product_use_appointment_id_ix ON inventory.service_product_use (tenant_id, property_id, appointment_id);
ALTER TABLE inventory.service_product_use ADD CONSTRAINT service_product_use_inventory_item_variant_id_fk FOREIGN KEY (tenant_id, inventory_item_variant_id) REFERENCES inventory.inventory_item_variant (tenant_id, inventory_item_variant_id) ON DELETE RESTRICT;
CREATE INDEX service_product_use_inventory_item_variant_id_ix ON inventory.service_product_use (tenant_id, inventory_item_variant_id);
ALTER TABLE inventory.service_product_use ADD CONSTRAINT service_product_use_product_lot_id_fk FOREIGN KEY (tenant_id, product_lot_id) REFERENCES inventory.product_lot (tenant_id, product_lot_id) ON DELETE RESTRICT;
CREATE INDEX service_product_use_product_lot_id_ix ON inventory.service_product_use (tenant_id, product_lot_id);
ALTER TABLE inventory.service_product_use ADD CONSTRAINT service_product_use_tenant_fk FOREIGN KEY (tenant_id) REFERENCES core.tenant (tenant_id);
ALTER TABLE inventory.service_product_use ADD CONSTRAINT service_product_use_property_fk FOREIGN KEY (tenant_id, property_id) REFERENCES core.property (tenant_id, property_id);

CREATE TRIGGER inventory_item_touch BEFORE UPDATE ON inventory.inventory_item FOR EACH ROW EXECUTE FUNCTION core.touch_versioned();
CREATE TRIGGER inventory_item_variant_touch BEFORE UPDATE ON inventory.inventory_item_variant FOR EACH ROW EXECUTE FUNCTION core.touch_versioned();
CREATE TRIGGER product_lot_touch BEFORE UPDATE ON inventory.product_lot FOR EACH ROW EXECUTE FUNCTION core.touch_versioned();
CREATE TRIGGER inventory_location_balance_touch BEFORE UPDATE ON inventory.inventory_location_balance FOR EACH ROW EXECUTE FUNCTION core.touch();
CREATE TRIGGER inventory_ledger_entry_append_only BEFORE UPDATE OR DELETE ON inventory.inventory_ledger_entry FOR EACH ROW EXECUTE FUNCTION core.forbid_mutation();
DO $$ BEGIN PERFORM core.ensure_monthly_partitions('inventory.inventory_ledger_entry'::regclass, (date_trunc('month', now() AT TIME ZONE 'UTC') - interval '1 month')::date, 4); END $$;
CREATE TABLE inventory.inventory_ledger_entry_default PARTITION OF inventory.inventory_ledger_entry DEFAULT;
CREATE TRIGGER inventory_transfer_touch BEFORE UPDATE ON inventory.inventory_transfer FOR EACH ROW EXECUTE FUNCTION core.touch_versioned();
CREATE TRIGGER laundry_batch_touch BEFORE UPDATE ON inventory.laundry_batch FOR EACH ROW EXECUTE FUNCTION core.touch_versioned();
CREATE TRIGGER laundry_batch_line_touch BEFORE UPDATE ON inventory.laundry_batch_line FOR EACH ROW EXECUTE FUNCTION core.touch();
CREATE TRIGGER supply_recipe_touch BEFORE UPDATE ON inventory.supply_recipe FOR EACH ROW EXECUTE FUNCTION core.touch_versioned();
CREATE TRIGGER supply_recipe_line_touch BEFORE UPDATE ON inventory.supply_recipe_line FOR EACH ROW EXECUTE FUNCTION core.touch();
CREATE TRIGGER demand_forecast_touch BEFORE UPDATE ON inventory.demand_forecast FOR EACH ROW EXECUTE FUNCTION core.touch_versioned();
CREATE TRIGGER forecast_line_touch BEFORE UPDATE ON inventory.forecast_line FOR EACH ROW EXECUTE FUNCTION core.touch();
CREATE TRIGGER stock_count_touch BEFORE UPDATE ON inventory.stock_count FOR EACH ROW EXECUTE FUNCTION core.touch_versioned();
CREATE TRIGGER service_product_use_append_only BEFORE UPDATE OR DELETE ON inventory.service_product_use FOR EACH ROW EXECUTE FUNCTION core.forbid_mutation();
CREATE UNIQUE INDEX inventory_item_variant_barcode_uq ON inventory.inventory_item_variant (tenant_id, barcode) WHERE barcode IS NOT NULL;
CREATE INDEX inventory_ledger_entry_grain_ix ON inventory.inventory_ledger_entry (tenant_id, property_id, inventory_item_variant_id, location_id, occurred_at);
CREATE INDEX inventory_ledger_entry_source_ix ON inventory.inventory_ledger_entry (tenant_id, source_document_type, source_document_id);
