-- 10 commerce: generated by database/tools/generate.py from database/model/. Do not edit.
-- may reference: catalog, core, guest, inventory, resources, scheduling, visit, workforce

CREATE SCHEMA IF NOT EXISTS commerce AUTHORIZATION spms_owner;

CREATE TABLE commerce.tender_definition (
    tender_definition_id           uuid NOT NULL DEFAULT core.uuid_v7(),
    tenant_id                      uuid NOT NULL,
    property_id                    uuid,
    tender_code                    text NOT NULL,
    tender_name                    text NOT NULL,
    tender_type                    text NOT NULL,
    currency_code                  char(3),
    external_mapping_id            uuid,
    status                         text NOT NULL DEFAULT 'Active',
    effective_from                 timestamptz NOT NULL DEFAULT now(),
    effective_to                   timestamptz,
    source_system                  text NOT NULL DEFAULT 'Spa',
    source_key                     text,
    version                        integer NOT NULL DEFAULT 1,
    created_at                     timestamptz NOT NULL DEFAULT now(),
    created_by                     uuid,
    updated_at                     timestamptz NOT NULL DEFAULT now(),
    updated_by                     uuid,
    correlation_id                 text,
    CONSTRAINT tender_definition_pkey PRIMARY KEY (tender_definition_id),
    CONSTRAINT tender_definition_tender_type_ck CHECK (tender_type IN ('Card', 'Cash', 'RoomCharge', 'GiftCard', 'MemberAccount', 'External')),
    CONSTRAINT tender_definition_currency_code_ck CHECK (currency_code ~ '^[A-Z]{3}$'),
    CONSTRAINT tender_definition_version_ck CHECK (version >= 1),
    CONSTRAINT tender_definition_tenant_identity_uq UNIQUE (tenant_id, tender_definition_id),
    CONSTRAINT tender_definition_status_known CHECK (status IN ('Active', 'Retired')),
    CONSTRAINT tender_definition_effective_range_ck CHECK (effective_to IS NULL OR effective_to > effective_from),
    CONSTRAINT tender_definition_code_uq UNIQUE NULLS NOT DISTINCT (tenant_id, property_id, tender_code)
);

CREATE TABLE commerce.cart (
    cart_id                        uuid NOT NULL DEFAULT core.uuid_v7(),
    tenant_id                      uuid NOT NULL,
    property_id                    uuid NOT NULL,
    guest_id                       uuid,
    appointment_id                 uuid,
    visit_id                       uuid,
    currency_code                  char(3) NOT NULL,
    expires_at                     timestamptz,
    converted_order_id             uuid,
    status                         text NOT NULL DEFAULT 'Open',
    version                        integer NOT NULL DEFAULT 1,
    created_at                     timestamptz NOT NULL DEFAULT now(),
    created_by                     uuid,
    updated_at                     timestamptz NOT NULL DEFAULT now(),
    updated_by                     uuid,
    correlation_id                 text,
    CONSTRAINT cart_pkey PRIMARY KEY (cart_id),
    CONSTRAINT cart_currency_code_ck CHECK (currency_code ~ '^[A-Z]{3}$'),
    CONSTRAINT cart_version_ck CHECK (version >= 1),
    CONSTRAINT cart_tenant_identity_uq UNIQUE (tenant_id, cart_id),
    CONSTRAINT cart_prop_ref_uq UNIQUE (tenant_id, property_id, cart_id),
    CONSTRAINT cart_status_known CHECK (status IN ('Open', 'Converted', 'Abandoned', 'Expired')),
    CONSTRAINT cart_converted_has_order CHECK ((status = 'Converted') = (converted_order_id IS NOT NULL))
);

CREATE TABLE commerce.cart_line (
    cart_line_id                   uuid NOT NULL DEFAULT core.uuid_v7(),
    tenant_id                      uuid NOT NULL,
    property_id                    uuid NOT NULL,
    cart_id                        uuid NOT NULL,
    line_number                    smallint NOT NULL,
    commerce_catalog_item_id       uuid NOT NULL,
    inventory_item_variant_id      uuid,
    appointment_id                 uuid,
    description                    text NOT NULL,
    quantity                       numeric(18,6) NOT NULL DEFAULT 1,
    unit_price_minor               bigint NOT NULL,
    created_at                     timestamptz NOT NULL DEFAULT now(),
    created_by                     uuid,
    updated_at                     timestamptz NOT NULL DEFAULT now(),
    updated_by                     uuid,
    correlation_id                 text,
    CONSTRAINT cart_line_pkey PRIMARY KEY (cart_line_id),
    CONSTRAINT cart_line_line_number_ck CHECK (line_number >= 1),
    CONSTRAINT cart_line_quantity_ck CHECK (quantity > 0),
    CONSTRAINT cart_line_tenant_identity_uq UNIQUE (tenant_id, cart_line_id),
    CONSTRAINT cart_line_number_uq UNIQUE (tenant_id, cart_id, line_number)
);

CREATE TABLE commerce.commerce_order (
    commerce_order_id              uuid NOT NULL DEFAULT core.uuid_v7(),
    tenant_id                      uuid NOT NULL,
    property_id                    uuid NOT NULL,
    order_number                   text,
    guest_id                       uuid,
    appointment_id                 uuid,
    visit_id                       uuid,
    owner_system                   text NOT NULL DEFAULT 'Spa',
    ordered_at                     timestamptz NOT NULL DEFAULT now(),
    currency_code                  char(3) NOT NULL,
    subtotal_minor                 bigint NOT NULL DEFAULT 0,
    discount_total_minor           bigint NOT NULL DEFAULT 0,
    tax_total_minor                bigint NOT NULL DEFAULT 0,
    tip_total_minor                bigint NOT NULL DEFAULT 0,
    total_minor                    bigint NOT NULL DEFAULT 0,
    status                         text NOT NULL DEFAULT 'Draft',
    source_system                  text NOT NULL DEFAULT 'Spa',
    source_key                     text,
    version                        integer NOT NULL DEFAULT 1,
    created_at                     timestamptz NOT NULL DEFAULT now(),
    created_by                     uuid,
    updated_at                     timestamptz NOT NULL DEFAULT now(),
    updated_by                     uuid,
    correlation_id                 text,
    CONSTRAINT commerce_order_pkey PRIMARY KEY (commerce_order_id),
    CONSTRAINT commerce_order_owner_system_ck CHECK (owner_system IN ('Spa', 'Marquee', 'Pos')),
    CONSTRAINT commerce_order_currency_code_ck CHECK (currency_code ~ '^[A-Z]{3}$'),
    CONSTRAINT commerce_order_discount_total_minor_ck CHECK (discount_total_minor >= 0),
    CONSTRAINT commerce_order_tax_total_minor_ck CHECK (tax_total_minor >= 0),
    CONSTRAINT commerce_order_tip_total_minor_ck CHECK (tip_total_minor >= 0),
    CONSTRAINT commerce_order_version_ck CHECK (version >= 1),
    CONSTRAINT commerce_order_tenant_identity_uq UNIQUE (tenant_id, commerce_order_id),
    CONSTRAINT commerce_order_prop_ref_uq UNIQUE (tenant_id, property_id, commerce_order_id),
    CONSTRAINT commerce_order_status_known CHECK (status IN ('Draft', 'Open', 'Delegated', 'PartiallyPaid', 'Paid', 'PartiallyRefunded', 'Refunded', 'Voided')),
    CONSTRAINT commerce_order_delegated_is_external CHECK (status <> 'Delegated' OR owner_system <> 'Spa')
);
COMMENT ON TABLE commerce.commerce_order IS 'When Marquee owns commerce for the property, owner_system = ''Marquee'' and source_key is its order id. [§53.2 Commerce; DEC-001 (owner_system); DEC-002 (Marquee owns delegated commerce)]';

CREATE TABLE commerce.order_line (
    order_line_id                  uuid NOT NULL DEFAULT core.uuid_v7(),
    tenant_id                      uuid NOT NULL,
    property_id                    uuid NOT NULL,
    commerce_order_id              uuid NOT NULL,
    line_number                    smallint NOT NULL,
    line_kind                      text NOT NULL,
    commerce_catalog_item_id       uuid,
    appointment_id                 uuid,
    inventory_item_variant_id      uuid,
    location_id                    uuid,
    product_lot_id                 uuid,
    staff_id                       uuid,
    original_order_line_id         uuid,
    description                    text NOT NULL,
    quantity_sold                  numeric(18,6) NOT NULL,
    unit_price_minor               bigint NOT NULL,
    discount_minor                 bigint NOT NULL DEFAULT 0,
    tax_minor                      bigint NOT NULL DEFAULT 0,
    tip_minor                      bigint NOT NULL DEFAULT 0,
    net_minor                      bigint NOT NULL,
    tax_code                       text,
    revenue_center_code            text,
    fulfilled_at                   timestamptz,
    created_at                     timestamptz NOT NULL DEFAULT now(),
    created_by                     uuid,
    updated_at                     timestamptz NOT NULL DEFAULT now(),
    updated_by                     uuid,
    correlation_id                 text,
    CONSTRAINT order_line_pkey PRIMARY KEY (order_line_id),
    CONSTRAINT order_line_line_number_ck CHECK (line_number >= 1),
    CONSTRAINT order_line_line_kind_ck CHECK (line_kind IN ('Service', 'Retail', 'Fee', 'Deposit', 'Discount', 'Tip')),
    CONSTRAINT order_line_quantity_sold_ck CHECK (quantity_sold <> 0),
    CONSTRAINT order_line_tenant_identity_uq UNIQUE (tenant_id, order_line_id),
    CONSTRAINT order_line_number_uq UNIQUE (tenant_id, commerce_order_id, line_number)
);
COMMENT ON COLUMN commerce.order_line.staff_id IS 'provider credited (commission); workforce is not a commerce dependency';

CREATE TABLE commerce.payment_intent (
    payment_intent_id              uuid NOT NULL DEFAULT core.uuid_v7(),
    tenant_id                      uuid NOT NULL,
    property_id                    uuid NOT NULL,
    commerce_order_id              uuid,
    appointment_id                 uuid,
    purpose                        text NOT NULL,
    amount_minor                   bigint NOT NULL,
    currency_code                  char(3) NOT NULL,
    provider_code                  text NOT NULL,
    provider_reference             text,
    capture_method                 text NOT NULL DEFAULT 'Automatic',
    idempotency_key                text NOT NULL,
    expires_at                     timestamptz,
    status                         text NOT NULL DEFAULT 'RequiresPaymentMethod',
    version                        integer NOT NULL DEFAULT 1,
    created_at                     timestamptz NOT NULL DEFAULT now(),
    created_by                     uuid,
    updated_at                     timestamptz NOT NULL DEFAULT now(),
    updated_by                     uuid,
    correlation_id                 text,
    CONSTRAINT payment_intent_pkey PRIMARY KEY (payment_intent_id),
    CONSTRAINT payment_intent_purpose_ck CHECK (purpose IN ('Deposit', 'Payment', 'NoShowFee', 'CancellationFee')),
    CONSTRAINT payment_intent_amount_minor_ck CHECK (amount_minor > 0),
    CONSTRAINT payment_intent_currency_code_ck CHECK (currency_code ~ '^[A-Z]{3}$'),
    CONSTRAINT payment_intent_capture_method_ck CHECK (capture_method IN ('Automatic', 'Manual')),
    CONSTRAINT payment_intent_version_ck CHECK (version >= 1),
    CONSTRAINT payment_intent_tenant_identity_uq UNIQUE (tenant_id, payment_intent_id),
    CONSTRAINT payment_intent_prop_ref_uq UNIQUE (tenant_id, property_id, payment_intent_id),
    CONSTRAINT payment_intent_status_known CHECK (status IN ('RequiresPaymentMethod', 'RequiresAction', 'Authorized', 'Captured', 'Cancelled', 'Failed', 'Expired')),
    CONSTRAINT payment_intent_has_subject CHECK (num_nonnulls(commerce_order_id, appointment_id) >= 1),
    CONSTRAINT payment_intent_idempotency_uq UNIQUE (tenant_id, idempotency_key)
);
COMMENT ON COLUMN commerce.payment_intent.provider_code IS 'payment adapter, chosen when DEC-010 lands';

CREATE TABLE commerce.payment_transaction (
    payment_transaction_id         uuid NOT NULL DEFAULT core.uuid_v7(),
    tenant_id                      uuid NOT NULL,
    property_id                    uuid NOT NULL,
    payment_intent_id              uuid,
    commerce_order_id              uuid,
    visit_id                       uuid,
    tender_definition_id           uuid NOT NULL,
    transaction_type               text NOT NULL,
    outcome                        text NOT NULL,
    amount_minor                   bigint NOT NULL,
    currency_code                  char(3) NOT NULL,
    provider_code                  text NOT NULL,
    provider_reference             text,
    card_brand                     text,
    card_last4                     char(4),
    processed_at                   timestamptz NOT NULL,
    original_transaction_id        uuid,
    idempotency_key                text NOT NULL,
    created_at                     timestamptz NOT NULL DEFAULT now(),
    created_by                     uuid,
    correlation_id                 text,
    CONSTRAINT payment_transaction_pkey PRIMARY KEY (payment_transaction_id),
    CONSTRAINT payment_transaction_transaction_type_ck CHECK (transaction_type IN ('Authorization', 'Capture', 'Sale', 'Void', 'Refund', 'Chargeback', 'Adjustment')),
    CONSTRAINT payment_transaction_outcome_ck CHECK (outcome IN ('Approved', 'Declined', 'Error', 'Pending', 'Unknown')),
    CONSTRAINT payment_transaction_amount_minor_ck CHECK (amount_minor >= 0),
    CONSTRAINT payment_transaction_currency_code_ck CHECK (currency_code ~ '^[A-Z]{3}$'),
    CONSTRAINT payment_transaction_card_last4_ck CHECK (card_last4 ~ '^[0-9]{4}$'),
    CONSTRAINT payment_transaction_tenant_identity_uq UNIQUE (tenant_id, payment_transaction_id),
    CONSTRAINT payment_transaction_prop_ref_uq UNIQUE (tenant_id, property_id, payment_transaction_id),
    CONSTRAINT payment_transaction_reversal_has_original CHECK (transaction_type NOT IN ('Void', 'Refund', 'Chargeback') OR original_transaction_id IS NOT NULL),
    CONSTRAINT payment_transaction_idempotency_uq UNIQUE (tenant_id, idempotency_key)
);

CREATE TABLE commerce.refund (
    refund_id                      uuid NOT NULL DEFAULT core.uuid_v7(),
    tenant_id                      uuid NOT NULL,
    property_id                    uuid NOT NULL,
    payment_transaction_id         uuid NOT NULL,
    amount_minor                   bigint NOT NULL,
    currency_code                  char(3) NOT NULL,
    reason_code                    text NOT NULL,
    approved_by                    uuid,
    approved_at                    timestamptz,
    provider_reference             text,
    settled_at                     timestamptz,
    idempotency_key                text NOT NULL,
    status                         text NOT NULL DEFAULT 'Requested',
    version                        integer NOT NULL DEFAULT 1,
    created_at                     timestamptz NOT NULL DEFAULT now(),
    created_by                     uuid,
    updated_at                     timestamptz NOT NULL DEFAULT now(),
    updated_by                     uuid,
    correlation_id                 text,
    CONSTRAINT refund_pkey PRIMARY KEY (refund_id),
    CONSTRAINT refund_amount_minor_ck CHECK (amount_minor > 0),
    CONSTRAINT refund_currency_code_ck CHECK (currency_code ~ '^[A-Z]{3}$'),
    CONSTRAINT refund_version_ck CHECK (version >= 1),
    CONSTRAINT refund_tenant_identity_uq UNIQUE (tenant_id, refund_id),
    CONSTRAINT refund_status_known CHECK (status IN ('Requested', 'Approved', 'Rejected', 'Submitted', 'Settled', 'Failed')),
    CONSTRAINT refund_approved_complete CHECK (status NOT IN ('Approved', 'Submitted', 'Settled') OR approved_by IS NOT NULL),
    CONSTRAINT refund_dual_control CHECK (approved_by IS NULL OR approved_by IS DISTINCT FROM created_by),
    CONSTRAINT refund_idempotency_uq UNIQUE (tenant_id, idempotency_key)
);

CREATE TABLE commerce.deposit_ledger_entry (
    deposit_ledger_entry_id        uuid NOT NULL DEFAULT core.uuid_v7(),
    tenant_id                      uuid NOT NULL,
    property_id                    uuid NOT NULL,
    appointment_id                 uuid NOT NULL,
    payment_transaction_id         uuid,
    entry_type                     text NOT NULL,
    amount_minor                   bigint NOT NULL,
    currency_code                  char(3) NOT NULL,
    reason_code                    text,
    created_at                     timestamptz NOT NULL DEFAULT now(),
    created_by                     uuid,
    correlation_id                 text,
    CONSTRAINT deposit_ledger_entry_pkey PRIMARY KEY (deposit_ledger_entry_id),
    CONSTRAINT deposit_ledger_entry_entry_type_ck CHECK (entry_type IN ('Collected', 'Applied', 'Refunded', 'Forfeited')),
    CONSTRAINT deposit_ledger_entry_currency_code_ck CHECK (currency_code ~ '^[A-Z]{3}$'),
    CONSTRAINT deposit_ledger_entry_tenant_identity_uq UNIQUE (tenant_id, deposit_ledger_entry_id),
    CONSTRAINT deposit_ledger_entry_sign_matches_type CHECK ((entry_type = 'Collected') = (amount_minor > 0) AND amount_minor <> 0)
);
COMMENT ON COLUMN commerce.deposit_ledger_entry.amount_minor IS 'signed: Collected positive; Applied/Refunded/Forfeited negative';

CREATE TABLE commerce.receipt (
    receipt_id                     uuid NOT NULL DEFAULT core.uuid_v7(),
    tenant_id                      uuid NOT NULL,
    property_id                    uuid NOT NULL,
    commerce_order_id              uuid NOT NULL,
    receipt_number                 text NOT NULL,
    issued_at                      timestamptz NOT NULL DEFAULT now(),
    delivery_channel               text NOT NULL,
    status                         text NOT NULL DEFAULT 'Issued',
    version                        integer NOT NULL DEFAULT 1,
    created_at                     timestamptz NOT NULL DEFAULT now(),
    created_by                     uuid,
    updated_at                     timestamptz NOT NULL DEFAULT now(),
    updated_by                     uuid,
    correlation_id                 text,
    CONSTRAINT receipt_pkey PRIMARY KEY (receipt_id),
    CONSTRAINT receipt_delivery_channel_ck CHECK (delivery_channel IN ('Print', 'Email', 'Sms')),
    CONSTRAINT receipt_version_ck CHECK (version >= 1),
    CONSTRAINT receipt_tenant_identity_uq UNIQUE (tenant_id, receipt_id),
    CONSTRAINT receipt_status_known CHECK (status IN ('Issued', 'Voided', 'Reissued')),
    CONSTRAINT receipt_number_uq UNIQUE (tenant_id, property_id, receipt_number)
);

CREATE TABLE commerce.commerce_reference (
    reference_id                   uuid NOT NULL DEFAULT core.uuid_v7(),
    tenant_id                      uuid NOT NULL,
    property_id                    uuid NOT NULL,
    appointment_id                 uuid,
    commerce_order_id              uuid,
    capability_code                text NOT NULL,
    owner_system                   text NOT NULL,
    operation                      text NOT NULL,
    external_id                    text,
    amount_minor                   bigint,
    currency_code                  char(3),
    idempotency_key                text NOT NULL,
    last_error                     text,
    status                         text NOT NULL DEFAULT 'Pending',
    version                        integer NOT NULL DEFAULT 1,
    created_at                     timestamptz NOT NULL DEFAULT now(),
    created_by                     uuid,
    updated_at                     timestamptz NOT NULL DEFAULT now(),
    updated_by                     uuid,
    correlation_id                 text,
    CONSTRAINT commerce_reference_pkey PRIMARY KEY (reference_id),
    CONSTRAINT commerce_reference_owner_system_ck CHECK (owner_system IN ('Marquee', 'Pos', 'Pms', 'External')),
    CONSTRAINT commerce_reference_operation_ck CHECK (operation IN ('CreateCart', 'AddLine', 'Checkout', 'Refund', 'Void', 'PostCharge')),
    CONSTRAINT commerce_reference_currency_code_ck CHECK (currency_code ~ '^[A-Z]{3}$'),
    CONSTRAINT commerce_reference_version_ck CHECK (version >= 1),
    CONSTRAINT commerce_reference_tenant_identity_uq UNIQUE (tenant_id, reference_id),
    CONSTRAINT commerce_reference_status_known CHECK (status IN ('Pending', 'Sent', 'Confirmed', 'Failed', 'Ambiguous')),
    CONSTRAINT commerce_reference_idempotency_uq UNIQUE (tenant_id, idempotency_key)
);
COMMENT ON TABLE commerce.commerce_reference IS 'An outbound call to the system that owns commerce, and what came back. [MCI Marquee commerce delegation; OWNERSHIP_AMBIGUOUS]';

CREATE TABLE commerce.visit_charge_reference (
    visit_charge_reference_id      uuid NOT NULL DEFAULT core.uuid_v7(),
    tenant_id                      uuid NOT NULL,
    property_id                    uuid NOT NULL,
    visit_id                       uuid NOT NULL,
    commerce_order_id              uuid,
    payment_transaction_id         uuid,
    charge_role                    text NOT NULL,
    external_folio_reference       text,
    amount_minor                   bigint NOT NULL,
    currency_code                  char(3) NOT NULL,
    reconciled_at                  timestamptz,
    status                         text NOT NULL DEFAULT 'Pending',
    created_at                     timestamptz NOT NULL DEFAULT now(),
    created_by                     uuid,
    updated_at                     timestamptz NOT NULL DEFAULT now(),
    updated_by                     uuid,
    correlation_id                 text,
    CONSTRAINT visit_charge_reference_pkey PRIMARY KEY (visit_charge_reference_id),
    CONSTRAINT visit_charge_reference_charge_role_ck CHECK (charge_role IN ('RoomCharge', 'Folio', 'Direct', 'MemberAccount')),
    CONSTRAINT visit_charge_reference_currency_code_ck CHECK (currency_code ~ '^[A-Z]{3}$'),
    CONSTRAINT visit_charge_reference_tenant_identity_uq UNIQUE (tenant_id, visit_charge_reference_id),
    CONSTRAINT visit_charge_reference_status_known CHECK (status IN ('Pending', 'Posted', 'Reconciled', 'Failed')),
    CONSTRAINT visit_charge_reference_reconciled_complete CHECK ((status = 'Reconciled') = (reconciled_at IS NOT NULL))
);

ALTER TABLE commerce.tender_definition ADD CONSTRAINT tender_definition_external_mapping_id_fk FOREIGN KEY (tenant_id, external_mapping_id) REFERENCES core.external_mapping (tenant_id, external_mapping_id) ON DELETE RESTRICT;
CREATE INDEX tender_definition_external_mapping_id_ix ON commerce.tender_definition (tenant_id, external_mapping_id);
ALTER TABLE commerce.tender_definition ADD CONSTRAINT tender_definition_tenant_fk FOREIGN KEY (tenant_id) REFERENCES core.tenant (tenant_id);
ALTER TABLE commerce.tender_definition ADD CONSTRAINT tender_definition_property_fk FOREIGN KEY (tenant_id, property_id) REFERENCES core.property (tenant_id, property_id);
ALTER TABLE commerce.cart ADD CONSTRAINT cart_guest_id_fk FOREIGN KEY (tenant_id, guest_id) REFERENCES guest.guest (tenant_id, guest_id) ON DELETE RESTRICT;
CREATE INDEX cart_guest_id_ix ON commerce.cart (tenant_id, guest_id);
ALTER TABLE commerce.cart ADD CONSTRAINT cart_appointment_id_fk FOREIGN KEY (tenant_id, property_id, appointment_id) REFERENCES scheduling.appointment (tenant_id, property_id, appointment_id) ON DELETE RESTRICT;
CREATE INDEX cart_appointment_id_ix ON commerce.cart (tenant_id, property_id, appointment_id);
ALTER TABLE commerce.cart ADD CONSTRAINT cart_visit_id_fk FOREIGN KEY (tenant_id, property_id, visit_id) REFERENCES visit.visit (tenant_id, property_id, visit_id) ON DELETE RESTRICT;
CREATE INDEX cart_visit_id_ix ON commerce.cart (tenant_id, property_id, visit_id);
ALTER TABLE commerce.cart ADD CONSTRAINT cart_converted_order_id_fk FOREIGN KEY (tenant_id, property_id, converted_order_id) REFERENCES commerce.commerce_order (tenant_id, property_id, commerce_order_id) ON DELETE RESTRICT;
CREATE INDEX cart_converted_order_id_ix ON commerce.cart (tenant_id, property_id, converted_order_id);
ALTER TABLE commerce.cart ADD CONSTRAINT cart_tenant_fk FOREIGN KEY (tenant_id) REFERENCES core.tenant (tenant_id);
ALTER TABLE commerce.cart ADD CONSTRAINT cart_property_fk FOREIGN KEY (tenant_id, property_id) REFERENCES core.property (tenant_id, property_id);
ALTER TABLE commerce.cart_line ADD CONSTRAINT cart_line_cart_id_fk FOREIGN KEY (tenant_id, property_id, cart_id) REFERENCES commerce.cart (tenant_id, property_id, cart_id) ON DELETE RESTRICT;
CREATE INDEX cart_line_cart_id_ix ON commerce.cart_line (tenant_id, property_id, cart_id);
ALTER TABLE commerce.cart_line ADD CONSTRAINT cart_line_commerce_catalog_item_id_fk FOREIGN KEY (tenant_id, commerce_catalog_item_id) REFERENCES catalog.commerce_catalog_item (tenant_id, commerce_catalog_item_id) ON DELETE RESTRICT;
CREATE INDEX cart_line_commerce_catalog_item_id_ix ON commerce.cart_line (tenant_id, commerce_catalog_item_id);
ALTER TABLE commerce.cart_line ADD CONSTRAINT cart_line_inventory_item_variant_id_fk FOREIGN KEY (tenant_id, inventory_item_variant_id) REFERENCES inventory.inventory_item_variant (tenant_id, inventory_item_variant_id) ON DELETE RESTRICT;
CREATE INDEX cart_line_inventory_item_variant_id_ix ON commerce.cart_line (tenant_id, inventory_item_variant_id);
ALTER TABLE commerce.cart_line ADD CONSTRAINT cart_line_appointment_id_fk FOREIGN KEY (tenant_id, property_id, appointment_id) REFERENCES scheduling.appointment (tenant_id, property_id, appointment_id) ON DELETE RESTRICT;
CREATE INDEX cart_line_appointment_id_ix ON commerce.cart_line (tenant_id, property_id, appointment_id);
ALTER TABLE commerce.cart_line ADD CONSTRAINT cart_line_tenant_fk FOREIGN KEY (tenant_id) REFERENCES core.tenant (tenant_id);
ALTER TABLE commerce.cart_line ADD CONSTRAINT cart_line_property_fk FOREIGN KEY (tenant_id, property_id) REFERENCES core.property (tenant_id, property_id);
ALTER TABLE commerce.commerce_order ADD CONSTRAINT commerce_order_guest_id_fk FOREIGN KEY (tenant_id, guest_id) REFERENCES guest.guest (tenant_id, guest_id) ON DELETE RESTRICT;
CREATE INDEX commerce_order_guest_id_ix ON commerce.commerce_order (tenant_id, guest_id);
ALTER TABLE commerce.commerce_order ADD CONSTRAINT commerce_order_appointment_id_fk FOREIGN KEY (tenant_id, property_id, appointment_id) REFERENCES scheduling.appointment (tenant_id, property_id, appointment_id) ON DELETE RESTRICT;
CREATE INDEX commerce_order_appointment_id_ix ON commerce.commerce_order (tenant_id, property_id, appointment_id);
ALTER TABLE commerce.commerce_order ADD CONSTRAINT commerce_order_visit_id_fk FOREIGN KEY (tenant_id, property_id, visit_id) REFERENCES visit.visit (tenant_id, property_id, visit_id) ON DELETE RESTRICT;
CREATE INDEX commerce_order_visit_id_ix ON commerce.commerce_order (tenant_id, property_id, visit_id);
ALTER TABLE commerce.commerce_order ADD CONSTRAINT commerce_order_tenant_fk FOREIGN KEY (tenant_id) REFERENCES core.tenant (tenant_id);
ALTER TABLE commerce.commerce_order ADD CONSTRAINT commerce_order_property_fk FOREIGN KEY (tenant_id, property_id) REFERENCES core.property (tenant_id, property_id);
ALTER TABLE commerce.order_line ADD CONSTRAINT order_line_commerce_order_id_fk FOREIGN KEY (tenant_id, property_id, commerce_order_id) REFERENCES commerce.commerce_order (tenant_id, property_id, commerce_order_id) ON DELETE RESTRICT;
CREATE INDEX order_line_commerce_order_id_ix ON commerce.order_line (tenant_id, property_id, commerce_order_id);
ALTER TABLE commerce.order_line ADD CONSTRAINT order_line_commerce_catalog_item_id_fk FOREIGN KEY (tenant_id, commerce_catalog_item_id) REFERENCES catalog.commerce_catalog_item (tenant_id, commerce_catalog_item_id) ON DELETE RESTRICT;
CREATE INDEX order_line_commerce_catalog_item_id_ix ON commerce.order_line (tenant_id, commerce_catalog_item_id);
ALTER TABLE commerce.order_line ADD CONSTRAINT order_line_appointment_id_fk FOREIGN KEY (tenant_id, property_id, appointment_id) REFERENCES scheduling.appointment (tenant_id, property_id, appointment_id) ON DELETE RESTRICT;
CREATE INDEX order_line_appointment_id_ix ON commerce.order_line (tenant_id, property_id, appointment_id);
ALTER TABLE commerce.order_line ADD CONSTRAINT order_line_inventory_item_variant_id_fk FOREIGN KEY (tenant_id, inventory_item_variant_id) REFERENCES inventory.inventory_item_variant (tenant_id, inventory_item_variant_id) ON DELETE RESTRICT;
CREATE INDEX order_line_inventory_item_variant_id_ix ON commerce.order_line (tenant_id, inventory_item_variant_id);
ALTER TABLE commerce.order_line ADD CONSTRAINT order_line_location_id_fk FOREIGN KEY (tenant_id, property_id, location_id) REFERENCES resources.location (tenant_id, property_id, location_id) ON DELETE RESTRICT;
CREATE INDEX order_line_location_id_ix ON commerce.order_line (tenant_id, property_id, location_id);
ALTER TABLE commerce.order_line ADD CONSTRAINT order_line_product_lot_id_fk FOREIGN KEY (tenant_id, product_lot_id) REFERENCES inventory.product_lot (tenant_id, product_lot_id) ON DELETE RESTRICT;
CREATE INDEX order_line_product_lot_id_ix ON commerce.order_line (tenant_id, product_lot_id);
ALTER TABLE commerce.order_line ADD CONSTRAINT order_line_original_order_line_id_fk FOREIGN KEY (tenant_id, original_order_line_id) REFERENCES commerce.order_line (tenant_id, order_line_id) ON DELETE RESTRICT;
CREATE INDEX order_line_original_order_line_id_ix ON commerce.order_line (tenant_id, original_order_line_id);
ALTER TABLE commerce.order_line ADD CONSTRAINT order_line_tenant_fk FOREIGN KEY (tenant_id) REFERENCES core.tenant (tenant_id);
ALTER TABLE commerce.order_line ADD CONSTRAINT order_line_property_fk FOREIGN KEY (tenant_id, property_id) REFERENCES core.property (tenant_id, property_id);
ALTER TABLE commerce.payment_intent ADD CONSTRAINT payment_intent_commerce_order_id_fk FOREIGN KEY (tenant_id, property_id, commerce_order_id) REFERENCES commerce.commerce_order (tenant_id, property_id, commerce_order_id) ON DELETE RESTRICT;
CREATE INDEX payment_intent_commerce_order_id_ix ON commerce.payment_intent (tenant_id, property_id, commerce_order_id);
ALTER TABLE commerce.payment_intent ADD CONSTRAINT payment_intent_appointment_id_fk FOREIGN KEY (tenant_id, property_id, appointment_id) REFERENCES scheduling.appointment (tenant_id, property_id, appointment_id) ON DELETE RESTRICT;
CREATE INDEX payment_intent_appointment_id_ix ON commerce.payment_intent (tenant_id, property_id, appointment_id);
ALTER TABLE commerce.payment_intent ADD CONSTRAINT payment_intent_tenant_fk FOREIGN KEY (tenant_id) REFERENCES core.tenant (tenant_id);
ALTER TABLE commerce.payment_intent ADD CONSTRAINT payment_intent_property_fk FOREIGN KEY (tenant_id, property_id) REFERENCES core.property (tenant_id, property_id);
ALTER TABLE commerce.payment_transaction ADD CONSTRAINT payment_transaction_payment_intent_id_fk FOREIGN KEY (tenant_id, property_id, payment_intent_id) REFERENCES commerce.payment_intent (tenant_id, property_id, payment_intent_id) ON DELETE RESTRICT;
CREATE INDEX payment_transaction_payment_intent_id_ix ON commerce.payment_transaction (tenant_id, property_id, payment_intent_id);
ALTER TABLE commerce.payment_transaction ADD CONSTRAINT payment_transaction_commerce_order_id_fk FOREIGN KEY (tenant_id, property_id, commerce_order_id) REFERENCES commerce.commerce_order (tenant_id, property_id, commerce_order_id) ON DELETE RESTRICT;
CREATE INDEX payment_transaction_commerce_order_id_ix ON commerce.payment_transaction (tenant_id, property_id, commerce_order_id);
ALTER TABLE commerce.payment_transaction ADD CONSTRAINT payment_transaction_visit_id_fk FOREIGN KEY (tenant_id, property_id, visit_id) REFERENCES visit.visit (tenant_id, property_id, visit_id) ON DELETE RESTRICT;
CREATE INDEX payment_transaction_visit_id_ix ON commerce.payment_transaction (tenant_id, property_id, visit_id);
ALTER TABLE commerce.payment_transaction ADD CONSTRAINT payment_transaction_tender_definition_id_fk FOREIGN KEY (tenant_id, tender_definition_id) REFERENCES commerce.tender_definition (tenant_id, tender_definition_id) ON DELETE RESTRICT;
CREATE INDEX payment_transaction_tender_definition_id_ix ON commerce.payment_transaction (tenant_id, tender_definition_id);
ALTER TABLE commerce.payment_transaction ADD CONSTRAINT payment_transaction_original_transaction_id_fk FOREIGN KEY (tenant_id, original_transaction_id) REFERENCES commerce.payment_transaction (tenant_id, payment_transaction_id) ON DELETE RESTRICT;
CREATE INDEX payment_transaction_original_transaction_id_ix ON commerce.payment_transaction (tenant_id, original_transaction_id);
ALTER TABLE commerce.payment_transaction ADD CONSTRAINT payment_transaction_tenant_fk FOREIGN KEY (tenant_id) REFERENCES core.tenant (tenant_id);
ALTER TABLE commerce.payment_transaction ADD CONSTRAINT payment_transaction_property_fk FOREIGN KEY (tenant_id, property_id) REFERENCES core.property (tenant_id, property_id);
ALTER TABLE commerce.refund ADD CONSTRAINT refund_payment_transaction_id_fk FOREIGN KEY (tenant_id, property_id, payment_transaction_id) REFERENCES commerce.payment_transaction (tenant_id, property_id, payment_transaction_id) ON DELETE RESTRICT;
CREATE INDEX refund_payment_transaction_id_ix ON commerce.refund (tenant_id, property_id, payment_transaction_id);
ALTER TABLE commerce.refund ADD CONSTRAINT refund_tenant_fk FOREIGN KEY (tenant_id) REFERENCES core.tenant (tenant_id);
ALTER TABLE commerce.refund ADD CONSTRAINT refund_property_fk FOREIGN KEY (tenant_id, property_id) REFERENCES core.property (tenant_id, property_id);
ALTER TABLE commerce.deposit_ledger_entry ADD CONSTRAINT deposit_ledger_entry_appointment_id_fk FOREIGN KEY (tenant_id, property_id, appointment_id) REFERENCES scheduling.appointment (tenant_id, property_id, appointment_id) ON DELETE RESTRICT;
CREATE INDEX deposit_ledger_entry_appointment_id_ix ON commerce.deposit_ledger_entry (tenant_id, property_id, appointment_id);
ALTER TABLE commerce.deposit_ledger_entry ADD CONSTRAINT deposit_ledger_entry_payment_transaction_id_fk FOREIGN KEY (tenant_id, property_id, payment_transaction_id) REFERENCES commerce.payment_transaction (tenant_id, property_id, payment_transaction_id) ON DELETE RESTRICT;
CREATE INDEX deposit_ledger_entry_payment_transaction_id_ix ON commerce.deposit_ledger_entry (tenant_id, property_id, payment_transaction_id);
ALTER TABLE commerce.deposit_ledger_entry ADD CONSTRAINT deposit_ledger_entry_tenant_fk FOREIGN KEY (tenant_id) REFERENCES core.tenant (tenant_id);
ALTER TABLE commerce.deposit_ledger_entry ADD CONSTRAINT deposit_ledger_entry_property_fk FOREIGN KEY (tenant_id, property_id) REFERENCES core.property (tenant_id, property_id);
ALTER TABLE commerce.receipt ADD CONSTRAINT receipt_commerce_order_id_fk FOREIGN KEY (tenant_id, property_id, commerce_order_id) REFERENCES commerce.commerce_order (tenant_id, property_id, commerce_order_id) ON DELETE RESTRICT;
CREATE INDEX receipt_commerce_order_id_ix ON commerce.receipt (tenant_id, property_id, commerce_order_id);
ALTER TABLE commerce.receipt ADD CONSTRAINT receipt_tenant_fk FOREIGN KEY (tenant_id) REFERENCES core.tenant (tenant_id);
ALTER TABLE commerce.receipt ADD CONSTRAINT receipt_property_fk FOREIGN KEY (tenant_id, property_id) REFERENCES core.property (tenant_id, property_id);
ALTER TABLE commerce.commerce_reference ADD CONSTRAINT commerce_reference_appointment_id_fk FOREIGN KEY (tenant_id, property_id, appointment_id) REFERENCES scheduling.appointment (tenant_id, property_id, appointment_id) ON DELETE RESTRICT;
CREATE INDEX commerce_reference_appointment_id_ix ON commerce.commerce_reference (tenant_id, property_id, appointment_id);
ALTER TABLE commerce.commerce_reference ADD CONSTRAINT commerce_reference_commerce_order_id_fk FOREIGN KEY (tenant_id, property_id, commerce_order_id) REFERENCES commerce.commerce_order (tenant_id, property_id, commerce_order_id) ON DELETE RESTRICT;
CREATE INDEX commerce_reference_commerce_order_id_ix ON commerce.commerce_reference (tenant_id, property_id, commerce_order_id);
ALTER TABLE commerce.commerce_reference ADD CONSTRAINT commerce_reference_tenant_fk FOREIGN KEY (tenant_id) REFERENCES core.tenant (tenant_id);
ALTER TABLE commerce.commerce_reference ADD CONSTRAINT commerce_reference_property_fk FOREIGN KEY (tenant_id, property_id) REFERENCES core.property (tenant_id, property_id);
ALTER TABLE commerce.visit_charge_reference ADD CONSTRAINT visit_charge_reference_visit_id_fk FOREIGN KEY (tenant_id, property_id, visit_id) REFERENCES visit.visit (tenant_id, property_id, visit_id) ON DELETE RESTRICT;
CREATE INDEX visit_charge_reference_visit_id_ix ON commerce.visit_charge_reference (tenant_id, property_id, visit_id);
ALTER TABLE commerce.visit_charge_reference ADD CONSTRAINT visit_charge_reference_commerce_order_id_fk FOREIGN KEY (tenant_id, property_id, commerce_order_id) REFERENCES commerce.commerce_order (tenant_id, property_id, commerce_order_id) ON DELETE RESTRICT;
CREATE INDEX visit_charge_reference_commerce_order_id_ix ON commerce.visit_charge_reference (tenant_id, property_id, commerce_order_id);
ALTER TABLE commerce.visit_charge_reference ADD CONSTRAINT visit_charge_reference_payment_transaction_id_fk FOREIGN KEY (tenant_id, property_id, payment_transaction_id) REFERENCES commerce.payment_transaction (tenant_id, property_id, payment_transaction_id) ON DELETE RESTRICT;
CREATE INDEX visit_charge_reference_payment_transaction_id_ix ON commerce.visit_charge_reference (tenant_id, property_id, payment_transaction_id);
ALTER TABLE commerce.visit_charge_reference ADD CONSTRAINT visit_charge_reference_tenant_fk FOREIGN KEY (tenant_id) REFERENCES core.tenant (tenant_id);
ALTER TABLE commerce.visit_charge_reference ADD CONSTRAINT visit_charge_reference_property_fk FOREIGN KEY (tenant_id, property_id) REFERENCES core.property (tenant_id, property_id);

CREATE TRIGGER tender_definition_touch BEFORE UPDATE ON commerce.tender_definition FOR EACH ROW EXECUTE FUNCTION core.touch_versioned();
CREATE TRIGGER cart_touch BEFORE UPDATE ON commerce.cart FOR EACH ROW EXECUTE FUNCTION core.touch_versioned();
CREATE TRIGGER cart_line_touch BEFORE UPDATE ON commerce.cart_line FOR EACH ROW EXECUTE FUNCTION core.touch();
CREATE TRIGGER commerce_order_touch BEFORE UPDATE ON commerce.commerce_order FOR EACH ROW EXECUTE FUNCTION core.touch_versioned();
CREATE TRIGGER order_line_touch BEFORE UPDATE ON commerce.order_line FOR EACH ROW EXECUTE FUNCTION core.touch();
CREATE TRIGGER payment_intent_touch BEFORE UPDATE ON commerce.payment_intent FOR EACH ROW EXECUTE FUNCTION core.touch_versioned();
CREATE TRIGGER payment_transaction_append_only BEFORE UPDATE OR DELETE ON commerce.payment_transaction FOR EACH ROW EXECUTE FUNCTION core.forbid_mutation();
CREATE TRIGGER refund_touch BEFORE UPDATE ON commerce.refund FOR EACH ROW EXECUTE FUNCTION core.touch_versioned();
CREATE TRIGGER deposit_ledger_entry_append_only BEFORE UPDATE OR DELETE ON commerce.deposit_ledger_entry FOR EACH ROW EXECUTE FUNCTION core.forbid_mutation();
CREATE TRIGGER receipt_touch BEFORE UPDATE ON commerce.receipt FOR EACH ROW EXECUTE FUNCTION core.touch_versioned();
CREATE TRIGGER commerce_reference_touch BEFORE UPDATE ON commerce.commerce_reference FOR EACH ROW EXECUTE FUNCTION core.touch_versioned();
CREATE TRIGGER visit_charge_reference_touch BEFORE UPDATE ON commerce.visit_charge_reference FOR EACH ROW EXECUTE FUNCTION core.touch();
CREATE UNIQUE INDEX commerce_order_number_uq ON commerce.commerce_order (tenant_id, property_id, order_number) WHERE order_number IS NOT NULL;
CREATE UNIQUE INDEX payment_intent_provider_uq ON commerce.payment_intent (tenant_id, provider_code, provider_reference) WHERE provider_reference IS NOT NULL;
