-- 11 reporting: generated by database/tools/generate.py from database/model/. Do not edit.
-- may reference: core

CREATE SCHEMA IF NOT EXISTS reporting AUTHORIZATION spms_owner;

CREATE TABLE reporting.report_run (
    report_run_id                  uuid NOT NULL DEFAULT core.uuid_v7(),
    tenant_id                      uuid NOT NULL,
    property_id                    uuid,
    report_id                      text NOT NULL,
    definition_version             text NOT NULL,
    definition_sha256              char(64) NOT NULL,
    filters                        jsonb NOT NULL DEFAULT '{}',
    as_of                          timestamptz NOT NULL,
    result_json                    jsonb,
    result_sha256                  char(64),
    error_code                     text,
    started_at                     timestamptz,
    completed_at                   timestamptz,
    expires_at                     timestamptz NOT NULL,
    is_closed_snapshot             boolean NOT NULL DEFAULT false,
    status                         text NOT NULL DEFAULT 'Queued',
    version                        integer NOT NULL DEFAULT 1,
    created_at                     timestamptz NOT NULL DEFAULT now(),
    created_by                     uuid,
    updated_at                     timestamptz NOT NULL DEFAULT now(),
    updated_by                     uuid,
    correlation_id                 text,
    CONSTRAINT report_run_pkey PRIMARY KEY (report_run_id),
    CONSTRAINT report_run_version_ck CHECK (version >= 1),
    CONSTRAINT report_run_tenant_identity_uq UNIQUE (tenant_id, report_run_id),
    CONSTRAINT report_run_status_known CHECK (status IN ('Queued', 'Running', 'Succeeded', 'Failed', 'Expired')),
    CONSTRAINT report_run_succeeded_complete CHECK (status <> 'Succeeded' OR (result_sha256 IS NOT NULL AND completed_at IS NOT NULL))
);

CREATE INDEX report_run_scope_ix ON reporting.report_run (tenant_id, property_id);
ALTER TABLE reporting.report_run ADD CONSTRAINT report_run_tenant_fk FOREIGN KEY (tenant_id) REFERENCES core.tenant (tenant_id);
ALTER TABLE reporting.report_run ADD CONSTRAINT report_run_property_fk FOREIGN KEY (tenant_id, property_id) REFERENCES core.property (tenant_id, property_id);

CREATE TRIGGER report_run_touch BEFORE UPDATE ON reporting.report_run FOR EACH ROW EXECUTE FUNCTION core.touch_versioned();
