-- 11 messaging: generated by database/tools/generate.py from database/model/. Do not edit.
-- may reference: catalog, core, guest, resources, scheduling, workforce

CREATE SCHEMA IF NOT EXISTS messaging AUTHORIZATION spms_owner;

CREATE TABLE messaging.message_template (
    message_template_id            uuid NOT NULL DEFAULT core.uuid_v7(),
    tenant_id                      uuid NOT NULL,
    property_id                    uuid,
    template_code                  text NOT NULL,
    purpose                        text NOT NULL,
    channel                        text NOT NULL,
    status                         text NOT NULL DEFAULT 'Draft',
    effective_from                 timestamptz NOT NULL DEFAULT now(),
    effective_to                   timestamptz,
    source_system                  text NOT NULL DEFAULT 'Spa',
    source_key                     text,
    version                        integer NOT NULL DEFAULT 1,
    created_at                     timestamptz NOT NULL DEFAULT now(),
    created_by                     uuid,
    updated_at                     timestamptz NOT NULL DEFAULT now(),
    updated_by                     uuid,
    correlation_id                 text,
    CONSTRAINT message_template_pkey PRIMARY KEY (message_template_id),
    CONSTRAINT message_template_purpose_ck CHECK (purpose IN ('Confirmation', 'Reminder', 'Cancellation', 'IntakeRequest', 'Receipt', 'Waitlist', 'Marketing', 'Transactional')),
    CONSTRAINT message_template_channel_ck CHECK (channel IN ('Email', 'Sms', 'WhatsApp', 'Push')),
    CONSTRAINT message_template_version_ck CHECK (version >= 1),
    CONSTRAINT message_template_tenant_identity_uq UNIQUE (tenant_id, message_template_id),
    CONSTRAINT message_template_status_known CHECK (status IN ('Draft', 'Active', 'Retired')),
    CONSTRAINT message_template_effective_range_ck CHECK (effective_to IS NULL OR effective_to > effective_from),
    CONSTRAINT message_template_code_uq UNIQUE NULLS NOT DISTINCT (tenant_id, property_id, template_code, channel)
);

CREATE TABLE messaging.message_template_version (
    message_template_version_id    uuid NOT NULL DEFAULT core.uuid_v7(),
    tenant_id                      uuid NOT NULL,
    property_id                    uuid,
    message_template_id            uuid NOT NULL,
    version_number                 integer NOT NULL,
    locale                         text NOT NULL,
    subject                        text,
    body_template                  text NOT NULL,
    variables                      text[] NOT NULL DEFAULT '{}',
    provider_template_reference    text,
    approved_by                    uuid,
    approved_at                    timestamptz,
    status                         text NOT NULL DEFAULT 'Draft',
    effective_from                 timestamptz NOT NULL DEFAULT now(),
    effective_to                   timestamptz,
    source_system                  text NOT NULL DEFAULT 'Spa',
    source_key                     text,
    version                        integer NOT NULL DEFAULT 1,
    created_at                     timestamptz NOT NULL DEFAULT now(),
    created_by                     uuid,
    updated_at                     timestamptz NOT NULL DEFAULT now(),
    updated_by                     uuid,
    correlation_id                 text,
    CONSTRAINT message_template_version_pkey PRIMARY KEY (message_template_version_id),
    CONSTRAINT message_template_version_version_number_ck CHECK (version_number >= 1),
    CONSTRAINT message_template_version_version_ck CHECK (version >= 1),
    CONSTRAINT message_template_version_tenant_identity_uq UNIQUE (tenant_id, message_template_version_id),
    CONSTRAINT message_template_version_status_known CHECK (status IN ('Draft', 'Approved', 'Active', 'Retired')),
    CONSTRAINT message_template_version_effective_range_ck CHECK (effective_to IS NULL OR effective_to > effective_from),
    CONSTRAINT message_template_version_active_is_approved CHECK (status NOT IN ('Approved', 'Active') OR approved_by IS NOT NULL),
    CONSTRAINT message_template_version_number_uq UNIQUE (tenant_id, message_template_id, locale, version_number)
);
COMMENT ON COLUMN messaging.message_template_version.provider_template_reference IS 'WhatsApp/SMS provider-approved template id';

CREATE TABLE messaging.reminder_rule (
    reminder_rule_id               uuid NOT NULL DEFAULT core.uuid_v7(),
    tenant_id                      uuid NOT NULL,
    property_id                    uuid,
    message_template_id            uuid NOT NULL,
    service_id                     uuid,
    trigger_event                  text NOT NULL,
    offset_minutes                 integer NOT NULL,
    respect_quiet_hours            boolean NOT NULL DEFAULT true,
    quiet_hours_start              time,
    quiet_hours_end                time,
    status                         text NOT NULL DEFAULT 'Active',
    effective_from                 timestamptz NOT NULL DEFAULT now(),
    effective_to                   timestamptz,
    source_system                  text NOT NULL DEFAULT 'Spa',
    source_key                     text,
    version                        integer NOT NULL DEFAULT 1,
    created_at                     timestamptz NOT NULL DEFAULT now(),
    created_by                     uuid,
    updated_at                     timestamptz NOT NULL DEFAULT now(),
    updated_by                     uuid,
    correlation_id                 text,
    CONSTRAINT reminder_rule_pkey PRIMARY KEY (reminder_rule_id),
    CONSTRAINT reminder_rule_trigger_event_ck CHECK (trigger_event IN ('AppointmentConfirmed', 'BeforeStart', 'AfterCompletion', 'IntakeDue', 'WaitlistOffer')),
    CONSTRAINT reminder_rule_version_ck CHECK (version >= 1),
    CONSTRAINT reminder_rule_tenant_identity_uq UNIQUE (tenant_id, reminder_rule_id),
    CONSTRAINT reminder_rule_status_known CHECK (status IN ('Active', 'Retired')),
    CONSTRAINT reminder_rule_effective_range_ck CHECK (effective_to IS NULL OR effective_to > effective_from),
    CONSTRAINT reminder_rule_quiet_pair CHECK ((quiet_hours_start IS NULL) = (quiet_hours_end IS NULL))
);
COMMENT ON COLUMN messaging.reminder_rule.service_id IS 'NULL = every service';
COMMENT ON COLUMN messaging.reminder_rule.offset_minutes IS 'negative = before the event';

CREATE TABLE messaging.scheduled_message (
    scheduled_message_id           uuid NOT NULL DEFAULT core.uuid_v7(),
    tenant_id                      uuid NOT NULL,
    property_id                    uuid NOT NULL,
    guest_id                       uuid NOT NULL,
    appointment_id                 uuid,
    message_template_version_id    uuid NOT NULL,
    reminder_rule_id               uuid,
    consent_record_id              uuid,
    channel                        text NOT NULL,
    recipient_address_cipher       bytea NOT NULL,
    key_version                    text NOT NULL,
    send_after                     timestamptz NOT NULL,
    expires_at                     timestamptz,
    status                         text NOT NULL DEFAULT 'Scheduled',
    version                        integer NOT NULL DEFAULT 1,
    created_at                     timestamptz NOT NULL DEFAULT now(),
    created_by                     uuid,
    updated_at                     timestamptz NOT NULL DEFAULT now(),
    updated_by                     uuid,
    correlation_id                 text,
    CONSTRAINT scheduled_message_pkey PRIMARY KEY (scheduled_message_id),
    CONSTRAINT scheduled_message_channel_ck CHECK (channel IN ('Email', 'Sms', 'WhatsApp', 'Push')),
    CONSTRAINT scheduled_message_version_ck CHECK (version >= 1),
    CONSTRAINT scheduled_message_tenant_identity_uq UNIQUE (tenant_id, scheduled_message_id),
    CONSTRAINT scheduled_message_prop_ref_uq UNIQUE (tenant_id, property_id, scheduled_message_id),
    CONSTRAINT scheduled_message_status_known CHECK (status IN ('Scheduled', 'Sending', 'Sent', 'Cancelled', 'Expired', 'Suppressed'))
);
COMMENT ON COLUMN messaging.scheduled_message.consent_record_id IS 'required for Marketing purpose templates';

CREATE TABLE messaging.message_delivery (
    delivery_id                    uuid NOT NULL DEFAULT core.uuid_v7(),
    tenant_id                      uuid NOT NULL,
    property_id                    uuid NOT NULL,
    scheduled_message_id           uuid NOT NULL,
    provider_code                  text NOT NULL,
    provider_message_id            text,
    delivery_state                 text NOT NULL,
    attempt_number                 smallint NOT NULL DEFAULT 1,
    provider_event_at              timestamptz,
    error_code                     text,
    idempotency_key                text NOT NULL,
    occurred_at                    timestamptz NOT NULL DEFAULT now(),
    created_by                     uuid,
    correlation_id                 text,
    CONSTRAINT message_delivery_pkey PRIMARY KEY (delivery_id, occurred_at),
    CONSTRAINT message_delivery_delivery_state_ck CHECK (delivery_state IN ('Queued', 'Sent', 'Delivered', 'Failed', 'Bounced', 'Undeliverable')),
    CONSTRAINT message_delivery_attempt_number_ck CHECK (attempt_number >= 1)
) PARTITION BY RANGE (occurred_at);
COMMENT ON TABLE messaging.message_delivery IS 'One row per delivery event (queued, sent, delivered, failed...). [delivery status callbacks]';

CREATE TABLE messaging.message_suppression (
    message_suppression_id         uuid NOT NULL DEFAULT core.uuid_v7(),
    tenant_id                      uuid NOT NULL,
    guest_id                       uuid,
    lookup_hash                    char(64),
    channel                        text NOT NULL,
    suppression_reason             text NOT NULL,
    status                         text NOT NULL DEFAULT 'Active',
    effective_from                 timestamptz NOT NULL DEFAULT now(),
    effective_to                   timestamptz,
    source_system                  text NOT NULL DEFAULT 'Spa',
    source_key                     text,
    version                        integer NOT NULL DEFAULT 1,
    created_at                     timestamptz NOT NULL DEFAULT now(),
    created_by                     uuid,
    updated_at                     timestamptz NOT NULL DEFAULT now(),
    updated_by                     uuid,
    correlation_id                 text,
    CONSTRAINT message_suppression_pkey PRIMARY KEY (message_suppression_id),
    CONSTRAINT message_suppression_channel_ck CHECK (channel IN ('Email', 'Sms', 'WhatsApp', 'Push')),
    CONSTRAINT message_suppression_suppression_reason_ck CHECK (suppression_reason IN ('OptOut', 'Bounce', 'Complaint', 'DoNotContact', 'Legal')),
    CONSTRAINT message_suppression_version_ck CHECK (version >= 1),
    CONSTRAINT message_suppression_tenant_identity_uq UNIQUE (tenant_id, message_suppression_id),
    CONSTRAINT message_suppression_status_known CHECK (status IN ('Active', 'Lifted')),
    CONSTRAINT message_suppression_effective_range_ck CHECK (effective_to IS NULL OR effective_to > effective_from),
    CONSTRAINT message_suppression_has_subject CHECK (num_nonnulls(guest_id, lookup_hash) >= 1)
);
COMMENT ON COLUMN messaging.message_suppression.lookup_hash IS 'address-level suppression for an unknown sender';

CREATE TABLE messaging.inbound_message (
    inbound_message_id             uuid NOT NULL DEFAULT core.uuid_v7(),
    tenant_id                      uuid NOT NULL,
    property_id                    uuid NOT NULL,
    guest_id                       uuid,
    in_reply_to_scheduled_message_id uuid,
    channel                        text NOT NULL,
    provider_message_id            text NOT NULL,
    sender_address_cipher          bytea NOT NULL,
    content_cipher                 bytea NOT NULL,
    key_version                    text NOT NULL,
    classification                 text NOT NULL DEFAULT 'Unknown',
    received_at                    timestamptz NOT NULL DEFAULT now(),
    created_by                     uuid,
    correlation_id                 text,
    CONSTRAINT inbound_message_pkey PRIMARY KEY (inbound_message_id),
    CONSTRAINT inbound_message_channel_ck CHECK (channel IN ('Email', 'Sms', 'WhatsApp', 'Push')),
    CONSTRAINT inbound_message_classification_ck CHECK (classification IN ('Reply', 'OptOut', 'OptIn', 'Unknown')),
    CONSTRAINT inbound_message_tenant_identity_uq UNIQUE (tenant_id, inbound_message_id),
    CONSTRAINT inbound_message_provider_uq UNIQUE (tenant_id, channel, provider_message_id)
);

ALTER TABLE messaging.message_template ADD CONSTRAINT message_template_tenant_fk FOREIGN KEY (tenant_id) REFERENCES core.tenant (tenant_id);
ALTER TABLE messaging.message_template ADD CONSTRAINT message_template_property_fk FOREIGN KEY (tenant_id, property_id) REFERENCES core.property (tenant_id, property_id);
ALTER TABLE messaging.message_template_version ADD CONSTRAINT message_template_version_message_template_id_fk FOREIGN KEY (tenant_id, message_template_id) REFERENCES messaging.message_template (tenant_id, message_template_id) ON DELETE RESTRICT;
CREATE INDEX message_template_version_message_template_id_ix ON messaging.message_template_version (tenant_id, message_template_id);
CREATE INDEX message_template_version_scope_ix ON messaging.message_template_version (tenant_id, property_id);
ALTER TABLE messaging.message_template_version ADD CONSTRAINT message_template_version_tenant_fk FOREIGN KEY (tenant_id) REFERENCES core.tenant (tenant_id);
ALTER TABLE messaging.message_template_version ADD CONSTRAINT message_template_version_property_fk FOREIGN KEY (tenant_id, property_id) REFERENCES core.property (tenant_id, property_id);
ALTER TABLE messaging.reminder_rule ADD CONSTRAINT reminder_rule_message_template_id_fk FOREIGN KEY (tenant_id, message_template_id) REFERENCES messaging.message_template (tenant_id, message_template_id) ON DELETE RESTRICT;
CREATE INDEX reminder_rule_message_template_id_ix ON messaging.reminder_rule (tenant_id, message_template_id);
ALTER TABLE messaging.reminder_rule ADD CONSTRAINT reminder_rule_service_id_fk FOREIGN KEY (tenant_id, service_id) REFERENCES catalog.service (tenant_id, service_id) ON DELETE RESTRICT;
CREATE INDEX reminder_rule_service_id_ix ON messaging.reminder_rule (tenant_id, service_id);
CREATE INDEX reminder_rule_scope_ix ON messaging.reminder_rule (tenant_id, property_id);
ALTER TABLE messaging.reminder_rule ADD CONSTRAINT reminder_rule_tenant_fk FOREIGN KEY (tenant_id) REFERENCES core.tenant (tenant_id);
ALTER TABLE messaging.reminder_rule ADD CONSTRAINT reminder_rule_property_fk FOREIGN KEY (tenant_id, property_id) REFERENCES core.property (tenant_id, property_id);
ALTER TABLE messaging.scheduled_message ADD CONSTRAINT scheduled_message_guest_id_fk FOREIGN KEY (tenant_id, guest_id) REFERENCES guest.guest (tenant_id, guest_id) ON DELETE RESTRICT;
CREATE INDEX scheduled_message_guest_id_ix ON messaging.scheduled_message (tenant_id, guest_id);
ALTER TABLE messaging.scheduled_message ADD CONSTRAINT scheduled_message_appointment_id_fk FOREIGN KEY (tenant_id, property_id, appointment_id) REFERENCES scheduling.appointment (tenant_id, property_id, appointment_id) ON DELETE RESTRICT;
CREATE INDEX scheduled_message_appointment_id_ix ON messaging.scheduled_message (tenant_id, property_id, appointment_id);
ALTER TABLE messaging.scheduled_message ADD CONSTRAINT scheduled_message_message_template_version_id_fk FOREIGN KEY (tenant_id, message_template_version_id) REFERENCES messaging.message_template_version (tenant_id, message_template_version_id) ON DELETE RESTRICT;
CREATE INDEX scheduled_message_message_template_version_id_ix ON messaging.scheduled_message (tenant_id, message_template_version_id);
ALTER TABLE messaging.scheduled_message ADD CONSTRAINT scheduled_message_reminder_rule_id_fk FOREIGN KEY (tenant_id, reminder_rule_id) REFERENCES messaging.reminder_rule (tenant_id, reminder_rule_id) ON DELETE RESTRICT;
CREATE INDEX scheduled_message_reminder_rule_id_ix ON messaging.scheduled_message (tenant_id, reminder_rule_id);
ALTER TABLE messaging.scheduled_message ADD CONSTRAINT scheduled_message_consent_record_id_fk FOREIGN KEY (tenant_id, consent_record_id) REFERENCES guest.consent_record (tenant_id, consent_id) ON DELETE RESTRICT;
CREATE INDEX scheduled_message_consent_record_id_ix ON messaging.scheduled_message (tenant_id, consent_record_id);
ALTER TABLE messaging.scheduled_message ADD CONSTRAINT scheduled_message_tenant_fk FOREIGN KEY (tenant_id) REFERENCES core.tenant (tenant_id);
ALTER TABLE messaging.scheduled_message ADD CONSTRAINT scheduled_message_property_fk FOREIGN KEY (tenant_id, property_id) REFERENCES core.property (tenant_id, property_id);
ALTER TABLE messaging.message_delivery ADD CONSTRAINT message_delivery_scheduled_message_id_fk FOREIGN KEY (tenant_id, property_id, scheduled_message_id) REFERENCES messaging.scheduled_message (tenant_id, property_id, scheduled_message_id) ON DELETE RESTRICT;
CREATE INDEX message_delivery_scheduled_message_id_ix ON messaging.message_delivery (tenant_id, property_id, scheduled_message_id);
ALTER TABLE messaging.message_delivery ADD CONSTRAINT message_delivery_tenant_fk FOREIGN KEY (tenant_id) REFERENCES core.tenant (tenant_id);
ALTER TABLE messaging.message_delivery ADD CONSTRAINT message_delivery_property_fk FOREIGN KEY (tenant_id, property_id) REFERENCES core.property (tenant_id, property_id);
ALTER TABLE messaging.message_suppression ADD CONSTRAINT message_suppression_guest_id_fk FOREIGN KEY (tenant_id, guest_id) REFERENCES guest.guest (tenant_id, guest_id) ON DELETE RESTRICT;
CREATE INDEX message_suppression_guest_id_ix ON messaging.message_suppression (tenant_id, guest_id);
ALTER TABLE messaging.message_suppression ADD CONSTRAINT message_suppression_tenant_fk FOREIGN KEY (tenant_id) REFERENCES core.tenant (tenant_id);
ALTER TABLE messaging.inbound_message ADD CONSTRAINT inbound_message_guest_id_fk FOREIGN KEY (tenant_id, guest_id) REFERENCES guest.guest (tenant_id, guest_id) ON DELETE RESTRICT;
CREATE INDEX inbound_message_guest_id_ix ON messaging.inbound_message (tenant_id, guest_id);
ALTER TABLE messaging.inbound_message ADD CONSTRAINT inbound_message_in_reply_to_scheduled_message_id_fk FOREIGN KEY (tenant_id, property_id, in_reply_to_scheduled_message_id) REFERENCES messaging.scheduled_message (tenant_id, property_id, scheduled_message_id) ON DELETE RESTRICT;
CREATE INDEX inbound_message_in_reply_to_scheduled_message_id_ix ON messaging.inbound_message (tenant_id, property_id, in_reply_to_scheduled_message_id);
ALTER TABLE messaging.inbound_message ADD CONSTRAINT inbound_message_tenant_fk FOREIGN KEY (tenant_id) REFERENCES core.tenant (tenant_id);
ALTER TABLE messaging.inbound_message ADD CONSTRAINT inbound_message_property_fk FOREIGN KEY (tenant_id, property_id) REFERENCES core.property (tenant_id, property_id);

CREATE TRIGGER message_template_touch BEFORE UPDATE ON messaging.message_template FOR EACH ROW EXECUTE FUNCTION core.touch_versioned();
CREATE TRIGGER message_template_version_touch BEFORE UPDATE ON messaging.message_template_version FOR EACH ROW EXECUTE FUNCTION core.touch_versioned();
CREATE TRIGGER reminder_rule_touch BEFORE UPDATE ON messaging.reminder_rule FOR EACH ROW EXECUTE FUNCTION core.touch_versioned();
CREATE TRIGGER scheduled_message_touch BEFORE UPDATE ON messaging.scheduled_message FOR EACH ROW EXECUTE FUNCTION core.touch_versioned();
CREATE TRIGGER message_delivery_append_only BEFORE UPDATE OR DELETE ON messaging.message_delivery FOR EACH ROW EXECUTE FUNCTION core.forbid_mutation();
DO $$ BEGIN PERFORM core.ensure_monthly_partitions('messaging.message_delivery'::regclass, (date_trunc('month', now() AT TIME ZONE 'UTC') - interval '1 month')::date, 4); END $$;
CREATE TABLE messaging.message_delivery_default PARTITION OF messaging.message_delivery DEFAULT;
CREATE TRIGGER message_suppression_touch BEFORE UPDATE ON messaging.message_suppression FOR EACH ROW EXECUTE FUNCTION core.touch_versioned();
CREATE TRIGGER inbound_message_append_only BEFORE UPDATE OR DELETE ON messaging.inbound_message FOR EACH ROW EXECUTE FUNCTION core.forbid_mutation();
CREATE INDEX scheduled_message_due_ix ON messaging.scheduled_message (send_after) WHERE status = 'Scheduled';
CREATE INDEX message_delivery_message_ix ON messaging.message_delivery (tenant_id, scheduled_message_id, occurred_at);
CREATE INDEX message_suppression_lookup_ix ON messaging.message_suppression (tenant_id, channel, lookup_hash) WHERE status = 'Active';
