-- 12 reporting: generated by database/tools/generate.py from database/model/. Do not edit.
-- may reference: core

CREATE SCHEMA IF NOT EXISTS reporting AUTHORIZATION spms_owner;

CREATE TABLE reporting.report_run (
    report_run_id                  uuid NOT NULL DEFAULT core.uuid_v7(),
    tenant_id                      uuid NOT NULL,
    property_id                    uuid,
    report_id                      text NOT NULL,
    definition_version             text NOT NULL,
    definition_sha256              char(64) NOT NULL,
    filters                        jsonb NOT NULL DEFAULT '{}',
    as_of                          timestamptz NOT NULL,
    source_watermark               timestamptz,
    result_json                    jsonb,
    result_sha256                  char(64),
    error_code                     text,
    started_at                     timestamptz,
    completed_at                   timestamptz,
    expires_at                     timestamptz NOT NULL,
    is_closed_snapshot             boolean NOT NULL DEFAULT false,
    status                         text NOT NULL DEFAULT 'Queued',
    version                        integer NOT NULL DEFAULT 1,
    created_at                     timestamptz NOT NULL DEFAULT now(),
    created_by                     uuid,
    updated_at                     timestamptz NOT NULL DEFAULT now(),
    updated_by                     uuid,
    correlation_id                 text,
    CONSTRAINT report_run_pkey PRIMARY KEY (report_run_id),
    CONSTRAINT report_run_version_ck CHECK (version >= 1),
    CONSTRAINT report_run_tenant_identity_uq UNIQUE (tenant_id, report_run_id),
    CONSTRAINT report_run_status_known CHECK (status IN ('Queued', 'Running', 'Succeeded', 'Failed', 'Expired')),
    CONSTRAINT report_run_succeeded_complete CHECK (status <> 'Succeeded' OR (result_sha256 IS NOT NULL AND completed_at IS NOT NULL))
);

CREATE TABLE reporting.report_schedule (
    report_schedule_id             uuid NOT NULL DEFAULT core.uuid_v7(),
    tenant_id                      uuid NOT NULL,
    property_id                    uuid,
    report_id                      text NOT NULL,
    owner_principal_id             uuid NOT NULL,
    filters                        jsonb NOT NULL DEFAULT '{}',
    timezone                       text NOT NULL,
    local_hour                     smallint NOT NULL,
    local_minute                   smallint NOT NULL,
    next_run_at                    timestamptz NOT NULL,
    last_run_id                    uuid,
    status                         text NOT NULL DEFAULT 'Active',
    effective_from                 timestamptz NOT NULL DEFAULT now(),
    effective_to                   timestamptz,
    version                        integer NOT NULL DEFAULT 1,
    created_at                     timestamptz NOT NULL DEFAULT now(),
    created_by                     uuid,
    updated_at                     timestamptz NOT NULL DEFAULT now(),
    updated_by                     uuid,
    correlation_id                 text,
    CONSTRAINT report_schedule_pkey PRIMARY KEY (report_schedule_id),
    CONSTRAINT report_schedule_local_hour_ck CHECK (local_hour BETWEEN 0 AND 23),
    CONSTRAINT report_schedule_local_minute_ck CHECK (local_minute BETWEEN 0 AND 59),
    CONSTRAINT report_schedule_version_ck CHECK (version >= 1),
    CONSTRAINT report_schedule_tenant_identity_uq UNIQUE (tenant_id, report_schedule_id),
    CONSTRAINT report_schedule_status_known CHECK (status IN ('Active', 'Paused', 'Retired')),
    CONSTRAINT report_schedule_effective_range_ck CHECK (effective_to IS NULL OR effective_to > effective_from)
);

CREATE TABLE reporting.reporting_fact (
    reporting_fact_id              uuid NOT NULL DEFAULT core.uuid_v7(),
    tenant_id                      uuid NOT NULL,
    property_id                    uuid,
    fact_family                    text NOT NULL,
    metric_key                     text NOT NULL,
    event_type                     text NOT NULL,
    source_id                      text NOT NULL,
    source_version                 integer NOT NULL,
    evidence_kind                  text NOT NULL DEFAULT 'Operational',
    staff_id                       uuid,
    guest_id                       uuid,
    visit_id                       uuid,
    service_id                     uuid,
    inventory_item_variant_id      uuid,
    location_id                    uuid,
    channel                        text NOT NULL DEFAULT 'Direct',
    member_plan                    text,
    fact_status                    text,
    quantity                       numeric(24,6) NOT NULL DEFAULT 0,
    amount_minor                   bigint NOT NULL DEFAULT 0,
    expected_minor                 bigint,
    denominator                    numeric(24,6) NOT NULL DEFAULT 0,
    currency_code                  char(3),
    occurred_at                    timestamptz NOT NULL DEFAULT now(),
    created_by                     uuid,
    correlation_id                 text,
    CONSTRAINT reporting_fact_pkey PRIMARY KEY (reporting_fact_id, occurred_at),
    CONSTRAINT reporting_fact_currency_code_ck CHECK (currency_code ~ '^[A-Z]{3}$')
) PARTITION BY RANGE (occurred_at);

CREATE INDEX report_run_scope_ix ON reporting.report_run (tenant_id, property_id);
ALTER TABLE reporting.report_run ADD CONSTRAINT report_run_tenant_fk FOREIGN KEY (tenant_id) REFERENCES core.tenant (tenant_id);
ALTER TABLE reporting.report_run ADD CONSTRAINT report_run_property_fk FOREIGN KEY (tenant_id, property_id) REFERENCES core.property (tenant_id, property_id);
ALTER TABLE reporting.report_schedule ADD CONSTRAINT report_schedule_owner_principal_id_fk FOREIGN KEY (tenant_id, owner_principal_id) REFERENCES core.principal (tenant_id, principal_id) ON DELETE RESTRICT;
CREATE INDEX report_schedule_owner_principal_id_ix ON reporting.report_schedule (tenant_id, owner_principal_id);
ALTER TABLE reporting.report_schedule ADD CONSTRAINT report_schedule_last_run_id_fk FOREIGN KEY (tenant_id, last_run_id) REFERENCES reporting.report_run (tenant_id, report_run_id) ON DELETE RESTRICT;
CREATE INDEX report_schedule_last_run_id_ix ON reporting.report_schedule (tenant_id, last_run_id);
CREATE INDEX report_schedule_scope_ix ON reporting.report_schedule (tenant_id, property_id);
ALTER TABLE reporting.report_schedule ADD CONSTRAINT report_schedule_tenant_fk FOREIGN KEY (tenant_id) REFERENCES core.tenant (tenant_id);
ALTER TABLE reporting.report_schedule ADD CONSTRAINT report_schedule_property_fk FOREIGN KEY (tenant_id, property_id) REFERENCES core.property (tenant_id, property_id);
CREATE INDEX reporting_fact_scope_ix ON reporting.reporting_fact (tenant_id, property_id);
ALTER TABLE reporting.reporting_fact ADD CONSTRAINT reporting_fact_tenant_fk FOREIGN KEY (tenant_id) REFERENCES core.tenant (tenant_id);
ALTER TABLE reporting.reporting_fact ADD CONSTRAINT reporting_fact_property_fk FOREIGN KEY (tenant_id, property_id) REFERENCES core.property (tenant_id, property_id);

CREATE TRIGGER report_run_touch BEFORE UPDATE ON reporting.report_run FOR EACH ROW EXECUTE FUNCTION core.touch_versioned();
CREATE TRIGGER report_schedule_touch BEFORE UPDATE ON reporting.report_schedule FOR EACH ROW EXECUTE FUNCTION core.touch_versioned();
CREATE TRIGGER reporting_fact_append_only BEFORE UPDATE OR DELETE ON reporting.reporting_fact FOR EACH ROW EXECUTE FUNCTION core.forbid_mutation();
DO $$ BEGIN PERFORM core.ensure_monthly_partitions('reporting.reporting_fact'::regclass, (date_trunc('month', now() AT TIME ZONE 'UTC') - interval '1 month')::date, 4); END $$;
CREATE TABLE reporting.reporting_fact_default PARTITION OF reporting.reporting_fact DEFAULT;
CREATE INDEX reporting_fact_family_ix ON reporting.reporting_fact (tenant_id, fact_family, occurred_at);
CREATE INDEX reporting_fact_source_ix ON reporting.reporting_fact (tenant_id, source_id, source_version);
